import { z } from 'zod';
import {
    BaseCommerceMediaSchema,
    CommerceMediaStateSchema
} from '../../../common/commerce-media.schema.js';
import { ImageAttributionSchema, mediaAssetUrl } from '../../../common/media.schema.js';
import { ModerationStatusEnumSchema } from '../../../enums/index.js';

/**
 * Enum schema for the visibility state of a single experience media row.
 * Re-exports the shared {@link CommerceMediaStateSchema} under the
 * per-vertical name used by experience media endpoints/services.
 *
 * @see packages/db/src/schemas/experience/experience_media.dbschema.ts
 */
export const ExperienceMediaStateSchema = CommerceMediaStateSchema;
export type ExperienceMediaState = z.infer<typeof ExperienceMediaStateSchema>;

/**
 * Zod schema for a single row in the `experience_media` table.
 *
 * Extends {@link BaseCommerceMediaSchema} (shared with `gastronomy_media`)
 * with the two fields that differ per vertical: `id` and the parent FK
 * (`experienceId`). See the base schema's JSDoc for the full field-level
 * documentation shared by both commerce verticals.
 *
 * @see packages/db/src/schemas/experience/experience_media.dbschema.ts
 */
export const ExperienceMediaSchema = BaseCommerceMediaSchema.extend({
    /** UUID primary key for this media row. */
    id: z.string().uuid({ message: 'zodError.common.id.invalidUuid' }),
    /** UUID of the parent experience listing (FK → experiences.id). */
    experienceId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' })
});

/**
 * Type inferred from `ExperienceMediaSchema`.
 *
 * Structurally compatible with `SelectExperienceMedia` (the Drizzle-inferred
 * type) so the model generic `BaseModelImpl<ExperienceMedia>` typechecks
 * without casts.
 */
export type ExperienceMedia = z.infer<typeof ExperienceMediaSchema>;

// ----------------------------------------------------------------------------
// Command Input Schemas
// ----------------------------------------------------------------------------

/**
 * Input payload for adding a single photo to an experience listing gallery.
 *
 * This is a URL-receiver schema: the upload to Cloudinary has already
 * happened via `POST /api/v1/admin/media/upload`. This endpoint registers
 * the already-uploaded URL as a new `experience_media` row.
 *
 * Server-controlled fields are intentionally EXCLUDED from the input:
 * - `id`            — generated by the DB
 * - `experienceId`  — comes from the URL param `/:id`
 * - `sortOrder`     — computed as max(visible sortOrder) + 1 (append to end)
 * - `isFeatured`    — always `false` on create; managed by a separate endpoint
 * - `state`         — always `'visible'` on create
 * - `archivedAt`    — null on create (set when archiving)
 * - Audit timestamps — set by the DB
 */
export const ExperienceMediaAddPayloadSchema = z.object({
    /**
     * Full public URL of the photo (Cloudinary delivery URL or external CDN).
     * Required — the upload endpoint returns this URL before this call is made.
     */
    url: mediaAssetUrl('zodError.common.commerceMedia.url.invalid'),
    /**
     * Cloudinary `public_id` (e.g. `hospeda/dev/abc123`).
     * Optional — historic or external-URL payloads may not carry one.
     */
    publicId: z
        .string()
        .min(1, { message: 'zodError.common.commerceMedia.publicId.min' })
        .optional(),
    /**
     * Short display caption (max 100 chars).
     * Optional — not all photos include a caption.
     */
    caption: z
        .string()
        .min(3, { message: 'zodError.common.commerceMedia.caption.min' })
        .max(100, { message: 'zodError.common.commerceMedia.caption.max' })
        .optional(),
    /**
     * Longer description of photo content (max 300 chars).
     * Optional.
     */
    description: z
        .string()
        .min(10, { message: 'zodError.common.commerceMedia.description.min' })
        .max(300, { message: 'zodError.common.commerceMedia.description.max' })
        .optional(),
    /**
     * Accessible alt text for `<img alt>` and screen readers.
     * Optional; falls back to caption / listing name at render time.
     */
    alt: z
        .string()
        .min(1, { message: 'zodError.common.commerceMedia.alt.min' })
        .max(200, { message: 'zodError.common.commerceMedia.alt.max' })
        .optional(),
    /**
     * Optional credits/source metadata (photographer, sourceUrl, license).
     */
    attribution: ImageAttributionSchema.nullable().optional(),
    /**
     * Content moderation state supplied by the upload endpoint.
     * When omitted the service defaults to `'PENDING'`.
     * Upload endpoint pre-approves images, so callers should pass `'APPROVED'`.
     */
    moderationState: ModerationStatusEnumSchema.optional()
});

/** Inferred type for the add-media payload. */
export type ExperienceMediaAddPayload = z.infer<typeof ExperienceMediaAddPayloadSchema>;

/**
 * Full service input for `ExperienceService.addMedia`.
 * Combines the URL param `experienceId` with the photo payload.
 */
export const ExperienceMediaAddInputSchema = z.object({
    /** UUID of the parent experience listing (from URL param `/:id`). */
    experienceId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' }),
    /** Photo payload received from the caller. */
    media: ExperienceMediaAddPayloadSchema
});

/** Inferred type for the full add-media service input. */
export type ExperienceMediaAddInput = z.infer<typeof ExperienceMediaAddInputSchema>;

// ----------------------------------------------------------------------------
// Command Output Schemas
// ----------------------------------------------------------------------------

/**
 * Single-row output schema for add-media / update-media / get-media-by-id responses.
 * Wraps the created/updated `ExperienceMedia` row in a `media` key, mirroring
 * the `{ faq: ... }` envelope used by FAQ endpoints.
 */
export const ExperienceMediaSingleOutputSchema = z.object({
    media: ExperienceMediaSchema
});

/** Inferred type for a single-media response. */
export type ExperienceMediaSingleOutput = z.infer<typeof ExperienceMediaSingleOutputSchema>;

/**
 * List output schema for `GET /:id/media` responses.
 * Wraps an ordered array of `ExperienceMedia` rows in a `media` key, mirroring
 * the `{ faqs: [...] }` envelope used by FAQ list endpoints.
 */
export const ExperienceMediaListOutputSchema = z.object({
    media: z.array(ExperienceMediaSchema)
});

/** Inferred type for a media list response. */
export type ExperienceMediaListOutput = z.infer<typeof ExperienceMediaListOutputSchema>;

// ----------------------------------------------------------------------------
// Remove Input Schema
// ----------------------------------------------------------------------------

/**
 * Service input schema for removing a single media row from an experience
 * listing gallery. The row is soft-deleted and the remaining visible rows
 * are resequenced.
 */
export const ExperienceMediaRemoveInputSchema = z.object({
    /** UUID of the parent experience listing (from URL param `/:id`). */
    experienceId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' }),
    /** UUID of the media row to remove (from URL param `/:mediaId`). */
    mediaId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' })
});

/** Inferred type for the remove-media service input. */
export type ExperienceMediaRemoveInput = z.infer<typeof ExperienceMediaRemoveInputSchema>;

// ----------------------------------------------------------------------------
// Reorder Input Schema
// ----------------------------------------------------------------------------

/**
 * HTTP payload schema for `PATCH /:id/media/reorder`.
 * The caller supplies the full ordered list of visible media UUIDs; the
 * service validates that this set matches the current visible rows exactly
 * and then applies the new `sortOrder` positions.
 */
export const ExperienceMediaReorderPayloadSchema = z.object({
    /**
     * Ordered array of `experience_media` UUIDs.
     * Must contain exactly the same IDs as the current visible rows — no
     * extras, no missing entries. The service rejects any mismatch with
     * `VALIDATION_ERROR`.
     */
    orderedIds: z
        .array(z.string().uuid({ message: 'zodError.common.id.invalidUuid' }), {
            message: 'zodError.experience.media.reorder.orderedIds.invalid'
        })
        .min(1, { message: 'zodError.experience.media.reorder.orderedIds.min' })
});

/** Inferred type for the reorder payload. */
export type ExperienceMediaReorderPayload = z.infer<typeof ExperienceMediaReorderPayloadSchema>;

/**
 * Service input schema for reordering an experience listing's gallery.
 * Combines the URL param `experienceId` with the ordered-ids payload.
 */
export const ExperienceMediaReorderInputSchema = z.object({
    /** UUID of the parent experience listing (from URL param `/:id`). */
    experienceId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' }),
    /** Ordered array of visible media UUIDs. */
    orderedIds: ExperienceMediaReorderPayloadSchema.shape.orderedIds
});

/** Inferred type for the reorder service input. */
export type ExperienceMediaReorderInput = z.infer<typeof ExperienceMediaReorderInputSchema>;

// ----------------------------------------------------------------------------
// List Input Schema
// ----------------------------------------------------------------------------

/**
 * Service input schema for listing an experience listing's media rows.
 * Supports an optional `state` filter (defaults to `'visible'`).
 */
export const ExperienceMediaListInputSchema = z.object({
    /** UUID of the parent experience listing (from URL param `/:id`). */
    experienceId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' }),
    /**
     * Visibility state filter.
     * Defaults to `'visible'` (active gallery photos).
     * Pass `'archived'` to list photos moved out of the gallery.
     */
    state: ExperienceMediaStateSchema.optional()
});

/** Inferred type for the list-media service input. */
export type ExperienceMediaListInput = z.infer<typeof ExperienceMediaListInputSchema>;

// ----------------------------------------------------------------------------
// Set Featured Input Schema
// ----------------------------------------------------------------------------

/**
 * Service input schema for setting the featured photo of an experience listing.
 *
 * Targets a specific `experience_media` row by ID and promotes it to
 * `is_featured = true`. The previous featured row (if any) is cleared in the
 * same transaction.
 *
 * DB invariants enforced (extras carril, mirroring accommodation's T-003):
 * - At most ONE featured row per listing (partial unique index).
 * - A featured photo can never be `state = 'archived'` (CHECK constraint).
 * The service validates that the target row is `state = 'visible'` before
 * writing to avoid tripping the CHECK constraint.
 */
export const ExperienceMediaSetFeaturedInputSchema = z.object({
    /** UUID of the parent experience listing (from URL param `/:id`). */
    experienceId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' }),
    /** UUID of the media row to promote as featured (from URL param `/:mediaId`). */
    mediaId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' })
});

/** Inferred type for the set-featured service input. */
export type ExperienceMediaSetFeaturedInput = z.infer<typeof ExperienceMediaSetFeaturedInputSchema>;

// ----------------------------------------------------------------------------
// Archive Photo Input Schema
// ----------------------------------------------------------------------------

/**
 * Service input schema for archiving a single experience photo.
 *
 * Flips `state = 'archived'` and sets `archivedAt = NOW()` on the target row.
 * A FEATURED photo cannot be archived — the DB CHECK constraint enforces
 * `NOT (is_featured AND state = 'archived')`. The service rejects the request
 * before reaching the DB when `isFeatured = true`.
 */
export const ExperienceMediaArchiveInputSchema = z.object({
    /** UUID of the parent experience listing (from URL param `/:id`). */
    experienceId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' }),
    /** UUID of the media row to archive (from URL param `/:mediaId`). */
    mediaId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' })
});

/** Inferred type for the archive-media service input. */
export type ExperienceMediaArchiveInput = z.infer<typeof ExperienceMediaArchiveInputSchema>;

// ----------------------------------------------------------------------------
// Restore Photo Input Schema
// ----------------------------------------------------------------------------

/**
 * Service input schema for restoring an archived experience photo.
 *
 * Flips `state = 'visible'`, clears `archivedAt = NULL`, and appends the row
 * at the END of the current visible gallery (`sortOrder = max visible + 1`).
 */
export const ExperienceMediaRestoreInputSchema = z.object({
    /** UUID of the parent experience listing (from URL param `/:id`). */
    experienceId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' }),
    /** UUID of the archived media row to restore (from URL param `/:mediaId`). */
    mediaId: z.string().uuid({ message: 'zodError.common.id.invalidUuid' })
});

/** Inferred type for the restore-media service input. */
export type ExperienceMediaRestoreInput = z.infer<typeof ExperienceMediaRestoreInputSchema>;
