-- =============================================================================
-- 0008_strip_accommodation_description_markdown.sql
--
-- SPEC-187 P0 (PR-1) — strip markdown markers from accommodation.description.
--
-- Why this migration exists:
--   Per SPEC-187 FR-9 (PD-1), the `accommodation.description` column currently
--   stores markdown source authored through the rich-text editor. Phase 1 of
--   SPEC-187 reverts the public detail page to render that field as plain
--   text (FR-2), which means any leftover markdown markers (`**`, `##`,
--   `[text](url)`, etc.) will be displayed verbatim to guests.
--
--   To avoid a content regression, this migration is REQUIRED before Phase 1
--   lands on staging: it strips every known markdown marker from the column
--   in place, so the public detail page renders clean text after FR-2 flips
--   the render path.
--
-- Carril:
--   1 — versioned, hand-written, journal-tracked. NOT generated by
--   `pnpm db:generate` (no schema change). Per `packages/db/CLAUDE.md`
--   "Golden Rule": data-only transformations land in `src/migrations/`.
--
-- PD-1 (rule reuse):
--   The strip regex set mirrors `apps/api/src/utils/entitlement-filter.ts:188-199`
--   (the actual `stripMarkdown` function in the JS entitlement-filter). The PL/pgSQL
--   function below applies the same transformations in SQL. Any change here MUST
--   be mirrored in the JS implementation, and vice versa, to avoid drift.
--
-- PD-3 (rollback unit):
--   This migration is intentionally separate from the Phase 2
--   `add_rich_description.sql` (which adds the `rich_description` column). The
--   strip can be reverted without losing the column, and the column add can be
--   reverted without re-introducing markers in `description`.
--
-- The function is `IMMUTABLE` and is dropped at the end of this script — it
-- exists only to power this one-shot UPDATE and is not part of the runtime
-- schema.
-- =============================================================================

CREATE OR REPLACE FUNCTION strip_markdown(input text) RETURNS text AS $$
DECLARE
    result text;
BEGIN
    result := input;
    -- PD-1: same regex set as apps/api/src/utils/entitlement-filter.ts:188-199.
    -- Order matters: bold (`**`) MUST run before italic (`*`) so `**foo**`
    -- is not partially consumed as `*foo*`.
    result := regexp_replace(result, '\*\*(.+?)\*\*', '\1', 'g');     -- bold
    result := regexp_replace(result, '\*(.+?)\*', '\1', 'g');         -- italic
    result := regexp_replace(result, '~~(.+?)~~', '\1', 'g');         -- strikethrough
    result := regexp_replace(result, '`(.+?)`', '\1', 'g');           -- inline code
    result := regexp_replace(result, '\[(.+?)\]\(.+?\)', '\1', 'g');  -- links
    result := regexp_replace(result, '!\[(.+?)\]\(.+?\)', '\1', 'g'); -- images
    result := regexp_replace(result, '^#+\s+', '', 'gm');             -- headings
    result := regexp_replace(result, '^[-*+]\s+', '', 'gm');          -- unordered list bullets
    result := regexp_replace(result, '^>\s+', '', 'gm');              -- blockquotes
    result := regexp_replace(result, '\n{3,}', '\n\n', 'g');          -- collapse 3+ blank lines
    result := trim(result);
    RETURN result;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
--> statement-breakpoint
-- Gate the UPDATE on rows that actually contain markers so the migration is
-- cheap on already-clean rows (regex short-circuits on the first match).
UPDATE "accommodations"
SET "description" = strip_markdown("description")
WHERE "description" ~ '[*_#`\[\]>~]';
--> statement-breakpoint
-- One-off cleanup: the function is not part of the runtime schema.
DROP FUNCTION strip_markdown(text);
