-- =============================================================================
-- 0011_restrip_accommodation_description_markdown.sql
--
-- SPEC-187 follow-up (P0 re-strip) — re-strip accommodation.description with the
-- CORRECTED markdown rules. Cleans up what 0008 left behind.
--
-- Why this migration exists:
--   0008_strip_accommodation_description_markdown.sql stripped markdown from
--   accommodation.description in place, but its strip_markdown() function had
--   three verified bugs that let markdown survive into the public plain-text
--   render:
--     (a) Underscore emphasis (`_em_`, `__strong__`) was NEVER stripped, even
--         though 0008's gate predicate `~ '[*_#`\[\]>~]'` selected rows that
--         contained `_`. So underscore-markdown survived.
--     (b) The image rule ran AFTER the link rule, so `![alt](url)` was turned
--         into the orphan `!alt` (the link rule consumed `[alt](url)` first,
--         leaving a stray leading `!`).
--     (c) (newline collapse — already correct in 0008, kept here for parity.)
--
--   This migration re-strips with the corrected, canonical order so:
--     - surviving `_em_` / `__strong__` underscore markers are removed;
--     - any FULL `![alt](url)` image markers that somehow remain collapse to
--       their alt text (image rule now runs BEFORE the link rule);
--     - excess blank lines are collapsed.
--
-- Canonical lockstep:
--   The transformation order below is byte-identical (in observable output) to
--   the JS source of truth `stripMarkdown` in
--   `apps/api/src/utils/entitlement-filter.ts` and the web mirror
--   `stripMarkdownPlain` / `STRIP_MARKDOWN_REGEX_SET` in
--   `apps/web/src/lib/render-plain.ts` (PD-1). Any change here MUST be mirrored
--   in those functions, and vice versa. Reference them BY NAME, not line number.
--
-- Lossy-artifact note (orphan `!`):
--   0008 turned `![alt](url)` into `!alt` in place. That transformation is
--   LOSSY: once the `[alt](url)` structure is gone, a stray `!alt` is
--   indistinguishable from a legitimate exclamation (`!important`, `!alarm`).
--   This migration therefore does NOT blanket-strip `!` (doing so would corrupt
--   real content). It only collapses FULL image markers that are still intact.
--   The corrected canonical strip_markdown() prevents NEW orphan `!` from ever
--   being produced; pre-existing orphans from 0008 (if any) are accepted as
--   irrecoverable plain text. The operational pre-migration table dump (handled
--   in the prod runbook) is the recovery path for the original source if needed.
--
-- Carril:
--   1 — versioned, hand-written, journal-tracked. NOT generated by
--   `pnpm db:generate` (no schema change). Per `packages/db/CLAUDE.md`
--   "Golden Rule": data-only transformations land in `src/migrations/`.
--
-- Idempotency:
--   Safe to re-run. The function is deterministic and the UPDATE is gated on
--   rows that still contain a strip-able marker. After one pass, no gated rows
--   remain (the corrected function removes every marker the gate looks for, so
--   a second run matches 0 rows). The function is IMMUTABLE and dropped at the
--   end — it is not part of the runtime schema.
--
-- Does NOT alter 0008 (already applied on staging; changing it would diverge
-- staging from prod). This is a separate, additive forward migration.
-- =============================================================================

CREATE OR REPLACE FUNCTION strip_markdown(input text) RETURNS text AS $$
DECLARE
    result text;
BEGIN
    result := input;
    -- Canonical order — mirrors apps/api/src/utils/entitlement-filter.ts
    -- (stripMarkdown). Order is load-bearing:
    --   * bold (`**`) before italic (`*`) and bold-underscore (`__`) before
    --     italic-underscore (`_`) so paired markers are not partial-consumed;
    --   * image (`![...]( ...)`) BEFORE link (`[...]( ...)`) so an image marker
    --     collapses to its alt text instead of leaving an orphan `!`.
    result := regexp_replace(result, '\*\*(.+?)\*\*', '\1', 'g');     -- bold **text**
    result := regexp_replace(result, '\*(.+?)\*', '\1', 'g');         -- italic *text*
    result := regexp_replace(result, '__(.+?)__', '\1', 'g');         -- bold __text__
    result := regexp_replace(result, '_(.+?)_', '\1', 'g');           -- italic _text_
    result := regexp_replace(result, '~~(.+?)~~', '\1', 'g');         -- strikethrough
    result := regexp_replace(result, '`(.+?)`', '\1', 'g');           -- inline code
    result := regexp_replace(result, '!\[(.+?)\]\(.+?\)', '\1', 'g'); -- images (BEFORE links)
    result := regexp_replace(result, '\[(.+?)\]\(.+?\)', '\1', 'g');  -- links
    result := regexp_replace(result, '^#+\s+', '', 'gm');             -- headings
    result := regexp_replace(result, '^[-*+]\s+', '', 'gm');          -- unordered list bullets
    result := regexp_replace(result, '^>\s+', '', 'gm');              -- blockquotes
    result := regexp_replace(result, '\n{3,}', '\n\n', 'g');          -- collapse 3+ blank lines
    result := trim(result);
    RETURN result;
END;
$$ LANGUAGE plpgsql IMMUTABLE;
--> statement-breakpoint
-- Gate the UPDATE on rows that still contain a strip-able marker so the
-- migration is cheap on already-clean rows and idempotent on re-run. The
-- predicate matches the markers the corrected function removes (including `_`
-- for underscore emphasis, which 0008 selected but never stripped).
UPDATE "accommodations"
SET "description" = strip_markdown("description")
WHERE "description" ~ '[*_#`\[\]>~]';
--> statement-breakpoint
-- One-off cleanup: the function is not part of the runtime schema.
DROP FUNCTION strip_markdown(text);
