CREATE TABLE "catalog_key" (
	"key" varchar(64) PRIMARY KEY NOT NULL,
	"kind" varchar(16) NOT NULL,
	"scope" varchar(16) NOT NULL,
	"aggregation_strategy" varchar(16) NOT NULL,
	"enforcement_strategy" varchar(16) NOT NULL,
	"key_class" varchar(16) NOT NULL,
	CONSTRAINT "ck_catalog_key_kind" CHECK ("catalog_key"."kind" IN ('entitlement', 'limit')),
	CONSTRAINT "ck_catalog_key_scope" CHECK ("catalog_key"."scope" IN ('vertical', 'global')),
	CONSTRAINT "ck_catalog_key_aggregation_strategy" CHECK ("catalog_key"."aggregation_strategy" IN ('SUM', 'MAX', 'MIN', 'BEST_DECLARED')),
	CONSTRAINT "ck_catalog_key_enforcement_strategy" CHECK ("catalog_key"."enforcement_strategy" IN ('ARCHIVE', 'UNPUBLISH', 'DISABLE', 'NONE')),
	CONSTRAINT "ck_catalog_key_class" CHECK ("catalog_key"."key_class" IN ('COMERCIAL', 'DE_ACCESO'))
);
--> statement-breakpoint
CREATE TABLE "vertical" (
	"id" varchar(32) PRIMARY KEY NOT NULL,
	"activation_event" varchar(64),
	CONSTRAINT "ck_vertical_id" CHECK ("vertical"."id" IN ('accommodation', 'gastronomy', 'experience', 'tourist', 'partner')),
	CONSTRAINT "ck_vertical_activation_event" CHECK ("vertical"."activation_event" IS NULL OR "vertical"."activation_event" IN ('listing_published', 'start_button_pressed'))
);

--> statement-breakpoint
-- HOS-1430: reference rows, hand-written here until the V1.2 generator regenerates them identically.
-- Order is deterministic: verticals in enum order; keys entitlements first then limits, each sorted by key.
INSERT INTO "vertical" ("id", "activation_event") VALUES
	('accommodation', 'listing_published'),
	('gastronomy', 'listing_published'),
	('experience', 'listing_published'),
	('tourist', 'start_button_pressed'),
	('partner', NULL);
--> statement-breakpoint
INSERT INTO "catalog_key" ("key", "kind", "scope", "aggregation_strategy", "enforcement_strategy", "key_class") VALUES
	('ai_accommodation_import', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('ai_chat', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('ai_search', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('ai_support', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('ai_text_improve', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('ai_translate', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_attach_review_photos', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_compare_accommodations', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_contact_whatsapp_direct', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_contact_whatsapp_display', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_embed_video', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_sync_external_calendar', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_use_calendar', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_use_collections', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_use_rich_description', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_view_recommendations', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('can_view_search_history', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('centralized_booking', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('consolidated_analytics', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('create_promotions', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('custom_branding', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('download_listing_pdf', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('edit_accommodation_info', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('edit_experience_info', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('edit_gastronomy_info', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('exclusive_deals', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('featured_listing', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('has_verification_badge', 'entitlement', 'global', 'MAX', 'NONE', 'COMERCIAL'),
	('issue_experience_certificate', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('manage_experience_directions', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('manage_experience_private_galleries', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('manage_gastronomy_daily_special', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('manage_gastronomy_events', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('manage_gastronomy_menu', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('menu_item_photos', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('menu_qr_scan_metrics', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('multi_property_management', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('multilingual_gastronomy_menu', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('partner_carousel_presence', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('partner_public_page', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('price_alerts', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('priority_support', 'entitlement', 'global', 'MAX', 'NONE', 'COMERCIAL'),
	('publish_accommodations', 'entitlement', 'vertical', 'MAX', 'UNPUBLISH', 'COMERCIAL'),
	('publish_experience', 'entitlement', 'vertical', 'MAX', 'UNPUBLISH', 'COMERCIAL'),
	('publish_gastronomy', 'entitlement', 'vertical', 'MAX', 'UNPUBLISH', 'COMERCIAL'),
	('recover_own_listing', 'entitlement', 'vertical', 'MAX', 'NONE', 'DE_ACCESO'),
	('respond_reviews', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('save_favorites', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('staff_management', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('subscribe_to_plan', 'entitlement', 'vertical', 'MAX', 'NONE', 'DE_ACCESO'),
	('view_advanced_stats', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('view_basic_stats', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('vip_promotions_access', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('vip_support', 'entitlement', 'global', 'MAX', 'NONE', 'COMERCIAL'),
	('vip_visibility_access', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('write_reviews', 'entitlement', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('max_accommodations', 'limit', 'vertical', 'SUM', 'UNPUBLISH', 'COMERCIAL'),
	('max_active_alerts', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_active_private_galleries', 'limit', 'vertical', 'SUM', 'ARCHIVE', 'COMERCIAL'),
	('max_active_promotions', 'limit', 'vertical', 'SUM', 'ARCHIVE', 'COMERCIAL'),
	('max_ai_accommodation_import_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_ai_chat_consumer_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_ai_chat_experience_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_ai_chat_gastronomy_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_ai_chat_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_ai_search_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_ai_support_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_ai_text_improve_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_ai_translate_per_month', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL'),
	('max_collections', 'limit', 'vertical', 'SUM', 'ARCHIVE', 'COMERCIAL'),
	('max_compare_items', 'limit', 'vertical', 'MAX', 'NONE', 'COMERCIAL'),
	('max_experiences', 'limit', 'vertical', 'SUM', 'UNPUBLISH', 'COMERCIAL'),
	('max_favorites', 'limit', 'vertical', 'SUM', 'ARCHIVE', 'COMERCIAL'),
	('max_gastronomies', 'limit', 'vertical', 'SUM', 'UNPUBLISH', 'COMERCIAL'),
	('max_photos_per_accommodation', 'limit', 'vertical', 'SUM', 'ARCHIVE', 'COMERCIAL'),
	('max_properties', 'limit', 'vertical', 'SUM', 'UNPUBLISH', 'COMERCIAL'),
	('max_search_history_entries', 'limit', 'vertical', 'MAX', 'ARCHIVE', 'COMERCIAL'),
	('max_staff_accounts', 'limit', 'vertical', 'SUM', 'DISABLE', 'COMERCIAL');
