/**
 * @file provision-owner.ts
 * @description Admin endpoint to provision a COMMERCE_OWNER account from an
 * approved commerce lead (SPEC-239 T-050).
 *
 * ## Flow
 * 1. Fetch the lead by ID from the database.
 * 2. Instantiate {@link CommerceOwnerProvisioningService} with injected ports
 *    ({@link createCommerceOwnerCreateUserPort} and
 *    {@link createCommerceOwnerCredentialsNotificationPort}).
 * 3. Call `provisionCommerceOwner(actor, { lead })`.
 * 4. Return `{ userId, email, name }` — NEVER the temporary password.
 *
 * ## Security
 * - Gated by `PermissionEnum.COMMERCE_EDIT_ALL` (enforced by `createAdminRoute`
 *   and double-checked inside the provisioning service).
 * - The temporary password is generated by the service, passed to the
 *   notification port, and never included in the HTTP response.
 *
 * @module routes/commerce/admin/provision-owner
 */

import { CommerceLeadModel } from '@repo/db';
import type { CommerceLead } from '@repo/schemas';
import { PermissionEnum, ServiceErrorCode } from '@repo/schemas';
import { CommerceOwnerProvisioningService, ServiceError } from '@repo/service-core';
import { z } from 'zod';
import {
    createCommerceOwnerCreateUserPort,
    createCommerceOwnerCredentialsNotificationPort
} from '../../../lib/commerce-ports';
import { getActorFromContext } from '../../../utils/actor';
import { env } from '../../../utils/env';
import { apiLogger } from '../../../utils/logger';
import { createAdminRoute } from '../../../utils/route-factory';

// ---------------------------------------------------------------------------
// Schemas
// ---------------------------------------------------------------------------

/**
 * Response schema for a successful provisioning.
 * The `temporaryPassword` is intentionally omitted — it exists only inside
 * the service and is delivered to the owner via the credentials email.
 */
const ProvisionOwnerResponseSchema = z.object({
    /** UUID of the newly created COMMERCE_OWNER user. */
    userId: z.string().uuid(),
    /** Email address of the provisioned owner (copied from the lead). */
    email: z.string().email(),
    /** Display name of the provisioned owner (from the lead's contactName). */
    name: z.string()
});

// ---------------------------------------------------------------------------
// Model instance (module-scoped, stateless)
// ---------------------------------------------------------------------------

const commerceLeadModel = new CommerceLeadModel();

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

/**
 * POST /api/v1/admin/commerce/leads/:id/provision-owner
 *
 * Creates a new COMMERCE_OWNER user account for the specified commerce lead.
 *
 * The route:
 * - Requires `COMMERCE_EDIT_ALL` permission.
 * - Fetches the lead and delegates all provisioning logic to
 *   {@link CommerceOwnerProvisioningService}.
 * - Returns only `{ userId, email, name }`.
 *
 * Status codes:
 * - `201` — owner provisioned successfully.
 * - `403` — actor lacks `COMMERCE_EDIT_ALL`.
 * - `404` — lead not found.
 * - `500` — unexpected error during user creation.
 */
export const adminProvisionOwnerRoute = createAdminRoute({
    method: 'post',
    path: '/:id/provision-owner',
    summary: 'Provision a COMMERCE_OWNER account from a lead (admin)',
    description:
        'Creates a new COMMERCE_OWNER user account for the specified approved commerce lead ' +
        'and sends the temporary credentials to the owner by email. ' +
        'Requires COMMERCE_EDIT_ALL permission.',
    tags: ['Commerce'],
    requiredPermissions: [PermissionEnum.COMMERCE_EDIT_ALL],
    requestParams: {
        id: z.string().uuid({ message: 'Lead ID must be a valid UUID' })
    },
    responseSchema: ProvisionOwnerResponseSchema,
    handler: async (ctx, params) => {
        const actor = getActorFromContext(ctx);
        const leadId = params.id as string;

        // Fetch the lead — not exposed as a public service method, so we read
        // directly via the model (thin admin route, no new service method needed).
        const lead = await commerceLeadModel.findById(leadId);
        if (!lead) {
            throw new ServiceError(
                ServiceErrorCode.NOT_FOUND,
                `Commerce lead not found: ${leadId}`
            );
        }

        // Instantiate ports per-request so they capture the current request
        // headers (needed by Better Auth for origin / cookie context).
        const createUser = createCommerceOwnerCreateUserPort(ctx.req.raw.headers);
        const notifier = createCommerceOwnerCredentialsNotificationPort(env.HOSPEDA_SITE_URL);

        const provisioningService = new CommerceOwnerProvisioningService(
            { logger: apiLogger },
            createUser,
            notifier
        );

        // The DB model returns the raw select type, which lacks the audit
        // fields (`createdById`, `updatedById`) declared in CommerceLead schema
        // but absent from the actual table.  The provisioning service only uses
        // `id`, `email`, `contactName`, and `domain` — safe to cast.
        const result = await provisioningService.provisionCommerceOwner(actor, {
            lead: lead as unknown as CommerceLead
        });

        if (result.error) {
            throw new ServiceError(result.error.code, result.error.message);
        }

        // biome-ignore lint/style/noNonNullAssertion: result.data is defined when result.error is absent
        const { userId, email, name } = result.data!;

        // NEVER return temporaryPassword in the HTTP response.
        return { userId, email, name };
    }
});
