/**
 * Audit & Security Logs Feature Module (SPEC-162)
 *
 * Barrel exports for the admin audit/security log viewers. Both viewers are
 * generated by the createEntityListPage framework — see config/audit-logs.config.ts.
 */

// Types — canonical types from @repo/schemas (re-exported for convenience)
export type { AuditLogEntry, AuditLogSeverity, AuditLogType } from '@repo/schemas';

// Widget cell components (reused by the framework column config)
export { AuditMessageCell } from './components/AuditMessageCell';
export { AuditSeverityBadge } from './components/AuditSeverityBadge';

// Framework-generated page components + routes
export {
    auditLogsConfig,
    AuditLogsPageComponent,
    AuditLogsRoute,
    securityLogsConfig,
    SecurityLogsPageComponent,
    SecurityLogsRoute
} from './config/audit-logs.config';
