from pathlib import Path
import subprocess,re,json
D='.specs/HOS-1352-billing-verticals-redesign/docs';V='.specs/HOS-1353-verticales-capacidades-y-autorizacion';B='.specs/HOS-1354-billing-cobro-y-proveedor'
patterns=[r'carga.{0,60}3a|3a.{0,60}carga|no esta migración',r'mutación.{0,60}fecha efectiva|fecha efectiva.{0,60}muta|reintento.{0,80}fecha efectiva|S37',r'tres correos del aumento|B13a.{0,60}aumento|B12.{0,60}aviso',r'reintento.{0,30}alta nueva|S16|checkout ya',r'promo_redemption|instante del canje',r'BL por inferencia|rama que la lee|reconciliation_mark_payment',r'aviso.{0,60}encola|encola.{0,60}cobertura|B4.{0,60}outbox|aviso.{0,60}durable',r'misma transacción que encola|con el encolado del aviso|coberturaPerdidaEn',r'comprobante de la transferencia|referencia del panel|RF4',r'primera cuota|MP5|aviso de falta de pago',r'relectura por id del pago|releyendo el pago|RF3',r'pendiente de .S19|S6.{0,30}no ocurre|ocurre y corre .S5',r'deja en .DRAFT|a .DRAFT.{0,25}PB11|levantar la moderación',r'los tres avisos|tres avisos.{0,60}V9b|dos avisos previos',r'dos avisos previos y el de la alerta cerrada|fecha objetivo|alerta cerrada',r'rank.{0,25}MAYOR.{0,30}limit menor|limit menor|MEJOR_DECLARADO',r'dieciocho valores|dieciocho plazos|merge de .B11|diecinueve',r'V9a.{0,60}domain_event|domain_event.{0,60}V9a|BW',r'destino para su ciclo, sin promos|ventana gemela|sin promos',r'contracargo y no en la vista|contracargo.{0,60}defecto|contracargo.{0,60}listado',r'las doce siguen|doce dependencias|las doce del|las doce de',r'B/09.{0,10}§6|nueva acuñada|clave nueva',r'correo encolado antes de la cancelación|correo antes|VIP',r'smoke.{0,50}no como gate|ventanas del corte|BT',r'paso 5/6|sin fuente que otorgue la capacidad|paso 5|paso 6',r'lista de piezas, l. 953|lista de piezas, l. 950|§4.6 .l. 951|§4.6 .l. 952',r'promos y cortesías, en .B9a|addons, en .B4|le agrega a .payment',r'precisar nunca corrige|LETRAS_MUERTAS|LETRAS_VIVAS_REVISADAS',r'predicado.{0,60}B2|y su test.{0,30}B2|CC|CF',r'fuera de staging|producción.{0,60}aborta|guard de entorno|sólo staging|toda sonda']
results={}
for i,pat in enumerate(patterns,1):
 r=subprocess.run(['rg','--hidden','-n','-i','-g','*.md',pat,D,V,B],capture_output=True,text=True)
 assert r.returncode in (0,1),(i,r.stderr)
 results[f'R{i:02}']={'patron':pat,'exit':r.returncode,'hits':r.stdout.splitlines()}
Path('/tmp/hos1352-p10-fuentes-rg.json').write_text(json.dumps(results,ensure_ascii=False,indent=2)+'\n')
print('30 búsquedas múltiples; resultados completos /tmp/hos1352-p10-fuentes-rg.json')
