import { AmenityService } from '@repo/service-core';
import requiredManifest from '../manifest-required.json';
import { createSeedFactory } from '../utils/index.js';

/**
 * Seed factory for amenities
 *
 * Creates amenity records from JSON files, excluding the slug field
 * since it's auto-generated by the service lifecycle hooks.
 */
export const seedAmenities = createSeedFactory({
    entityName: 'Amenities',
    serviceClass: AmenityService,
    folder: 'src/data/amenity',
    files: requiredManifest.amenities,

    // Exclude metadata fields and slug field as it's auto-generated
    normalizer: (data) => {
        // First exclude metadata fields
        const { $schema, id, slug, ...cleanData } = data as {
            $schema?: string;
            id?: string;
            slug?: string;
            [key: string]: unknown;
        };

        return cleanData;
    },

    // Custom entity info for better logging
    getEntityInfo: (item, _context) => {
        const amenity = item as { name: string; type?: string };
        const typeInfo = amenity.type ? ` (${amenity.type})` : '';
        return `"${amenity.name}"${typeInfo}`;
    }
});
