import { AttractionModel } from '@repo/db';
import { AttractionService } from '@repo/service-core';
import requiredManifest from '../manifest-required.json';
import { createSeedFactory, STATUS_ICONS, whereFixtureFields } from '../utils/index.js';

/**
 * Seed factory for attractions
 *
 * Creates attraction records from JSON files, excluding the slug field
 * since it's auto-generated by the service lifecycle hooks.
 */
export const seedAttractions = createSeedFactory({
    entityName: 'Attractions',
    serviceClass: AttractionService,
    folder: 'src/data/attraction',
    files: requiredManifest.attractions,

    // HOS-735: re-runnable. Keyed by NAME, not slug: the normalizer below drops the fixture
    // slug on purpose so the service regenerates it, and the fixtures spell it with
    // underscores while the generated one uses hyphens (`aqua_parque_termal` ->
    // `aqua-parque-termal`). A slug lookup never matched, so a re-run did not fail: it
    // silently inserted the whole catalog again as `anfiteatro-2`, `anfiteatro-3`, ...
    existing: { modelClass: AttractionModel, getWhere: whereFixtureFields({ fields: ['name'] }) },

    // Exclude metadata fields and slug field as it's auto-generated
    normalizer: (data) => {
        // First exclude metadata fields and auto-generated fields
        const { $schema, id, slug, lifecycleState, tagIds, ...cleanData } = data as {
            $schema?: string;
            id?: string;
            slug?: string;
            lifecycleState?: string;
            tagIds?: unknown[];
            [key: string]: unknown;
        };

        return cleanData;
    },

    // Custom entity info for better logging
    getEntityInfo: (item, _context) => {
        const attraction = item as { name: string; isBuiltin?: boolean };
        const builtinIcon = attraction.isBuiltin ? ` ${STATUS_ICONS.BuiltIn}` : '';
        return `"${attraction.name}"${builtinIcon}`;
    }
});
