import { PointOfInterestService } from '@repo/service-core';
import requiredManifest from '../manifest-required.json';
import { createSeedFactory, STATUS_ICONS } from '../utils/index.js';
import type { SeedContext } from '../utils/seedContext.js';

/**
 * Normalizes a raw POI fixture item into `service.create()`-ready data.
 *
 * Strips the metadata/auto-generated fields (`$schema`, `id`,
 * `lifecycleState` — the latter defaults to `ACTIVE` via
 * `BaseLifecycleFields`, same as `attractions.seed.ts`). **Unlike**
 * `attractions.seed.ts`'s normalizer, `slug` is intentionally KEPT: POIs
 * carry no `name` column (HOS-113 OQ-2), so `slug` is a required, stable
 * identifier rather than a value auto-generated by a service `_beforeCreate`
 * hook. Display names come from each fixture's `nameI18n` (HOS-138 removed the
 * legacy `destinations.poiNames.<slug>` i18n keys).
 *
 * Exported (rather than an inline lambda) so tests can validate it against
 * every real fixture without running the full seed pipeline against a
 * database — mirrors the same testability pattern `destinations.seed.ts`
 * uses for `preProcessDestination` (HOS-25 T-025).
 *
 * @param data - Raw fixture item, as loaded from `src/data/pointOfInterest/*.json`
 * @returns The cleaned data payload, ready for `PointOfInterestCreateInputSchema`
 */
export const normalizePointOfInterestSeedItem = (
    data: Record<string, unknown>
): Record<string, unknown> => {
    const { $schema, id, lifecycleState, ...cleanData } = data as {
        $schema?: string;
        id?: string;
        lifecycleState?: string;
        [key: string]: unknown;
    };

    return cleanData;
};

/**
 * Formats a POI fixture item for seed-progress logging. Uses `slug` — there
 * is no `name` field to fall back on (HOS-113 OQ-2), unlike
 * `attractions.seed.ts`'s `getEntityInfo`.
 *
 * @param item - Raw fixture item
 * @param _context - Seed context (unused, matches `SeedFactoryConfig`'s signature)
 */
export const getPointOfInterestEntityInfo = (item: unknown, _context: SeedContext): string => {
    const poi = item as { slug: string; type?: string; isBuiltin?: boolean };
    const builtinIcon = poi.isBuiltin ? ` ${STATUS_ICONS.BuiltIn}` : '';
    return `"${poi.slug}" (${poi.type})${builtinIcon}`;
};

/**
 * Seed factory for points of interest (HOS-113 T-024).
 *
 * Creates POI records from JSON fixtures under `src/data/pointOfInterest/`,
 * mirroring `attractions.seed.ts`'s `createSeedFactory` shape. Write access
 * is seed-only in Phase 1 (HOS-113 NG-5/OQ-6 — no admin CRUD routes exist
 * yet), so this factory is the sole production path that creates POI rows.
 *
 * @example
 * ```typescript
 * await seedPointsOfInterest(seedContext);
 * // Creates POIs like:
 * // "autodromo_concepcion_del_uruguay" (STADIUM)
 * // "playa_banco_pelay" (BEACH)
 * ```
 */
export const seedPointsOfInterest = createSeedFactory({
    entityName: 'PointsOfInterest',
    serviceClass: PointOfInterestService,
    folder: 'src/data/pointOfInterest',
    files: requiredManifest.pointsOfInterest,
    normalizer: normalizePointOfInterestSeedItem,
    getEntityInfo: getPointOfInterestEntityInfo
});
