import { SponsorshipLevelService } from '@repo/service-core';
import requiredManifest from '../manifest-required.json';
import { createSeedFactory } from '../utils/index.js';

/**
 * Seed factory for sponsorship levels
 *
 * Creates sponsorship level records from JSON files, excluding the slug field
 * since it's auto-generated by the service lifecycle hooks.
 */
export const seedSponsorshipLevels = createSeedFactory({
    entityName: 'Sponsorship Levels',
    serviceClass: SponsorshipLevelService,
    folder: 'src/data/sponsorshipLevel',
    files: requiredManifest.sponsorshipLevels,

    // Exclude metadata fields only
    normalizer: (data) => {
        const { $schema, id, eventLevelId, ...cleanData } = data as {
            $schema?: string;
            id?: string;
            eventLevelId?: string;
            [key: string]: unknown;
        };

        return cleanData;
    },

    // Custom entity info for better logging
    getEntityInfo: (item, _context) => {
        const level = item as { name: string; tier?: string; targetType?: string };
        const tierInfo = level.tier ? ` (${level.tier})` : '';
        const targetInfo = level.targetType ? ` - ${level.targetType}` : '';
        return `"${level.name}"${tierInfo}${targetInfo}`;
    }
});
