import { SponsorshipPackageModel } from '@repo/db';
import { SponsorshipPackageService } from '@repo/service-core';
import requiredManifest from '../manifest-required.json';
import { STATUS_ICONS } from '../utils/icons.js';
import { createSeedFactory } from '../utils/index.js';
import { logger } from '../utils/logger.js';

/**
 * Seed factory for sponsorship packages
 *
 * Creates sponsorship package records from JSON files, excluding the slug field
 * since it's auto-generated by the service lifecycle hooks. Maps eventLevelId
 * from seed IDs to real database IDs using postProcess after creation.
 */
export const seedSponsorshipPackages = createSeedFactory({
    entityName: 'Sponsorship Packages',
    serviceClass: SponsorshipPackageService,
    folder: 'src/data/sponsorshipPackage',
    files: requiredManifest.sponsorshipPackages,

    // Exclude metadata fields and eventLevelId (will be set in postProcess)
    normalizer: (data) => {
        const { $schema, id, eventLevelId, ...cleanData } = data as {
            $schema?: string;
            id?: string;
            eventLevelId?: string;
            [key: string]: unknown;
        };

        return cleanData;
    },

    // Update eventLevelId after entity creation
    postProcess: async (result, item, context) => {
        const itemData = item as { eventLevelId?: string };
        const serviceResult = result as { data?: { id?: string } };

        // Only process if both eventLevelId in source data and created entity ID exist
        if (itemData.eventLevelId && serviceResult?.data?.id) {
            const seedEventLevelId = itemData.eventLevelId;
            const realEventLevelId = context.idMapper.getRealId(
                'sponsorship levels',
                seedEventLevelId
            );

            if (realEventLevelId) {
                try {
                    // Update the package with the real eventLevelId
                    const model = new SponsorshipPackageModel();
                    await model.update(
                        { id: serviceResult.data.id },
                        { eventLevelId: realEventLevelId }
                    );
                    logger.info(
                        `${STATUS_ICONS.Info}    Linked event level: ${context.idMapper.getDisplayName('sponsorship levels', seedEventLevelId)}`
                    );
                } catch (error) {
                    logger.warn(
                        `${STATUS_ICONS.Warning}    Failed to link event level: ${error instanceof Error ? error.message : String(error)}`
                    );
                }
            } else {
                logger.warn(
                    `${STATUS_ICONS.Warning}    Event level ID "${seedEventLevelId}" not found in mappings`
                );
            }
        }
    },

    // Custom entity info for better logging
    getEntityInfo: (item, _context) => {
        const pkg = item as { name: string; includedPosts?: number; includedEvents?: number };
        const postsInfo = pkg.includedPosts ? ` - ${pkg.includedPosts} posts` : '';
        const eventsInfo = pkg.includedEvents ? ` - ${pkg.includedEvents} events` : '';
        return `"${pkg.name}"${postsInfo}${eventsInfo}`;
    }
});
