/**
 * Features list page - using generic entity list system
 */
import { FeaturesPageComponent, FeaturesRoute } from '@/features/features/config/features.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [35f745a1-ba85-403c-90b2-907c4c6e5e00]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = FeaturesRoute;
export default FeaturesPageComponent;
