/**
 * Amenities list page - using generic entity list system
 */
import {
    AmenitiesPageComponent,
    AmenitiesRoute
} from '@/features/amenities/config/amenities.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [c421a6ad-c8c3-4133-8ebf-f1704366abb9]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = AmenitiesRoute;
export default AmenitiesPageComponent;
