/**
 * Destinations list page - refactored using generic entity list system
 */
import {
    DestinationsPageComponent,
    DestinationsRoute
} from '@/features/destinations/config/destinations.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [a916067e-a8f9-43d5-9e7d-fe89029679f1]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = DestinationsRoute;
export default DestinationsPageComponent;
