/**
 * @file ProviderQrPanel.client.tsx
 * @description The provider's "Mi QR" tab (HOS-376 T-050, §6.2a).
 *
 * The SVG is generated by our own API and handed in as markup, but it is
 * rendered through an `<img src="data:image/svg+xml,…">` rather than injected
 * into the DOM. Both would look identical; only one of them cannot execute
 * script. A browser disables scripting inside an SVG loaded as an image, so
 * this costs nothing and removes the question entirely — and the CSP already
 * allows `data:` under `img-src`.
 *
 * The download is the reason this is an island at all. A plain
 * `<a download href="{API}/mine/qr">` was the obvious alternative and does not
 * work: the API is a different origin, so the browser would send the request
 * without the session cookie and save a 401 to the provider's disk. Building
 * the file from the markup already on the page avoids the round trip.
 */

import { useCallback, useMemo, useState } from 'react';
import type { SupportedLocale } from '@/lib/i18n';
import { createTranslations } from '@/lib/i18n';
import styles from './ProviderPanels.module.css';

interface ProviderQrPanelProps {
    readonly locale: SupportedLocale;
    /** The QR as SVG markup, already rendered by the API. */
    readonly svg: string;
    /** The listing's slug, used to name the downloaded file. */
    readonly slug: string;
    /** The URL the code encodes, shown as text so it can be checked by eye. */
    readonly targetUrl: string;
}

/**
 * Renders the QR, its target URL, and a download button.
 *
 * @param props - Locale, the SVG markup, the slug and the encoded URL.
 * @returns The panel element.
 */
export function ProviderQrPanel({ locale, svg, slug, targetUrl }: ProviderQrPanelProps) {
    const { t } = createTranslations(locale);
    const [downloaded, setDownloaded] = useState(false);

    const dataUrl = useMemo(
        () => `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`,
        [svg]
    );

    // The anchor is created for the click and thrown away. A rendered one would
    // have to be hidden from assistive technology — and a hidden link with no
    // accessible content is exactly what it sounds like: not a link.
    const handleDownload = useCallback(() => {
        const anchor = document.createElement('a');
        anchor.href = dataUrl;
        anchor.download = `qr-${slug}.svg`;
        anchor.click();
        setDownloaded(true);
    }, [dataUrl, slug]);

    return (
        <div className={styles.panel}>
            <h3 className={styles.sectionTitle}>
                {t('host-trades.provider.qr.title', 'Tu código QR')}
            </h3>

            <p className={styles.rowBody}>
                {t(
                    'host-trades.provider.qr.help',
                    'Imprimilo o mostralo en el celular. El anfitrión lo escanea con la cámara y registra el uso él mismo: no hace falta que le pidas datos ni que lo cargues vos.'
                )}
            </p>

            <div className={styles.qrFrame}>
                <img
                    alt={t(
                        'host-trades.provider.qr.alt',
                        'Código QR que lleva a la página para registrar un uso de tu beneficio'
                    )}
                    className={styles.qrImage}
                    src={dataUrl}
                />
            </div>

            <p className={styles.rowMeta}>
                {t('host-trades.provider.qr.encodes', 'Lleva a: {{url}}', { url: targetUrl })}
            </p>

            <button
                className={styles.primaryAction}
                onClick={handleDownload}
                type="button"
            >
                {t('host-trades.provider.qr.download', 'Descargar el QR')}
            </button>

            {downloaded ? (
                <p
                    className={styles.success}
                    role="status"
                >
                    {t('host-trades.provider.qr.downloaded', 'Listo, lo descargamos como SVG.')}
                </p>
            ) : null}
        </div>
    );
}
