import { Section, Text } from '@react-email/components';
import { Button } from '../components/button.js';
import { Heading } from '../components/heading.js';
import { InfoRow } from '../components/info-row.js';
import { EmailLayout } from '../components/layout.js';

/**
 * Props for the CommerceOwnerCredentials email template (SPEC-239 T-050).
 */
export interface CommerceOwnerCredentialsProps {
    /** Display name of the provisioned commerce owner. */
    readonly recipientName: string;
    /** Temporary password generated by the provisioning service. */
    readonly temporaryPassword: string;
    /** Full URL to the change-password page (siteUrl + /mi-cuenta/cambiar-contrasena). */
    readonly changePasswordUrl: string;
}

/**
 * Email template sent to a newly provisioned COMMERCE_OWNER account.
 *
 * Displays the temporary password and a CTA button directing the owner to
 * the mandatory change-password page before they can use the platform.
 *
 * Security note: renders the temporaryPassword in plain text inside the
 * email body — this is intentional (one-time delivery, forced change on
 * first login).  The template itself does NOT store or log the password.
 *
 * @param props - Template data.
 */
export function CommerceOwnerCredentials({
    recipientName,
    temporaryPassword,
    changePasswordUrl
}: CommerceOwnerCredentialsProps) {
    return (
        <EmailLayout
            previewText="Tus credenciales de acceso a Hospeda — activá tu cuenta ahora"
            showUnsubscribe={false}
        >
            <Heading>¡Bienvenido a Hospeda!</Heading>

            <Text style={styles.greeting}>Hola {recipientName},</Text>

            <Text style={styles.paragraph}>
                Tu cuenta de propietario en <strong>Hospeda</strong> ha sido creada exitosamente. A
                continuación encontrás tus credenciales de acceso temporales.
            </Text>

            <Section style={styles.credentialsBox}>
                <InfoRow
                    label="Contraseña temporal"
                    value={temporaryPassword}
                />
            </Section>

            <Text style={styles.paragraph}>
                Por seguridad, <strong>debés cambiar tu contraseña</strong> antes de poder acceder
                al panel de control. Hacé clic en el botón de abajo para activar tu cuenta.
            </Text>

            <Section style={styles.buttonContainer}>
                <Button href={changePasswordUrl}>Activar mi cuenta</Button>
            </Section>

            <Text style={styles.securityNote}>
                Si no solicitaste esta cuenta o creés que fue un error, contactá a nuestro equipo de
                soporte respondiendo este email o escribiendo a soporte@hospeda.com.ar.
            </Text>
        </EmailLayout>
    );
}

const styles = {
    greeting: {
        color: '#1e293b',
        fontSize: '16px',
        lineHeight: '24px',
        margin: '0 0 16px'
    },
    paragraph: {
        color: '#475569',
        fontSize: '16px',
        lineHeight: '24px',
        margin: '0 0 16px'
    },
    credentialsBox: {
        backgroundColor: '#f0fdf4',
        borderRadius: '8px',
        borderLeft: '4px solid #22c55e',
        padding: '24px',
        margin: '24px 0'
    },
    buttonContainer: {
        margin: '32px 0',
        textAlign: 'center' as const
    },
    securityNote: {
        color: '#64748b',
        fontSize: '14px',
        lineHeight: '20px',
        margin: '24px 0 0',
        textAlign: 'center' as const
    }
};
