import { Section, Text } from '@react-email/components';
import { Button } from '../components/button.js';
import { Heading } from '../components/heading.js';
import { InfoRow } from '../components/info-row.js';
import { EmailLayout } from '../components/layout.js';

/**
 * Props for the CommerceOwnerCredentials email template (SPEC-239 T-050).
 */
export interface CommerceOwnerCredentialsProps {
    /** Display name of the provisioned commerce owner. */
    readonly recipientName: string;
    /** Temporary password generated by the provisioning service. */
    readonly temporaryPassword: string;
    /** Full URL to the change-password page (siteUrl + /mi-cuenta/cambiar-contrasena). */
    readonly changePasswordUrl: string;
}

/**
 * Email template sent to a newly provisioned COMMERCE_OWNER account
 * (HOS-166 PR-C §7.5 rework).
 *
 * Historically this ended at a single "Activar mi cuenta" CTA to the
 * change-password page. It now doubles as the "lead approved → complete and
 * publish" notification (see the HOS-166 PR-C report for why: it is sent at
 * exactly the lead-approved moment, through the already-live
 * `ProvisioningNotificationPort`, rather than reviving the dead
 * `LeadNotificationPort` — HOS-166 §7.5/R-8) — it walks the owner through
 * the FULL path: credentials → change password → complete your listing →
 * publish → pay.
 *
 * It deliberately links ONLY to the change-password page, never straight to
 * payment or even to `/mi-cuenta/comercio`: `mustChangePasswordGate()` 403s
 * EVERY protected route (including listing create/edit and checkout) until
 * the password changes (HOS-166 §5.4), so any link past that gate would
 * dead-end the very first click.
 *
 * Displays the temporary password and a CTA button directing the owner to
 * the mandatory change-password page before they can use the platform.
 *
 * Security note: renders the temporaryPassword in plain text inside the
 * email body — this is intentional (one-time delivery, forced change on
 * first login).  The template itself does NOT store or log the password.
 *
 * @param props - Template data.
 */
export function CommerceOwnerCredentials({
    recipientName,
    temporaryPassword,
    changePasswordUrl
}: CommerceOwnerCredentialsProps) {
    return (
        <EmailLayout
            previewText="Tus credenciales de acceso a Hospeda — activá tu cuenta y publicá tu comercio"
            showUnsubscribe={false}
        >
            <Heading>¡Bienvenido a Hospeda!</Heading>

            <Text style={styles.greeting}>Hola {recipientName},</Text>

            <Text style={styles.paragraph}>
                Tu cuenta de propietario en <strong>Hospeda</strong> ha sido creada exitosamente. A
                continuación encontrás tus credenciales de acceso temporales.
            </Text>

            <Section style={styles.credentialsBox}>
                <InfoRow
                    label="Contraseña temporal"
                    value={temporaryPassword}
                />
            </Section>

            <Text style={styles.paragraph}>
                Por seguridad, <strong>debés cambiar tu contraseña</strong> antes de poder acceder
                al panel de control. Hacé clic en el botón de abajo para activar tu cuenta.
            </Text>

            <Section style={styles.buttonContainer}>
                <Button href={changePasswordUrl}>Activar mi cuenta</Button>
            </Section>

            <Text style={styles.paragraph}>
                Una vez que cambies tu contraseña, estos son los próximos pasos para publicar tu
                comercio:
            </Text>

            <Section style={styles.stepsBox}>
                <Text style={styles.stepItem}>
                    1. Completá los datos de tu comercio (nombre, descripción, fotos, horarios y
                    contacto).
                </Text>
                <Text style={styles.stepItem}>
                    2. Cuando esté completo, vas a poder publicarlo desde tu cuenta.
                </Text>
                <Text style={styles.stepItem}>
                    3. Publicá y pagá la suscripción — recién ahí tu ficha se muestra al público.
                </Text>
            </Section>

            <Text style={styles.securityNote}>
                Si no solicitaste esta cuenta o creés que fue un error, contactá a nuestro equipo de
                soporte respondiendo este email o escribiendo a soporte@hospeda.com.ar.
            </Text>
        </EmailLayout>
    );
}

const styles = {
    greeting: {
        color: '#1e293b',
        fontSize: '16px',
        lineHeight: '24px',
        margin: '0 0 16px'
    },
    paragraph: {
        color: '#475569',
        fontSize: '16px',
        lineHeight: '24px',
        margin: '0 0 16px'
    },
    credentialsBox: {
        backgroundColor: '#f0fdf4',
        borderRadius: '8px',
        borderLeft: '4px solid #22c55e',
        padding: '24px',
        margin: '24px 0'
    },
    stepsBox: {
        backgroundColor: '#f8fafc',
        borderRadius: '8px',
        padding: '20px 24px',
        margin: '16px 0 24px'
    },
    stepItem: {
        color: '#334155',
        fontSize: '15px',
        lineHeight: '22px',
        margin: '0 0 8px'
    },
    buttonContainer: {
        margin: '32px 0',
        textAlign: 'center' as const
    },
    securityNote: {
        color: '#64748b',
        fontSize: '14px',
        lineHeight: '20px',
        margin: '24px 0 0',
        textAlign: 'center' as const
    }
};
