export enum BuiltinPermissionTypeEnum {
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_DELETE = 'USER_DELETE',

    DESTINATION_CREATE = 'DESTINATION_CREATE',
    DESTINATION_UPDATE = 'DESTINATION_UPDATE',
    DESTINATION_DELETE = 'DESTINATION_DELETE',

    ACCOMMODATION_CREATE = 'ACCOMMODATION_CREATE',
    ACCOMMODATION_UPDATE = 'ACCOMMODATION_UPDATE',
    ACCOMMODATION_DELETE = 'ACCOMMODATION_DELETE',

    EVENT_CREATE = 'EVENT_CREATE',
    EVENT_UPDATE = 'EVENT_UPDATE',
    EVENT_DELETE = 'EVENT_DELETE',

    POST_CREATE = 'POST_CREATE',
    POST_UPDATE = 'POST_UPDATE',
    POST_DELETE = 'POST_DELETE',

    TAG_CREATE = 'TAG_CREATE',
    TAG_UPDATE = 'TAG_UPDATE',
    TAG_DELETE = 'TAG_DELETE',

    USER_ROLE_CREATE = 'USER_ROLE_CREATE',
    USER_ROLE_UPDATE = 'USER_ROLE_UPDATE',
    USER_ROLE_DELETE = 'USER_ROLE_DELETE',

    USER_PERMISSION_CREATE = 'USER_PERMISSION_CREATE',
    USER_PERMISSION_UPDATE = 'USER_PERMISSION_UPDATE',
    USER_PERMISSION_DELETE = 'USER_PERMISSION_DELETE',

    POST_SPONSOR_CREATE = 'POST_SPONSOR_CREATE',
    POST_SPONSOR_UPDATE = 'POST_SPONSOR_UPDATE',
    POST_SPONSOR_DELETE = 'POST_SPONSOR_DELETE',

    AMENITY_CREATE = 'AMENITY_CREATE',
    AMENITY_UPDATE = 'AMENITY_UPDATE',
    AMENITY_DELETE = 'AMENITY_DELETE',

    FEATURE_CREATE = 'FEATURE_CREATE',
    FEATURE_UPDATE = 'FEATURE_UPDATE',
    FEATURE_DELETE = 'FEATURE_DELETE'
}
