/**
 * @file callback.ts
 *
 * Admin-only endpoint that completes the MercadoLibre OAuth authorization-code
 * flow (HOS-45 / SPEC-278 T-012). Validates the CSRF `state` echoed back by
 * MercadoLibre (generated by the paired `authorize` route, T-011), exchanges
 * the one-time `code` for an access/refresh token pair, and persists the
 * result via {@link upsertMLCredential}.
 *
 * @module routes/integrations/mercadolibre-oauth/callback
 */

import { PermissionEnum } from '@repo/schemas';
import { HTTPException } from 'hono/http-exception';
import { z } from 'zod';
import { upsertMLCredential } from '../../../services/mercadolibre-oauth/ml-credential.repository';
import { exchangeAuthorizationCode } from '../../../services/mercadolibre-oauth/ml-oauth-client';
import { env } from '../../../utils/env';
import { createAdminRoute } from '../../../utils/route-factory';
import { validateAndConsumeState } from './authorize';

/**
 * Response schema for a successful callback exchange.
 *
 * **SECURITY**: Deliberately excludes the access token, refresh token, and
 * any other secret — only a success flag, the provider name, and the new
 * expiry timestamp are ever returned to the caller.
 */
const CallbackResponseSchema = z.object({
    success: z.boolean(),
    provider: z.literal('mercadolibre'),
    expiresAt: z.string()
});

/**
 * GET /api/v1/admin/mercadolibre-oauth/callback
 *
 * Completes the MercadoLibre OAuth authorization-code flow:
 * 1. Validates and consumes the `state` param (one-time use CSRF token
 *    generated by the `authorize` route). Unknown/expired/already-consumed
 *    states are rejected with a 400 before any token exchange is attempted.
 * 2. Guards on `HOSPEDA_MERCADOLIBRE_REDIRECT_URI` being configured (same
 *    503 the `authorize` route uses for "not configured"), then exchanges
 *    the `code` for an access/refresh token pair.
 * 3. On success, persists the new credential via {@link upsertMLCredential}.
 *    On failure, the error propagates untouched — no partial credential is
 *    ever persisted.
 *
 * Requires {@link PermissionEnum.INTEGRATION_MERCADOLIBRE_MANAGE}.
 */
export const mercadoLibreCallbackRoute = createAdminRoute({
    method: 'get',
    path: '/callback',
    summary: 'Complete MercadoLibre OAuth flow',
    description:
        'Validates the OAuth state, exchanges the authorization code for tokens, and persists the resulting credential.',
    tags: ['Integrations'],
    requiredPermissions: [PermissionEnum.INTEGRATION_MERCADOLIBRE_MANAGE],
    requestQuery: {
        code: z.string().min(1),
        state: z.string().min(1)
    },
    responseSchema: CallbackResponseSchema,
    handler: async (_c, _params, _body, query) => {
        const state = query?.state as string;
        const code = query?.code as string;

        if (!validateAndConsumeState(state)) {
            throw new HTTPException(400, { message: 'Invalid or expired OAuth state' });
        }

        if (!env.HOSPEDA_MERCADOLIBRE_REDIRECT_URI) {
            throw new HTTPException(503, {
                message: 'MercadoLibre OAuth integration is not configured'
            });
        }

        const tokens = await exchangeAuthorizationCode({
            code,
            redirectUri: env.HOSPEDA_MERCADOLIBRE_REDIRECT_URI
        });

        const expiresAt = new Date(Date.now() + tokens.expiresIn * 1000);

        await upsertMLCredential({
            accessToken: tokens.accessToken,
            refreshToken: tokens.refreshToken,
            expiresAt
        });

        return {
            success: true,
            provider: 'mercadolibre' as const,
            expiresAt: expiresAt.toISOString()
        };
    }
});
