/**
 * Posts list page - using generic entity list system
 */
import { PostsPageComponent, PostsRoute } from '@/features/posts/config/posts.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [f8c8dd64-004f-4eb7-ada2-91743310fb2f]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = PostsRoute;
export default PostsPageComponent;
