import { useToast } from '@/components/ui/ToastProvider';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useTranslations } from '@/hooks/use-translations';
import { cn } from '@/lib/utils';
import { type Seo, SeoSchema } from '@repo/schemas';
import { useEffect, useMemo, useState } from 'react';
import {
    SEO_LIMITS,
    type SeoFormValues,
    buildSeoFormValues,
    buildSeoPayload,
    buildSeoPreviewDescription,
    buildSeoPreviewTitle,
    getSeoCounterTone,
    truncateSeoPreview
} from './seo-editor.utils';

interface SeoEditorErrors {
    title?: string;
    description?: string;
}

export interface SeoEditorProps {
    readonly seo: Seo | null | undefined;
    readonly fallbackTitle: string;
    readonly fallbackDescription: string;
    readonly previewUrl: string;
    readonly isSaving: boolean;
    readonly saveError?: string;
    readonly onSave: (seo: Seo | null) => Promise<unknown>;
}

export function SeoEditor({
    fallbackDescription,
    fallbackTitle,
    isSaving,
    onSave,
    previewUrl,
    saveError,
    seo
}: SeoEditorProps) {
    const { addToast } = useToast();
    const { t } = useTranslations();
    const [values, setValues] = useState<SeoFormValues>(() => buildSeoFormValues(seo));
    const [fieldErrors, setFieldErrors] = useState<SeoEditorErrors>({});

    useEffect(() => {
        setValues(buildSeoFormValues(seo));
        setFieldErrors({});
    }, [seo]);

    const previewTitle = useMemo(
        () =>
            buildSeoPreviewTitle({
                title: values.title,
                fallbackTitle
            }),
        [fallbackTitle, values.title]
    );
    const previewDescription = useMemo(
        () =>
            buildSeoPreviewDescription({
                description: values.description,
                fallbackDescription
            }),
        [fallbackDescription, values.description]
    );

    const isAutoTitle = values.title.trim().length === 0;
    const isAutoDescription = values.description.trim().length === 0;

    const handleValueChange = (field: keyof SeoFormValues, value: string) => {
        setValues((current) => ({ ...current, [field]: value }));

        if (fieldErrors[field]) {
            setFieldErrors((current) => ({ ...current, [field]: undefined }));
        }
    };

    const handleSave = async () => {
        const payload = buildSeoPayload(values);

        if (payload) {
            const parsed = SeoSchema.safeParse(payload);

            if (!parsed.success) {
                const nextErrors: SeoEditorErrors = {};

                for (const issue of parsed.error.issues) {
                    const path = issue.path[0];
                    if (path === 'title' || path === 'description') {
                        nextErrors[path] = t(issue.message as Parameters<typeof t>[0]);
                    }
                }

                setFieldErrors(nextErrors);
                return;
            }
        }

        try {
            await onSave(payload);
            addToast({
                title: t('error.form.save-success'),
                message: t('error.form.save-success-message'),
                variant: 'success'
            });
        } catch (error) {
            addToast({
                title: t('error.form.save-failed'),
                message: error instanceof Error ? error.message : t('error.form.unexpected-error'),
                variant: 'error'
            });
        }
    };

    return (
        <div className="space-y-6">
            <Card>
                <CardHeader>
                    <CardTitle className="text-base">
                        {t('admin-pages.seo.searchEnginePreview')}
                    </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                    <div className="space-y-1">
                        <div className="flex items-center gap-2">
                            <p
                                className="cursor-pointer text-lg text-primary hover:underline"
                                data-testid="seo-preview-title"
                            >
                                {truncateSeoPreview({
                                    text: previewTitle,
                                    maxLength: SEO_LIMITS.title.max + 10
                                })}
                            </p>
                            {isAutoTitle && (
                                <Badge variant="outline">
                                    {t('admin-pages.seo.autoGenerated')}
                                </Badge>
                            )}
                        </div>
                        <p className="text-green-700 text-sm dark:text-green-300">{previewUrl}</p>
                        <div className="flex items-start gap-2">
                            <p
                                className="text-muted-foreground text-sm"
                                data-testid="seo-preview-description"
                            >
                                {truncateSeoPreview({
                                    text: previewDescription,
                                    maxLength: SEO_LIMITS.description.max
                                })}
                            </p>
                            {isAutoDescription && (
                                <Badge variant="outline">
                                    {t('admin-pages.seo.autoGenerated')}
                                </Badge>
                            )}
                        </div>
                    </div>
                </CardContent>
            </Card>

            <Card>
                <CardContent className="space-y-5 pt-6">
                    <div className="space-y-2">
                        <div className="flex items-center justify-between gap-3">
                            <Label htmlFor="seo-title">{t('admin-pages.seo.metaTitle')}</Label>
                            <span
                                className={cn(
                                    'text-sm',
                                    getSeoCounterTone({
                                        length: values.title.length,
                                        min: SEO_LIMITS.title.min,
                                        max: SEO_LIMITS.title.max
                                    })
                                )}
                                data-testid="seo-title-counter"
                            >
                                {values.title.length} / {SEO_LIMITS.title.max}
                            </span>
                        </div>
                        <Input
                            id="seo-title"
                            value={values.title}
                            onChange={(event) => handleValueChange('title', event.target.value)}
                            placeholder={fallbackTitle}
                            disabled={isSaving}
                        />
                        <p className="text-muted-foreground text-xs">
                            {t('admin-pages.seo.metaTitleHint')}
                        </p>
                        {fieldErrors.title && (
                            <p className="text-destructive text-xs">{fieldErrors.title}</p>
                        )}
                    </div>

                    <div className="space-y-2">
                        <div className="flex items-center justify-between gap-3">
                            <Label htmlFor="seo-description">
                                {t('admin-pages.seo.metaDescription')}
                            </Label>
                            <span
                                className={cn(
                                    'text-sm',
                                    getSeoCounterTone({
                                        length: values.description.length,
                                        min: SEO_LIMITS.description.min,
                                        max: SEO_LIMITS.description.max
                                    })
                                )}
                                data-testid="seo-description-counter"
                            >
                                {values.description.length} / {SEO_LIMITS.description.max}
                            </span>
                        </div>
                        <Textarea
                            id="seo-description"
                            value={values.description}
                            onChange={(event) =>
                                handleValueChange('description', event.target.value)
                            }
                            placeholder={fallbackDescription}
                            disabled={isSaving}
                            rows={4}
                        />
                        <p className="text-muted-foreground text-xs">
                            {t('admin-pages.seo.metaDescriptionHint')}
                        </p>
                        {fieldErrors.description && (
                            <p className="text-destructive text-xs">{fieldErrors.description}</p>
                        )}
                    </div>

                    <div className="flex items-center justify-between gap-4">
                        <p className="text-muted-foreground text-sm">
                            {t('admin-pages.seo.emptyFieldFallbackNote')}
                        </p>
                        <Button
                            onClick={handleSave}
                            disabled={isSaving}
                        >
                            {isSaving ? t('admin-pages.seo.saving') : t('admin-pages.seo.save')}
                        </Button>
                    </div>

                    {saveError && <p className="text-destructive text-xs">{saveError}</p>}
                </CardContent>
            </Card>
        </div>
    );
}
