import { z } from 'zod';

// ============================================================================
// SHARED I18N TEXT SCHEMA
// Single source of truth for localized text fields across the platform.
// Supported locales: es (Spanish), en (English), pt (Portuguese).
// ============================================================================

/**
 * Input contract for the i18nText factory.
 * Callers set their own per-field string length bounds.
 */
export interface I18nTextOptions {
    /** Minimum string length applied to each locale field. */
    readonly min: number;
    /** Maximum string length applied to each locale field. */
    readonly max: number;
}

/**
 * Base localized-text schema with no length constraints.
 *
 * Use this type reference when you only need the shape (`{ es, en, pt }`)
 * without additional length validation — for example in DB-layer `$type<>`
 * annotations or when writing generic helpers that accept any I18nText.
 *
 * For validated input schemas prefer the `i18nText({ min, max })` factory.
 *
 * @example
 * // DB column type annotation
 * name: jsonb('name').$type<I18nText>().notNull()
 *
 * @example
 * // Zod schema usage
 * const schema = z.object({ label: I18nTextSchema });
 */
export const I18nTextSchema = z.object({
    /** Spanish locale text. */
    es: z.string(),
    /** English locale text. */
    en: z.string(),
    /** Portuguese locale text. */
    pt: z.string()
});

/**
 * TypeScript type inferred from {@link I18nTextSchema}.
 * Represents a required localized-text value with all three locales.
 */
export type I18nText = z.infer<typeof I18nTextSchema>;

/**
 * Localized-text schema for content that is only guaranteed to exist in
 * Spanish. `es` is required; `en`/`pt` are nullable — for datasets whose
 * source content is Spanish-only and where auto-translating the other
 * locales is an explicit, separate follow-up (never invented at import
 * time) rather than a same-step requirement.
 *
 * This is a NARROW, entity-scoped variant — do NOT use it as a drop-in
 * replacement for {@link I18nTextSchema} across the platform. It exists
 * because some entities (e.g. the HOS-142 POI catalog import) ingest
 * bulk, Spanish-sourced content where requiring `en`/`pt` up front would
 * either invent translations or block the import entirely; most entities
 * should keep using {@link I18nTextSchema} / {@link i18nText}, which
 * assume all three locales are always populated.
 *
 * @example
 * // Entity schema field — name that may lack en/pt translations
 * nameI18n: PartialI18nTextSchema.nullish()
 */
export const PartialI18nTextSchema = z.object({
    /** Spanish locale text — always required. */
    es: z.string(),
    /** English locale text — null when not yet translated. */
    en: z.string().nullish(),
    /** Portuguese locale text — null when not yet translated. */
    pt: z.string().nullish()
});

/**
 * TypeScript type inferred from {@link PartialI18nTextSchema}.
 * Represents a localized-text value where only `es` is guaranteed present.
 */
export type PartialI18nText = z.infer<typeof PartialI18nTextSchema>;

/**
 * Factory that returns a localized-text Zod schema with per-field string
 * length bounds applied to every locale (`es`, `en`, `pt`).
 *
 * This is the preferred way to define i18n text fields in entity schemas,
 * because it lets each entity declare the appropriate length constraints
 * without duplicating the `z.object({ es, en, pt })` boilerplate.
 *
 * @param options - RO-RO input with `min` and `max` string lengths.
 * @returns A Zod object schema `{ es: z.string().min(min).max(max), ... }`
 *
 * @example
 * // Entity schema field — required localized name
 * name: i18nText({ min: 2, max: 100 })
 *
 * @example
 * // Entity schema field — nullable localized description
 * description: i18nText({ min: 10, max: 500 }).nullish()
 */
export const i18nText = ({ min, max }: I18nTextOptions) =>
    z.object({
        /** Spanish locale text. */
        es: z.string().min(min).max(max),
        /** English locale text. */
        en: z.string().min(min).max(max),
        /** Portuguese locale text. */
        pt: z.string().min(min).max(max)
    });

// ---------------------------------------------------------------------------
// Translation metadata (SPEC-212)
// ---------------------------------------------------------------------------

/**
 * Per-field, per-locale translation metadata stored alongside I18nText columns.
 * Tracks whether a translation was auto-generated by AI or manually overridden.
 */
export interface TranslationMeta {
    [field: string]: {
        [locale: string]: {
            /** Whether this translation was auto-generated by AI (false = manual override). */
            autoTranslated: boolean;
            /** ISO timestamp of when the translation was created/updated. */
            translatedAt: string;
            /** AI provider used for auto-translation (e.g. 'google', 'openai'). */
            provider?: string;
            /** AI model used for auto-translation (e.g. 'gemini-1.5-flash'). */
            model?: string;
        };
    };
}

/**
 * Zod schema for translation metadata.
 * Loose (passthrough) — the shape is well-defined but we allow extension.
 */
export const TranslationMetaSchema = z.record(
    z.string(),
    z.record(
        z.string(),
        z.object({
            autoTranslated: z.boolean(),
            translatedAt: z.string(),
            provider: z.string().optional(),
            model: z.string().optional()
        })
    )
);
