import { SponsorsPageComponent, SponsorsRoute } from '@/features/sponsors/config/sponsors.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [e4e35754-f4fe-4141-aee4-b433b47e13fc]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = SponsorsRoute;
export default SponsorsPageComponent;
