/**
 * Accommodation Import Schemas (SPEC-222)
 *
 * Defines the foundational types for the "import accommodation from URL"
 * feature. These schemas describe where scraped/extracted data came from
 * (the import source platform) and how confident each extracted field value
 * is and by which extraction method it was obtained.
 *
 * Also defines the API request and response contracts for the
 * `POST /api/v1/protected/accommodations/import-from-url` endpoint.
 *
 * All downstream import services and API routes depend on these contracts.
 */
import { z } from 'zod';

import { AccommodationTypeEnumSchema } from '../../enums/index.js';
import { LanguageEnumSchema } from '../user/user.settings.schema.js';

// ---------------------------------------------------------------------------
// ImportSourceSchema
// ---------------------------------------------------------------------------

/**
 * Zod enum of the external platforms an accommodation can be imported from.
 *
 * - `mercadolibre` — Mercado Libre real-estate listings
 * - `google`        — Google Maps / Google Business listings
 * - `booking`       — Booking.com property pages
 * - `airbnb`        — Airbnb listing pages
 * - `generic`       — Any other URL (generic HTML scraping)
 * - `none`          — No external source; data was entered manually
 *
 * @example
 * ```ts
 * ImportSourceSchema.parse('airbnb');   // ok
 * ImportSourceSchema.parse('unknown');  // throws
 * ```
 */
export const ImportSourceSchema = z.enum([
    'mercadolibre',
    'google',
    'booking',
    'airbnb',
    'generic',
    'none'
]);

/**
 * TypeScript type inferred from {@link ImportSourceSchema}.
 *
 * @example
 * ```ts
 * const src: ImportSource = 'booking';
 * ```
 */
export type ImportSource = z.infer<typeof ImportSourceSchema>;

// ---------------------------------------------------------------------------
// FieldSourceSchema
// ---------------------------------------------------------------------------

/**
 * Zod enum describing the extraction method used to obtain a single field value.
 *
 * - `official_api` — Retrieved from an official platform API endpoint
 * - `jsonld`       — Parsed from a JSON-LD `<script type="application/ld+json">` block
 * - `opengraph`    — Parsed from Open Graph `<meta property="og:*">` tags
 * - `meta`         — Parsed from other `<meta>` tags (description, keywords, etc.)
 * - `text`         — Extracted by heuristic text / DOM parsing
 * - `ai`           — Inferred or generated by an AI model
 *
 * @example
 * ```ts
 * FieldSourceSchema.parse('jsonld');   // ok
 * FieldSourceSchema.parse('scrape');   // throws
 * ```
 */
export const FieldSourceSchema = z.enum([
    'official_api',
    'jsonld',
    'opengraph',
    'meta',
    'text',
    'ai'
]);

/**
 * TypeScript type inferred from {@link FieldSourceSchema}.
 *
 * @example
 * ```ts
 * const method: FieldSource = 'ai';
 * ```
 */
export type FieldSource = z.infer<typeof FieldSourceSchema>;

// ---------------------------------------------------------------------------
// importedField helper
// ---------------------------------------------------------------------------

/**
 * Factory that wraps any Zod value schema into a standardised "imported field"
 * object schema carrying:
 * - `value`      — The extracted value, typed by `valueSchema`.
 * - `confidence` — Extraction confidence score in the range [0, 100].
 * - `source`     — Which extraction method produced this value (see {@link FieldSourceSchema}).
 *
 * Use this for every field an importer writes so that callers always know how
 * reliable each piece of data is and where it originated.
 *
 * @param valueSchema - A Zod schema that describes the shape of the extracted value.
 * @returns A `z.ZodObject` wrapping `value`, `confidence`, and `source`.
 *
 * @example
 * ```ts
 * const NameFieldSchema = importedField(z.string());
 * NameFieldSchema.parse({ value: 'Hotel Sol', confidence: 90, source: 'jsonld' }); // ok
 *
 * const PriceFieldSchema = importedField(z.number().positive());
 * PriceFieldSchema.parse({ value: 150, confidence: 75, source: 'ai' }); // ok
 * ```
 */
export const importedField = <T extends z.ZodTypeAny>(valueSchema: T) =>
    z.object({
        value: valueSchema,
        confidence: z.number().min(0).max(100),
        source: FieldSourceSchema
    });

/**
 * Generic TypeScript type for an imported field holding a value of type `T`.
 *
 * This mirrors the runtime shape produced by {@link importedField} but is
 * convenient for type annotations without referencing the Zod schema directly.
 *
 * @example
 * ```ts
 * const nameField: ImportedField<string> = {
 *   value: 'Hotel Sol',
 *   confidence: 90,
 *   source: 'jsonld',
 * };
 * ```
 */
export type ImportedField<T> = {
    value: T;
    confidence: number;
    source: FieldSource;
};

// ---------------------------------------------------------------------------
// AccommodationImportDraftSchema
// ---------------------------------------------------------------------------

/**
 * Partial draft populated during a URL import pass.
 *
 * Every field is **optional** and wrapped in an {@link importedField} envelope
 * so the host knows where each value came from and how confident the extractor
 * was before deciding to keep, edit, or discard it.
 *
 * The draft intentionally mirrors only the accommodation fields that a URL
 * import can plausibly pre-fill. Fields requiring host knowledge or business
 * logic (check-in/out times, house-rules, etc.) are excluded entirely.
 *
 * Unknown top-level keys are stripped on parse (Zod default `.strip()`
 * behaviour). Nothing is required — an empty object `{}` is a valid draft.
 *
 * @example
 * ```ts
 * const draft: AccommodationImportDraft = AccommodationImportDraftSchema.parse({
 *   name: { value: 'Cabaña del Río', confidence: 92, source: 'jsonld' },
 *   type: { value: 'CABIN', confidence: 80, source: 'text' },
 *   price: {
 *     price: { value: 5000, confidence: 70, source: 'text' },
 *     currency: { value: 'ARS', confidence: 70, source: 'text' },
 *   },
 * });
 * ```
 */
export const AccommodationImportDraftSchema = z.object({
    /** Human-readable name of the accommodation (1–100 chars). */
    name: importedField(z.string().min(1).max(100)).optional(),

    /** Short summary visible in listing cards (1–300 chars). */
    summary: importedField(z.string().min(1).max(300)).optional(),

    /**
     * Long-form description. No minimum enforced in the draft — this is a
     * pre-fill; the host adds/edits detail before the final save.
     */
    description: importedField(z.string()).optional(),

    /** Accommodation category (one of the 13 {@link AccommodationTypeEnum} values). */
    type: importedField(AccommodationTypeEnumSchema).optional(),

    /**
     * Numeric capacity and room-count details.
     * Only the four fields a scraper can reasonably detect are included.
     */
    extraInfo: z
        .object({
            /** Maximum number of guests. */
            capacity: importedField(z.number().int().nonnegative()).optional(),
            /** Number of bedrooms. */
            bedrooms: importedField(z.number().int().nonnegative()).optional(),
            /** Total number of beds. */
            beds: importedField(z.number().int().nonnegative()).optional(),
            /** Number of bathrooms. */
            bathrooms: importedField(z.number().int().nonnegative()).optional()
        })
        .optional(),

    /**
     * Geographic location data.
     * Coordinates use string lat/long to match the project's CoordinatesSchema.
     */
    location: z
        .object({
            /** WGS-84 coordinates as string pairs (mirrors CoordinatesSchema). */
            coordinates: importedField(
                z.object({
                    lat: z.string(),
                    long: z.string()
                })
            ).optional(),
            /** Street name. */
            street: importedField(z.string()).optional(),
            /** Street number or identifier. */
            number: importedField(z.string()).optional()
        })
        .optional(),

    /** Pricing information extracted from the listing. */
    price: z
        .object({
            /** Numeric price (non-negative). */
            price: importedField(z.number().nonnegative()).optional(),
            /** ISO 4217 currency code or local label. */
            currency: importedField(z.string()).optional()
        })
        .optional(),

    /** Contact details found on the listing page. */
    contactInfo: z
        .object({
            /** Mobile / WhatsApp number. */
            mobilePhone: importedField(z.string()).optional(),
            /** Official website URL. */
            website: importedField(z.string()).optional()
        })
        .optional(),

    /** SEO metadata extracted from the page head. */
    seo: z
        .object({
            /** Page title (`<title>` or `og:title`). */
            title: importedField(z.string()).optional(),
            /** Meta description. */
            description: importedField(z.string()).optional()
        })
        .optional()
});

/**
 * TypeScript type inferred from {@link AccommodationImportDraftSchema}.
 *
 * Each field carries an {@link ImportedField} envelope with `value`,
 * `confidence`, and `source`. All top-level keys and all nested imported-field
 * keys are optional because the draft may only partially cover an accommodation.
 *
 * @example
 * ```ts
 * const draft: AccommodationImportDraft = {
 *   name: { value: 'Cabaña del Río', confidence: 92, source: 'jsonld' },
 * };
 * ```
 */
export type AccommodationImportDraft = z.infer<typeof AccommodationImportDraftSchema>;

// ---------------------------------------------------------------------------
// AccommodationImportRequestSchema
// ---------------------------------------------------------------------------

/**
 * Zod schema for the JSON body of
 * `POST /api/v1/protected/accommodations/import-from-url`.
 *
 * Validation rules:
 * - `url` must be a valid URL (Zod's RFC-3986 check) capped at 2 048 characters
 *   to prevent oversized inputs reaching the scraper layer.
 * - `locale` is optional. When absent the route handler defaults to `'es'`
 *   (the Argentine market default). Reuses {@link LanguageEnumSchema}
 *   (`'es' | 'en' | 'pt'`) — the platform-wide single source of truth for
 *   supported locales, never re-declared here.
 * - `legalConfirmed` must be **exactly** `true`. Sending `false` or omitting
 *   the field is rejected at the schema level. The server re-checks this flag
 *   to ensure the host has explicitly acknowledged the legal notice before
 *   any scraping occurs.
 *
 * @example
 * ```ts
 * AccommodationImportRequestSchema.parse({
 *   url: 'https://airbnb.com/rooms/123',
 *   locale: 'es',
 *   legalConfirmed: true,
 * }); // ok
 *
 * AccommodationImportRequestSchema.parse({
 *   url: 'https://airbnb.com/rooms/123',
 *   legalConfirmed: false,
 * }); // throws — legalConfirmed must be exactly true
 * ```
 */
export const AccommodationImportRequestSchema = z.object({
    /**
     * The public URL of the accommodation listing to import.
     * Must be a syntactically valid URL, max 2 048 characters.
     */
    url: z.string().url().max(2048),
    /**
     * Target locale for AI-assisted extraction and text normalisation.
     * Defaults to `'es'` when absent.
     */
    locale: LanguageEnumSchema.optional(),
    /**
     * Explicit host acknowledgement of the legal notice.
     * Must be `true` — any other value (including `false` or absence) is
     * rejected so the server never silently proceeds without consent.
     */
    legalConfirmed: z.literal(true)
});

/**
 * TypeScript type inferred from {@link AccommodationImportRequestSchema}.
 *
 * @example
 * ```ts
 * const req: AccommodationImportRequest = {
 *   url: 'https://booking.com/hotel/ar/sol.html',
 *   legalConfirmed: true,
 * };
 * ```
 */
export type AccommodationImportRequest = z.infer<typeof AccommodationImportRequestSchema>;

// ---------------------------------------------------------------------------
// AccommodationImportResponseSchema
// ---------------------------------------------------------------------------

/**
 * Zod schema for the JSON body returned by
 * `POST /api/v1/protected/accommodations/import-from-url`.
 *
 * The response is designed to be consumed by the host's import review UI:
 * the host sees the draft, can inspect which methods were used, and decides
 * which fields to keep, edit, or discard before creating the accommodation.
 *
 * Fields:
 * - `draft`               — Partially populated accommodation data. May be an
 *                           empty object `{}` when extraction yielded nothing
 *                           (graceful-degradation).
 * - `source`              — Which platform was detected for the URL. `'none'`
 *                           is accepted as a graceful-degradation marker when
 *                           detection failed.
 * - `methodsUsed`         — Array of {@link FieldSource} values identifying
 *                           every extraction method that contributed at least
 *                           one field to the draft. Empty when `draft` is `{}`.
 * - `partial`             — `true` when some fields could not be extracted and
 *                           the host should fill them manually.
 * - `message`             — Optional human-readable note (e.g. extraction
 *                           warning, fallback notice).
 * - `destinationHint`     — Optional locality resolution hint. `scrapedLocality`
 *                           is the raw locality string found on the page;
 *                           `candidates` are matched destination records
 *                           (UUID + name) for the host to pick from.
 * - `unresolvedAmenities` — Amenity strings found on the page that could not
 *                           be mapped to a known amenity slug.
 * - `mediaHints`          — Image URLs collected during scraping that the host
 *                           can optionally import.
 *
 * @example
 * ```ts
 * const res: AccommodationImportResponse = {
 *   draft: { name: { value: 'Hotel Sol', confidence: 90, source: 'jsonld' } },
 *   source: 'booking',
 *   methodsUsed: ['jsonld', 'opengraph'],
 *   partial: false,
 * };
 * ```
 */
export const AccommodationImportResponseSchema = z.object({
    /**
     * Partial draft of the accommodation data extracted from the URL.
     * An empty object `{}` is valid when extraction yielded no usable fields.
     */
    draft: AccommodationImportDraftSchema,
    /**
     * Detected import source platform for the submitted URL.
     * `'none'` is accepted as a graceful-degradation marker when detection
     * failed or when the source is genuinely unknown.
     */
    source: ImportSourceSchema,
    /**
     * All extraction methods that contributed at least one field value to
     * the draft. Empty array when `draft` is empty.
     */
    methodsUsed: z.array(FieldSourceSchema),
    /**
     * Whether the draft is incomplete and requires manual host input to fill
     * the missing required accommodation fields before publishing.
     */
    partial: z.boolean(),
    /**
     * Optional human-readable message from the importer (e.g. a warning
     * about rate-limiting, a fallback notice, or a quality advisory).
     */
    message: z.string().optional(),
    /**
     * Optional locality resolution hint to help the host map the scraped
     * address to a Hospeda destination record.
     */
    destinationHint: z
        .object({
            /** Raw locality string as scraped from the listing page. */
            scrapedLocality: z.string().optional(),
            /**
             * Destination records that match the scraped locality.
             * Each candidate carries the destination UUID and display name.
             */
            candidates: z.array(
                z.object({
                    /** UUID of the candidate destination record. */
                    id: z.string().uuid(),
                    /** Human-readable destination name. */
                    name: z.string()
                })
            )
        })
        .optional(),
    /**
     * Amenity strings found on the page that could not be resolved to a
     * known amenity slug. The host can manually map or ignore these.
     */
    unresolvedAmenities: z.array(z.string()).optional(),
    /**
     * Image URLs collected during scraping. The host decides which (if any)
     * to import into the accommodation's media gallery.
     */
    mediaHints: z
        .object({
            /** List of absolute image URLs found on the listing page. */
            imageUrls: z.array(z.string())
        })
        .optional()
});

/**
 * TypeScript type inferred from {@link AccommodationImportResponseSchema}.
 *
 * @example
 * ```ts
 * const res: AccommodationImportResponse = {
 *   draft: {},
 *   source: 'generic',
 *   methodsUsed: [],
 *   partial: true,
 *   message: 'Could not extract any structured data from the page.',
 * };
 * ```
 */
export type AccommodationImportResponse = z.infer<typeof AccommodationImportResponseSchema>;
