"""Writes omisiones.json next to it: per pin, the verbatim spans gen01.py replaces by «[…]»."""
import json
import os
O = {
 "DEC-CONC-002#📌1": [("Once filas de\n`B/03`", "[…] Filas de\n`B/03`")],
 "DEC-CONC-002#📌3": [(" —que desde\nentonces cuenta las dos lápidas, la del corte y la de recepción—", " […]")],
 "DEC-ADDON-002#📌2": [("`S26` la\naplica a los `USER`/`GLOBAL` compatibles con la vertical que discontinúa. ", "[…] "),
                        ("una de las\ncatorce transiciones", "una de las\n[…] transiciones")],
 "DEC-MIG-002#📌1": [(": una regla de Cloudflare cierra las rutas que crean o re-autorizan algo en el\nproveedor.", ": […].")],
 "DEC-MIG-003#📌1": [(" si el despliegue falla: el costo, aceptado, es que los\nclientes cancelados se re-suscriben sin trial, y **qué se hace con esa diferencia no está\ndecidido**.", " si el despliegue falla […].")],
 "DEC-MIG-003#📌2": [("escribe sigue siendo: las lápidas (paso 4), los dos", "escribe sigue siendo: […] los dos")],
 "DEC-MIG-003#📌3": [("- La rama de aborto devuelve la URL de notificación a la ruta del viejo y la verifica con\n  una entrega real.\n", "- […]\n"),
                      ("- El borrado del contenido de las `L1` pasa al paso 5b, después de abrir altas, porque el\n  backup no restaura fotos ni tokens.\n", "- […]\n"),
                      ("- El apuntado de la URL es el paso 4b, después de las lápidas. El paso 3", "- […] El paso 3"),
                      ("- El recuento de fichas de Gastronomía y de Experiencia se hace antes del 1a, y el corte no\n  arranca si da una fila; el gate del paso 2 lo repite como segundo control, y si ahí da una\n  fila el corte entra en la rama de aborto (`V/21` §2.4).\n", "- […]\n"),
                      ("- El paso 4c, después del 4b y fuera de la rama, revalida las páginas públicas de las fichas\n  que nacieron despublicadas.", "- […]")],
 "DEC-MIG-003#📌5": [("; el borde la cierra antes de apagar el\ncontenedor viejo en el paso 3 y la abre al final del paso 4, con las lápidas verificadas;\nmientras está cerrada, el proveedor recibe error y reintenta a la misma URL.", "; […]."),
                      ("vuelve\na cerrar la ruta si hace falta, redespliega", "[…] redespliega")],
 "DEC-DATA-002#📌1": [("**tiene seis hechos**", "**tiene […] hechos**")],
 "DEC-TEST-001#📌1": [("el total de 31 guards no\ncambia", "el total de […] guards no\ncambia")],
 "DEC-RF-008#📌1": [("**quince**\nacciones", "**[…]**\nacciones"), ("dicen quince.", "dicen […].")],
 "DEC-ADDON-004#📌1": [("`S11` o por `S26`—", "`S11` […]—")],
 "DEC-ARCH-006#📌8": [(", las filas vivas sin\n`CANCEL_SCHEDULED`,", ", […],"), ("y siguen siendo once.", "y […].")],
 "DEC-ARCH-006#📌9": [("siguen en once.", "siguen en […].")],
 "DEC-SUB-013#📌1": [("`S24`, `S26`)", "`S24`, […])"), ("`S21`, `S28`)", "`S21`, […])")],
 "DEC-TEST-001#📌2": [("pasa a 32 guards", "pasa a […] guards")],
 "DEC-TEST-001#📌3": [("queda en 33 guards", "queda en […] guards")],
 "DEC-TEST-001#📌4": [("sigue en 33\nguards", "sigue en […]\nguards")],
 "DEC-TEST-001#📌5": [("pasa de 33 a **34 guards distintos**", "pasa de 33 a **[…] guards distintos**"), ("; queda para el owner.", "; […].")],
 "DEC-TEST-001#📌6": [("**18 de verticales, 15\nde billing y 1 de `U1`**", "**[…]**")],
 "DEC-RF-004#📌1": [("`S12`-vía-`S26` ya no depende de transportar la causa:\n`S21` la lee en la fecha de fin en la fila de `vertical_discontinuation` de la vertical de la\nprincipal, y abre el 15. ", "[…] "),
                     (" La lectura es por la vertical y no\npor la fila, así que también alcanza a la baja que la persona pidió antes del anuncio y termina\ndespués.", " […]")],
 "DEC-RF-006#📌2": [("el `USER`/`GLOBAL` que `S26`\ncanceló y todo complemento cuya principal mató `S12` sobre una vertical con fila en\n`vertical_discontinuation`.", "[…].")],
 "DEC-MP-008#📌2": [("una pausa o una cancelación hecha por el pagador", "[…] una cancelación hecha por el pagador")],
 "DEC-SUB-021#📌1": [("1. **La frase *«los reintentos del proveedor cobran con ella»* queda CONDICIONADA a `GR-1`**, como\n   `DEC-SUB-010` lo está a su segunda lectura. El *Contexto medido* no la mide: `EX-36` mide que la\n   tarjeta **se puede** cambiar, no que el reintento de un cobro ya abierto use la nueva; y `GR-3`", "1. […] `GR-3`"),
                     (" **Se mide con el próximo rechazo mensual real.** Mientras tanto, **la\n   pantalla y los correos del grace no prometen que el reintento use la tarjeta nueva**. La\n   decisión no cambia; cambia lo que se le promete al cliente.", " […]")],
 "DEC-MIG-005#📌5": [(" El titular que sólo conoce el proveedor tiene detector sólo si alguna lectura medida en\nsandbox trae su pagador (`EX-59`); si ninguna, queda declarado sin detector.", " […]")],
 "DEC-RF-008#📌3": [("de dieciséis a veintiuna vivas", "de dieciséis a […] vivas")],
 "DEC-RF-008#📌4": [("de veintiuna a veintitrés vivas", "de […] a […] vivas"), ("las dos las construye `V8`", "las dos las construye […]")],
 "DEC-ENT-006#📌1": [(", que se asigna al aprobar la postulación,", ", […],")],
 "DEC-ENT-006#📌2": [(" o\nel alta directa del admin con dueño.", "\n[…]."), ("; `starts_at` y `ends_at` quedan hasta la unidad de socios (H; ver el\n📌 de `DEC-ARCH-014`)", "; […] (H; ver el\n📌 de `DEC-ARCH-014`)")],
 "DEC-ENT-006#📌3": [("**los borra `V7` con su migración, junto con sus lectores del panel**", "**los borra […], junto con sus lectores del panel**")],
 "DEC-ENT-006#📌4": [("sale en la misma migración de `V7` que `starts_at` y `ends_at`", "sale en […] que `starts_at` y `ends_at`")],
 "DEC-MIG-006#📌2": [("la escribe\ndespués el script del corte, con la función", "la escribe\n[…], con la función")],
 "DEC-ARCH-013#📌1": [("se congelan con\nsus valores adentro, en el mismo cambio que lo borra, y salen en el paso 6 del corte.", "[…]."), ("antes del ensayo del\ncorte en staging.", "[…].")],
 "DEC-ARCH-013#📌3": [("los escribe\ndespués el script del corte, con la función", "los escribe\n[…], con la función")],
 "DEC-ARCH-013#📌4": [("**Ese\ncontrol cuenta como guard: los guards pasan de 33 a 34**", "**Ese\ncontrol cuenta como guard: […]**")],
 "DEC-ARCH-014#📌1": [("El\nprograma pasa a 23 unidades y el reparto de guards a 17 de verticales, 15 de billing y 1 de `U1`,\n33 en total. `U1` no es de ninguna épica, así que las dependencias entre épicas siguen en once.", "[…] `U1` no es de ninguna épica […]."),
                       ("; el\nborde la cierra desde que se apaga el contenedor viejo hasta que las lápidas del paso 4 están\nverificadas, el proveedor recibe error y reintenta a la misma URL, y el 4b sólo verifica", "; […] el 4b sólo verifica"),
                       (" Qué código\ncontesta el borde cerrado, para que el proveedor reintente, y qué pasa con lo que se pierda si el\ncierre pasa la escalera de reintentos quedaron para el owner\n(`30-revision-del-owner/35-aplicacion-lote-o.md` §3).", " […]")],
 "DEC-ARCH-014#📌2": [(" **P-A**: la ruta de avisos\nno la cierra una regla de bloqueo, que contesta un `4xx` sin reintento medido, sino un Worker del\nborde que contesta `500`, el único código con reintento medido (`WH-4`), con una cabecera propia\nque lo distingue de un `500` de la aplicación; se prende antes de apagar el contenedor viejo, se\napaga al final del paso 4, vive con el script del corte y lo deja listo el ensayo del paso 0\n(`DEC-MIG-003`). **P-B**: lo que se pierda durante el cierre lo lista el detector del día\nsiguiente al corte, sin abrir marca ni asentar (`DEC-MIG-005`).", " […]"),
                       ("Las dependencias entre épicas siguen en once y los guards en 33, con el\nmismo reparto: `G14` sigue en `V1`.", "[…] `G14` sigue en `V1`.")],
 "DEC-ARCH-014#📌5": [("; `starts_at` y `ends_at` quedan hasta la unidad de socios (H; ver el\n📌 de `DEC-ENT-006`)", "; […] (H; ver el\n📌 de `DEC-ENT-006`)"), ("33, pasan a **34**:", "33, pasan a **[…]**:")],
 "DEC-DATA-008#📌1": [("los fija el owner antes del ensayo del corte en staging, y", "los fija el owner […], y")],
 "DEC-DATA-008#📌3": [("con los quince valores,", "con los […] valores,"), ("los cinco sin valor escrito\nantes del ensayo del corte en `staging`.", "los cinco sin valor escrito\n[…].")],
 "DEC-DATA-008#📌4": [("los sigue fijando el owner antes\ndel ensayo del corte en `staging`.", "los sigue fijando el owner […].")],
 "DEC-ARCH-017#📌1": [("\naddons, `B4`, que le agrega a `payment` la columna de la instancia—", "\n[…]—")],
}
# indent=4 plus a final newline is exactly what the pre-commit's biome format leaves
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'omisiones.json'), 'w', encoding='utf-8') as fh:
    json.dump({k: [{"de": a, "a": b} for a, b in v] for k, v in O.items()}, fh, ensure_ascii=False, indent=4)
    fh.write('\n')
print(len(O))
