import { SeoEditor } from '@/components/seo/SeoEditor';
import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';

const addToast = vi.fn();

vi.mock('@/components/ui/ToastProvider', () => ({
    useToast: () => ({ addToast })
}));

vi.mock('@/hooks/use-translations', () => ({
    useTranslations: () => ({
        t: (key: string) => {
            const translations: Record<string, string> = {
                'admin-pages.seo.searchEnginePreview': 'Google preview',
                'admin-pages.seo.autoGenerated': 'Auto',
                'admin-pages.seo.metaTitle': 'Meta title',
                'admin-pages.seo.metaTitleHint': 'Title hint',
                'admin-pages.seo.metaDescription': 'Meta description',
                'admin-pages.seo.metaDescriptionHint': 'Description hint',
                'admin-pages.seo.emptyFieldFallbackNote': 'Fallback note',
                'admin-pages.seo.save': 'Save changes',
                'admin-pages.seo.saving': 'Saving...',
                'error.form.save-success': 'Saved',
                'error.form.save-success-message': 'Saved message',
                'error.form.save-failed': 'Save failed',
                'error.form.unexpected-error': 'Unexpected error',
                'zodError.common.seo.title.min': 'Title is too short',
                'zodError.common.seo.description.min': 'Description is too short'
            };

            return translations[key] ?? key;
        }
    })
}));

describe('SeoEditor', () => {
    it('renders auto-generated preview values when fields are empty', () => {
        render(
            <SeoEditor
                seo={null}
                fallbackTitle="Casa del Rio"
                fallbackDescription="Casa amplia frente al río con cochera y parrilla."
                previewUrl="https://hospeda.com.ar/es/alojamientos/casa-del-rio/"
                isSaving={false}
                onSave={vi.fn()}
            />
        );

        expect(screen.getByTestId('seo-preview-title')).toHaveTextContent('Casa del Rio | Hospeda');
        expect(screen.getByTestId('seo-preview-description')).toHaveTextContent(
            'Casa amplia frente al río con cochera y parrilla.'
        );
        expect(screen.getAllByText('Auto')).toHaveLength(2);
    });

    it('updates preview and counters when the user types overrides', () => {
        const titleOverride = 'Alojamiento boutique frente al río';
        const descriptionOverride =
            'Descripción más larga para mejorar el CTR en resultados de búsqueda.';

        render(
            <SeoEditor
                seo={null}
                fallbackTitle="Casa del Rio"
                fallbackDescription="Resumen original"
                previewUrl="https://hospeda.com.ar/es/alojamientos/casa-del-rio/"
                isSaving={false}
                onSave={vi.fn()}
            />
        );

        fireEvent.change(screen.getByLabelText('Meta title'), {
            target: { value: titleOverride }
        });
        fireEvent.change(screen.getByLabelText('Meta description'), {
            target: { value: descriptionOverride }
        });

        expect(screen.getByTestId('seo-preview-title')).toHaveTextContent(
            'Alojamiento boutique frente al río | Hospeda'
        );
        expect(screen.getByTestId('seo-title-counter')).toHaveTextContent(
            `${titleOverride.length} / 60`
        );
        expect(screen.getByTestId('seo-description-counter')).toHaveTextContent(
            `${descriptionOverride.length} / 155`
        );
    });

    it('does not save invalid overrides and surfaces translated validation text', async () => {
        const onSave = vi.fn();

        render(
            <SeoEditor
                seo={null}
                fallbackTitle="Casa del Rio"
                fallbackDescription="Resumen original"
                previewUrl="https://hospeda.com.ar/es/alojamientos/casa-del-rio/"
                isSaving={false}
                onSave={onSave}
            />
        );

        fireEvent.change(screen.getByLabelText('Meta title'), {
            target: { value: 'Muy corto' }
        });
        fireEvent.click(screen.getByRole('button', { name: 'Save changes' }));

        expect(onSave).not.toHaveBeenCalled();
        expect(screen.getByText('Title is too short')).toBeInTheDocument();
    });

    it('sends null when both fields are blank', async () => {
        const onSave = vi.fn().mockResolvedValue(undefined);

        render(
            <SeoEditor
                seo={{
                    title: 'Título ya guardado',
                    description:
                        'Descripción suficientemente larga para pasar la validación al iniciar la edición.'
                }}
                fallbackTitle="Casa del Rio"
                fallbackDescription="Resumen original"
                previewUrl="https://hospeda.com.ar/es/alojamientos/casa-del-rio/"
                isSaving={false}
                onSave={onSave}
            />
        );

        fireEvent.change(screen.getByLabelText('Meta title'), {
            target: { value: '   ' }
        });
        fireEvent.change(screen.getByLabelText('Meta description'), {
            target: { value: '   ' }
        });
        fireEvent.click(screen.getByRole('button', { name: 'Save changes' }));

        expect(onSave).toHaveBeenCalledWith(null);
    });
});
