/**
 * Users list page - using generic entity list system
 */
import { UsersPageComponent, UsersRoute } from '@/features/users/config/users.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [e8984a56-6dd2-43ab-bfa3-fd3a52d5c02b]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = UsersRoute;
export default UsersPageComponent;
