import { relations } from 'drizzle-orm';
import { index, pgTable, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';
import { users } from '../user/user.dbschema.ts';
import { aiMessages } from './ai_messages.dbschema.ts';

/**
 * AI conversations table (SPEC-173 T-007).
 *
 * Generic multi-turn conversation container for AI chat interactions.
 * A conversation groups a sequence of `ai_messages` belonging to a single
 * authenticated user session (child spec C — accommodation chat for tourists).
 *
 * This table is intentionally generic: child specs may add FK columns
 * (e.g. `accommodationId` for the chat child) via additive migrations without
 * altering the foundation schema.
 *
 * All AI requires an authenticated user (§5.7), so `userId` is always
 * non-null for valid conversations.
 *
 * Note: this table is distinct from the platform `conversations` table
 * (`packages/db/src/schemas/conversation/conversations.dbschema.ts`), which is
 * for host↔guest messaging. The `ai_` prefix avoids ambiguity.
 */
export const aiConversations = pgTable(
    'ai_conversations',
    {
        id: uuid('id').primaryKey().defaultRandom(),

        /**
         * FK → users.id. The authenticated user who owns this conversation.
         * ON DELETE CASCADE: removing a user removes their AI conversation history.
         */
        userId: uuid('user_id')
            .notNull()
            .references(() => users.id, { onDelete: 'cascade' }),

        /**
         * Optional human-readable title for the conversation.
         * May be set by the user or auto-generated by the engine from the first
         * message. NULL means untitled.
         */
        title: varchar('title', { length: 255 }),

        /**
         * AI feature context for this conversation (e.g. `chat`, `support`).
         * Allows the engine and admin tooling to filter conversations by feature.
         * Values: `text_improve` | `chat` | `search` | `support`
         */
        feature: varchar('feature', { length: 50 }),

        // ---- Timestamps ----
        createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
        updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),

        // ---- Soft delete ----
        deletedAt: timestamp('deleted_at', { withTimezone: true }),
        deletedById: uuid('deleted_by_id').references(() => users.id, { onDelete: 'set null' }),

        /**
         * Optional extra context stored with the conversation.
         * Child specs may store e.g. `{ accommodationId }` here without a
         * migration, until a dedicated FK column is justified.
         */
        contextNote: text('context_note')
    },
    (table) => ({
        /**
         * User inbox query: list all AI conversations for a given user
         * in reverse-chronological order.
         */
        aiConversations_userId_created_idx: index('aiConversations_userId_created_idx').on(
            table.userId,
            table.createdAt.desc()
        )
    })
);

/** Drizzle relations for `ai_conversations`. */
export const aiConversationsRelations = relations(aiConversations, ({ one, many }) => ({
    user: one(users, {
        fields: [aiConversations.userId],
        references: [users.id]
    }),
    deletedBy: one(users, {
        fields: [aiConversations.deletedById],
        references: [users.id]
    }),
    messages: many(aiMessages)
}));

/** Type inference helpers. */
export type InsertAiConversation = typeof aiConversations.$inferInsert;
export type SelectAiConversation = typeof aiConversations.$inferSelect;
