import { relations } from 'drizzle-orm';
import { index, integer, pgTable, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';
import { users } from '../user/user.dbschema.ts';

/**
 * AI usage metering table (SPEC-173 T-006).
 *
 * Records every AI call for usage metering, cost reporting, per-plan quota
 * enforcement, and cost-ceiling tracking (§5.7, §5.8, FR-7, AC-7).
 *
 * Every call is recorded regardless of tier — this is the authoritative source
 * for per-user / per-feature / per-month reporting.
 *
 * **Money convention**: `costEstimateMicroUsd` is stored as an integer number
 * of micro-USD (millionths of a US dollar; 1 USD = 1,000,000 µUSD). USD native,
 * no FX conversion — never float/numeric.
 *
 * The `feature` and `provider` columns store AI identifiers as varchar,
 * matching `AiFeature` and `AiProviderId` from `@repo/schemas`. See the
 * comment in `ai_prompt_versions.dbschema.ts` for the pgEnum rationale.
 *
 * The `status` column uses varchar for the call outcome:
 *   `success` | `error` | `fallback` | `quota_exceeded` | `ceiling_hit` | `kill_switch`
 *
 * Decision (owner-approved 2026-06-04): varchar chosen for AI enums (consistent
 * with repo — pgEnum is reserved for TS enums in @repo/schemas; AI values are
 * z.enum). Migrating to pgEnum is a future option if these are ever promoted to
 * TS enums.
 *
 * **APPEND-ONLY metering table** (owner-approved 2026-06-04): rows are immutable
 * records — no soft-delete (`deletedAt`/`deletedById`), no `updatedAt`. This
 * matches the pattern of `cron_runs`, `app_log`, and `ai_credential_audit`.
 * A deleted user's usage rows survive (anonymised) via `userId` nullable +
 * `ON DELETE SET NULL`.
 */
export const aiUsage = pgTable(
    'ai_usage',
    {
        id: uuid('id').primaryKey().defaultRandom(),

        /**
         * FK → users.id. The authenticated user who triggered the AI call.
         * Nullable: a deleted user's metering rows are preserved (anonymised)
         * via ON DELETE SET NULL (append-only — rows must not be lost).
         */
        userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),

        /**
         * AI feature that was invoked.
         * Values: `text_improve` | `chat` | `search` | `support`
         */
        feature: varchar('feature', { length: 50 }).notNull(),

        /**
         * Provider that served the call (or attempted to before fallback).
         * Values: `openai` | `anthropic` | `stub`
         */
        provider: varchar('provider', { length: 50 }).notNull(),

        /**
         * Model identifier as returned by the provider adapter.
         * E.g. `gpt-4o`, `claude-3-5-sonnet-20241022`. Stored verbatim
         * for cost attribution and reporting.
         */
        model: varchar('model', { length: 100 }).notNull(),

        /** Number of input (prompt) tokens consumed by this call. */
        tokensIn: integer('tokens_in').notNull(),

        /** Number of output (completion) tokens generated by this call. */
        tokensOut: integer('tokens_out').notNull(),

        /**
         * Estimated cost of this call in integer micro-USD
         * (millionths of a US dollar; 1 USD = 1,000,000 µUSD).
         * Computed by the cost calculator from token counts × provider rates.
         * USD native, no FX conversion. NEVER float or numeric.
         */
        costEstimateMicroUsd: integer('cost_estimate_micro_usd').notNull(),

        /** End-to-end latency of the AI call in milliseconds. */
        latencyMs: integer('latency_ms').notNull(),

        /**
         * Call outcome.
         * Values: `success` | `error` | `fallback` | `quota_exceeded` |
         *         `ceiling_hit` | `kill_switch`
         */
        status: varchar('status', { length: 30 }).notNull(),

        // ---- Timestamp (creation only — APPEND-ONLY, no updatedAt, no deletedAt) ----
        createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
    },
    (table) => ({
        /**
         * Primary reporting index: per-user, per-feature monthly usage.
         * Covers: monthly quota enforcement + admin usage reports.
         */
        aiUsage_userId_feature_created_idx: index('aiUsage_userId_feature_created_idx').on(
            table.userId,
            table.feature,
            table.createdAt.desc()
        ),

        /**
         * Cost ceiling tracking: global / per-feature accumulated spend.
         * Covers: cost ceiling checks (§5.8) + per-provider cost reports.
         */
        aiUsage_provider_feature_created_idx: index('aiUsage_provider_feature_created_idx').on(
            table.provider,
            table.feature,
            table.createdAt.desc()
        )
    })
);

/** Drizzle relations for `ai_usage`. */
export const aiUsageRelations = relations(aiUsage, ({ one }) => ({
    user: one(users, {
        fields: [aiUsage.userId],
        references: [users.id]
    })
}));

/** Type inference helpers. */
export type InsertAiUsage = typeof aiUsage.$inferInsert;
export type SelectAiUsage = typeof aiUsage.$inferSelect;
