/** TEST:B13a:23 — live route manifest for AC:B13a:24 (HOS-1638). */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { beforeAll, describe, expect, it } from 'vitest';
import { initApp } from '../../src/app';
import { validateApiEnv } from '../../src/utils/env';

const manifestFile = resolve(import.meta.dirname, '../../route-manifest.json');
const note =
    'Generated by apps/api/test/route-manifest/route-manifest.test.ts. Regenerate with UPDATE_ROUTE_MANIFEST=1. HOS-1638.';
// Hono registers middleware as ALL. No ALL handler prefix survived inspection;
// Better Auth's /api/auth/* handler registers GET and POST, not ALL.
const HANDLER_ALL_PREFIXES: readonly string[] = [];
const HANDLER_WILDCARD_PREFIXES: readonly string[] = ['/api/auth/*'];

type Route = { readonly method: string; readonly path: string };
let routes: Route[];

beforeAll(() => {
    validateApiEnv();
    const app = initApp();
    routes = [
        ...new Map(
            app.routes
                .filter(
                    (route) => route.method !== 'ALL' || HANDLER_ALL_PREFIXES.includes(route.path)
                )
                .map(({ method, path }) => [`${method} ${path}`, { method, path }])
        ).values()
    ].sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
});

describe('TEST:B13a:23 — registered API routes (AC:B13a:24)', () => {
    it('keeps a generated manifest in sync with initApp()', () => {
        const expected = `${JSON.stringify({ note, routes }, null, 2)}\n`;
        if (process.env.UPDATE_ROUTE_MANIFEST === '1') {
            writeFileSync(manifestFile, expected);
            execFileSync('pnpm', ['exec', 'biome', 'format', '--write', manifestFile]);
        } else {
            const previousManifest = JSON.parse(readFileSync(manifestFile, 'utf8')) as {
                note: string;
                routes: Route[];
            };
            if (JSON.stringify(previousManifest) !== JSON.stringify({ note, routes })) {
                const previous = previousManifest.routes;
                const currentKeys = new Set(routes.map((route) => `${route.method} ${route.path}`));
                const previousKeys = new Set(
                    previous.map((route) => `${route.method} ${route.path}`)
                );
                const changed = [
                    ...routes
                        .filter((route) => !previousKeys.has(`${route.method} ${route.path}`))
                        .map((route) => `+ ${route.method} ${route.path}`),
                    ...previous
                        .filter((route) => !currentKeys.has(`${route.method} ${route.path}`))
                        .map((route) => `- ${route.method} ${route.path}`)
                ].slice(0, 10);
                throw new Error(
                    `Route manifest differs from initApp(). Regenerate with UPDATE_ROUTE_MANIFEST=1 CI=true pnpm --filter hospeda-api exec vitest run test/route-manifest/route-manifest.test.ts\n${changed.join('\n')}`
                );
            }
        }
        expect(routes.length).toBeGreaterThan(100);
        expect(
            routes.filter(
                (route) =>
                    route.path.endsWith('/*') && !HANDLER_WILDCARD_PREFIXES.includes(route.path)
            )
        ).toEqual([]);
        expect(routes).toContainEqual({
            method: 'GET',
            path: '/api/v1/admin/users/:id/effective-set'
        });
        expect(
            routes.some((route) => route.path === '/api/v1/protected/users/me/entitlements')
        ).toBe(false);
    });
});
