#!/usr/bin/env tsx

/**
 * Script to generate TypeScript types from translation JSON files
 *
 * This script reads all translation files and generates a union type
 * of all possible translation keys for type safety.
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const LOCALES_DIR = resolve(import.meta.dirname, '../src/locales');
const OUTPUT_FILE = resolve(import.meta.dirname, '../src/types.ts');

/**
 * Filename → runtime namespace overrides.
 *
 * The generator derives each namespace from the locale JSON filename
 * (e.g. `home.json` → `home`). For MOST files the filename equals the runtime
 * namespace registered in `config.shared.ts` / `config.admin.ts`. Two files are
 * the exception: their runtime namespace is the PLURAL form while the file is
 * named in the singular (`destination.json` → `destinations`, `event.json` →
 * `events`). Without this remap the generated `TranslationKey` union would emit
 * `destination.*` / `event.*` keys that never resolve at runtime (the loader
 * registers `destinations` / `events`), giving false autocomplete safety for
 * those namespaces (HOS-127).
 *
 * Keep this in sync with the namespace keys in `config.shared.ts`
 * (`rawWebTranslations`), which are the single source of truth for the runtime
 * namespace of each file.
 */
export const FILENAME_NAMESPACE_OVERRIDES: Readonly<Record<string, string>> = {
    destination: 'destinations',
    event: 'events'
};

/**
 * Resolve the runtime namespace for a locale JSON file's base name.
 *
 * @param fileBaseName - The JSON filename without its `.json` extension
 *   (e.g. `destination`, `home`, `admin-billing`).
 * @returns The runtime namespace prefix used to build translation keys — the
 *   override when one exists, otherwise the base name unchanged.
 */
export function resolveNamespace(fileBaseName: string): string {
    return FILENAME_NAMESPACE_OVERRIDES[fileBaseName] ?? fileBaseName;
}

/**
 * Recursively extracts all keys from a nested object
 * @param obj - The object to extract keys from
 * @param prefix - The prefix for nested keys
 * @returns Array of dot-notation keys
 */
function extractKeys(obj: Record<string, unknown>, prefix = ''): string[] {
    const keys: string[] = [];

    for (const key in obj) {
        const fullKey = prefix ? `${prefix}.${key}` : key;

        if (typeof obj[key] === 'object' && obj[key] !== null && !Array.isArray(obj[key])) {
            keys.push(...extractKeys(obj[key] as Record<string, unknown>, fullKey));
        } else {
            keys.push(fullKey);
        }
    }

    return keys;
}

/**
 * Main function to generate types
 */
function generateTypes(): void {
    console.log('🔄 Generating translation types...');

    const allKeys = new Set<string>();

    try {
        // Read all locale directories
        const locales = readdirSync(LOCALES_DIR, { withFileTypes: true })
            .filter((dirent) => dirent.isDirectory())
            .map((dirent) => dirent.name);

        console.log(`📁 Found locales: ${locales.join(', ')}`);

        // Process each locale
        for (const locale of locales) {
            const localeDir = join(LOCALES_DIR, locale);
            const files = readdirSync(localeDir).filter((file) => file.endsWith('.json'));

            console.log(`📄 Processing ${files.length} files for locale '${locale}'`);

            // Process each translation file
            for (const file of files) {
                const filePath = join(localeDir, file);
                const namespace = resolveNamespace(file.replace('.json', ''));

                try {
                    const content = readFileSync(filePath, 'utf-8');
                    const translations = JSON.parse(content);

                    // Extract keys and add namespace prefix
                    const keys = extractKeys(translations);
                    for (const key of keys) {
                        allKeys.add(`${namespace}.${key}`);
                    }
                } catch (error) {
                    console.error(`❌ Error processing file ${filePath}:`, error);
                }
            }
        }

        // Generate TypeScript type definition
        const sortedKeys = Array.from(allKeys).sort();
        const typeDefinition = `/**
 * Auto-generated translation keys
 *
 * This file is automatically generated from translation JSON files.
 * Do not edit manually - run 'pnpm generate-types' to regenerate.
 *
 * NOTE: This file is git-ignored. It is generated on install (root 'prepare'
 * script) and before any typecheck/build via the Turbo '@repo/i18n#build'
 * task, so it should never be committed. The locale JSON files under
 * src/locales are the single source of truth.
 *
 * Total keys: ${sortedKeys.length}
 */

export type TranslationKey =
${sortedKeys.map((key) => `    | '${key}'`).join('\n')};

/**
 * @deprecated Use TranslationKey instead
 */
export type TranslationKeys = TranslationKey;
`;

        // Write the generated types
        writeFileSync(OUTPUT_FILE, typeDefinition, 'utf-8');

        console.log(`✅ Generated ${sortedKeys.length} translation keys`);
        console.log(`📝 Types written to: ${OUTPUT_FILE}`);
    } catch (error) {
        console.error('❌ Error generating types:', error);
        process.exit(1);
    }
}

// Run the script only when invoked directly (e.g. `tsx scripts/generate-types.ts`),
// NOT when the module is imported by a test to exercise `resolveNamespace`.
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
    generateTypes();
}
