/**
 * @file BrochureDownloadButton.client.tsx
 * @description Downloads the printable PDF ficha of a commerce listing
 * (HOS-1058).
 *
 * ## Why this is an island and not an `<a download href="{API}/…">`
 *
 * Because that was tried, on this exact shape, and it does not work. The API is
 * a different origin, so a plain anchor travels WITHOUT the session cookie and
 * the browser saves a 401 to the owner's disk — measured in HOS-376 and written
 * down in `ProviderQrPanel.client.tsx`. The fetch below carries
 * `credentials: 'include'`, the same way every other protected browser call in
 * this app does, and hands the bytes to the user through an object URL.
 *
 * That still satisfies HOS-1058's constraint. What the issue forbids is a PDF
 * ASSEMBLED in the page: the file here is generated by a server route and
 * arrives complete. The anchor is only the local hand-off of bytes the browser
 * already holds.
 *
 * ## The 403 is a real state, not an error
 *
 * The sheet is a premium capability, and the listing summary the owner index
 * renders carries no entitlement information — so the button renders for every
 * published listing and the API is the one that decides. A refusal is shown as
 * the upsell sentence it is, never as "something went wrong".
 */

import type { JSX } from 'react';
import { useState } from 'react';
import { getApiUrl } from '@/lib/env';
import type { SupportedLocale } from '@/lib/i18n';
import { createTranslations } from '@/lib/i18n';
import styles from './CommerceListingActions.module.css';

/** API path segment per vertical (mirrors the protected route mounts). */
const API_SEGMENT_BY_VERTICAL = {
    gastronomy: 'gastronomies',
    experience: 'experiences'
} as const;

export interface BrochureDownloadButtonProps {
    /** Which commerce vertical the listing belongs to. */
    readonly vertical: keyof typeof API_SEGMENT_BY_VERTICAL;
    /** The listing's id. */
    readonly listingId: string;
    /** The listing's slug, used as the fallback download filename. */
    readonly slug: string;
    /** Active locale — decides the language the SHEET is printed in. */
    readonly locale: SupportedLocale;
}

/** What the button is doing right now. */
type DownloadState = 'idle' | 'working' | 'locked' | 'error';

/**
 * Reads the filename the server chose, falling back to the listing slug.
 *
 * The header is `attachment; filename="ficha-x.pdf"`. A missing or unparsable
 * one is not worth failing over — the file is already in hand.
 */
function filenameFrom(input: { disposition: string | null; slug: string }): string {
    const match = /filename="([^"]+)"/.exec(input.disposition ?? '');
    return match?.[1] ?? `ficha-${input.slug}.pdf`;
}

/**
 * Renders the "download PDF sheet" action for one published listing.
 */
export function BrochureDownloadButton({
    vertical,
    listingId,
    slug,
    locale
}: BrochureDownloadButtonProps): JSX.Element {
    const { t } = createTranslations(locale);
    const [state, setState] = useState<DownloadState>('idle');

    async function handleDownload(): Promise<void> {
        if (state === 'working') {
            return;
        }
        setState('working');

        try {
            const url = `${getApiUrl()}/api/v1/protected/${API_SEGMENT_BY_VERTICAL[vertical]}/${listingId}/brochure`;
            const response = await fetch(url, {
                credentials: 'include',
                // The API resolves the sheet's language from this header, the
                // same signal the checkout return URLs use — so a sheet asked
                // for from an /en/ page prints in English.
                headers: { 'X-Client-Locale': locale }
            });

            if (response.status === 403) {
                setState('locked');
                return;
            }
            if (!response.ok) {
                setState('error');
                return;
            }

            const blob = await response.blob();
            const objectUrl = URL.createObjectURL(blob);
            const anchor = document.createElement('a');
            anchor.href = objectUrl;
            anchor.download = filenameFrom({
                disposition: response.headers.get('content-disposition'),
                slug
            });
            document.body.appendChild(anchor);
            anchor.click();
            anchor.remove();
            // Freed on the next tick rather than immediately: revoking before
            // the browser has started the save aborts it in Safari.
            setTimeout(() => URL.revokeObjectURL(objectUrl), 0);
            setState('idle');
        } catch {
            setState('error');
        }
    }

    return (
        <>
            <button
                type="button"
                className={styles.link}
                disabled={state === 'working'}
                aria-busy={state === 'working'}
                onClick={() => {
                    void handleDownload();
                }}
                data-testid="commerce-brochure-download"
            >
                {state === 'working'
                    ? t('commerce.brochure.downloading', 'Generando la ficha…')
                    : t('commerce.brochure.download', 'Descargar ficha en PDF')}
            </button>

            {state === 'locked' && (
                <p className={styles.hint}>
                    {t(
                        'commerce.brochure.locked',
                        'La ficha en PDF está disponible en el plan Premium de tu rubro.'
                    )}
                </p>
            )}

            {state === 'error' && (
                <p
                    className={styles.error}
                    role="alert"
                >
                    {t(
                        'commerce.brochure.error',
                        'No pudimos generar la ficha. Probá de nuevo en un momento.'
                    )}
                </p>
            )}
        </>
    );
}
