/**
 * AI text-improvement streaming route (SPEC-198).
 *
 * Mounted at `POST /api/v1/protected/ai/text-improve` by
 * `apps/api/src/routes/ai/protected/index.ts` (the protected AI barrel —
 * T-004 in the spec). Streams an SSE response of incremental text
 * suggestions generated by the `text_improve` AI feature for a HOST
 * accommodation field (`description` or `summary`).
 *
 * ## Middleware order (CRITICAL — wrong order = 503 on every request)
 *
 * `createProtectedStreamingRoute` PREPENDS `protectedAuthMiddleware` to
 * whatever we pass in `options.middlewares`, so the final chain is:
 *
 *   auth → entitlement → rateLimit-perUser → rateLimit-perIP → quota
 *
 * `entitlementMiddleware` MUST run before `createAiQuotaMiddleware` —
 * the quota middleware reads `c.get('userEntitlements')` which is
 * populated by `entitlementMiddleware`. Reordering causes 503 on every
 * request (the quota middleware's billing-load guard trips first).
 *
 * ## Per-request service
 *
 * `createConfiguredAiService()` is called once per request (no module
 * singleton) per SPEC-173 §T-043 owner decision — guarantees a rotated
 * provider credential is picked up immediately with no stale-credential
 * window.
 *
 * ## Prompt
 *
 * The system prompt is resolved internally by the engine from
 * `DEFAULT_PROMPTS['text_improve']` (already production-quality, owner-
 * approved as-shipped). The route only sends the user turn.
 *
 * @module apps/api/routes/ai/protected/text-improve
 */

import { AiTextImproveRequestSchema } from '@repo/schemas';
import type { AiFeature, AiTextImprove, AiTextImproveFieldType, LanguageEnum } from '@repo/schemas';
import { createAiQuotaMiddleware } from '../../../middlewares/ai-quota';
import { createAiRateLimitMiddlewares } from '../../../middlewares/ai-rate-limit';
import { entitlementMiddleware } from '../../../middlewares/entitlement';
import { createConfiguredAiService } from '../../../services/ai-service.factory';
import { createProtectedStreamingRoute } from '../../../utils/streaming-route-factory';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * The AI feature key used by the engine for prompt resolution, provider
 * routing, and per-feature quota metering. MUST match the stable
 * `AiFeature` enum value defined in `@repo/schemas`.
 */
const FEATURE: AiFeature = 'text_improve';

/**
 * Default locale applied when the request body omits `locale`. The
 * engine also defaults to `'es'`, but making the fallback explicit at
 * the route boundary keeps behaviour auditable in the route file and
 * prevents a future engine-default change from silently shifting the
 * generated language.
 */
const DEFAULT_LOCALE: LanguageEnum = 'es';

// ---------------------------------------------------------------------------
// Prompt builder
// ---------------------------------------------------------------------------

/**
 * Builds the user turn sent to the `text_improve` engine capability.
 *
 * The system prompt is owned by the engine (`DEFAULT_PROMPTS['text_improve']`
 * or a SUPER_ADMIN-overridable version in `ai_prompt_versions`) and is
 * resolved automatically by the engine before the provider call. This
 * function only composes the user-facing instruction + the field content.
 *
 * Exported separately so T-005 (route unit tests) can assert on the
 * exact prompt string for a given `fieldValue` + `fieldType` pair.
 *
 * @param input - The validated text-improvement request body.
 * @returns The user turn sent to the AI provider.
 */
export function buildTextImprovePrompt(input: AiTextImprove): string {
    const label: AiTextImproveFieldType = input.fieldType;
    return `Please improve the following accommodation ${label}:\n\n${input.fieldValue}`;
}

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

/**
 * Protected SSE streaming route for AI text improvement.
 *
 * The factory injects `protectedAuthMiddleware` before our middleware
 * stack, so we only need to specify the AI-specific middleware here.
 * The `requiredPermissions` is omitted — the AI feature is gated by
 * the `ai_text_improve` billing entitlement (not a `PermissionEnum`),
 * which is enforced downstream by `createAiQuotaMiddleware`.
 */
export const protectedAiTextImproveRoute = createProtectedStreamingRoute({
    path: '/',
    summary: 'AI text improvement (streaming SSE)',
    description:
        'Improves a HOST accommodation text field (description or summary) using the `text_improve` AI feature. ' +
        'Streams the suggestion token-by-token via Server-Sent Events. ' +
        'Gated by the `ai_text_improve` billing entitlement and per-plan monthly quota.',
    tags: ['AI - Text Improve'],
    requestSchema: AiTextImproveRequestSchema,
    options: {
        middlewares: [
            // 1. Load user entitlements + limits + billingLoadFailed flag.
            //    MUST be first — createAiQuotaMiddleware reads c.get('userEntitlements').
            entitlementMiddleware(),
            // 2. Per-user burst rate limit + per-IP rate limit (defaults from SPEC-173).
            ...createAiRateLimitMiddlewares(FEATURE),
            // 3. Entitlement gate (403 ENTITLEMENT_REQUIRED) + monthly quota
            //    (403 LIMIT_REACHED) + billing-outage guard (503 SERVICE_UNAVAILABLE).
            createAiQuotaMiddleware(FEATURE)
        ]
    },
    streamHandler: async ({ c }) => {
        // The factory validated the body above (AiTextImproveRequestSchema).
        // We re-read here because the factory does not pass the parsed body
        // into the handler — Hono caches c.req.json() so this is a free lookup.
        const body = (await c.req.json()) as AiTextImprove;
        const { locale } = body;

        const prompt = buildTextImprovePrompt(body);
        const aiService = await createConfiguredAiService();

        const { stream, meta } = await aiService.streamText({
            feature: FEATURE,
            prompt,
            locale: locale ?? DEFAULT_LOCALE
        });

        return { stream, meta };
    }
});
