/**
 * AI text-improvement streaming route (SPEC-198).
 *
 * Mounted at `POST /api/v1/protected/ai/text-improve` by
 * `apps/api/src/routes/ai/protected/index.ts` (the protected AI barrel —
 * T-004 in the spec). Streams an SSE response of incremental text
 * suggestions generated by the `text_improve` AI feature for a HOST
 * accommodation field (`description`, `summary`, or `faq_answer`) or,
 * since HOS-1075, a comercio (gastronomy/experience) field.
 *
 * ## Middleware order (CRITICAL — wrong order = 503 on every request)
 *
 * `createProtectedStreamingRoute` PREPENDS `protectedAuthMiddleware` to
 * whatever we pass in `options.middlewares`, so the final chain is:
 *
 *   auth → entitlement → entitlementRouter → rateLimit-perUser → rateLimit-perIP → quota
 *
 * `entitlementMiddleware` MUST run before `entitlementRouter`
 * ({@link aiTextImproveEntitlementRouter}), which must in turn run before
 * `createAiQuotaMiddleware` — the quota middleware reads
 * `c.get('userEntitlements')`/`c.get('userLimits')`, which are populated by
 * whichever of the two ran last for this request (see
 * {@link aiTextImproveEntitlementRouter}'s docblock for why the choice is
 * per-request, not per-mount). Reordering causes 503 on every request (the
 * quota middleware's billing-load guard trips first) or, worse, silently
 * re-exposes the HOS-1075 leak by leaving the accommodation set in place for
 * a comercio request.
 *
 * ## Per-request service
 *
 * `createConfiguredAiService()` is called once per request (no module
 * singleton) per SPEC-173 §T-043 owner decision — guarantees a rotated
 * provider credential is picked up immediately with no stale-credential
 * window.
 *
 * ## Prompt
 *
 * The system prompt is resolved internally by the engine from
 * `DEFAULT_PROMPTS['text_improve']` (already production-quality, owner-
 * approved as-shipped). The route only sends the user turn.
 *
 * @module apps/api/routes/ai/protected/text-improve
 */

import type { CommerceVertical } from '@repo/billing';
import type { AiFeature, AiTextImprove, LanguageEnum } from '@repo/schemas';
import { AiTextImproveRequestSchema } from '@repo/schemas';
import type { MiddlewareHandler } from 'hono';
import { createAiQuotaMiddleware } from '../../../middlewares/ai-quota';
import { createAiRateLimitMiddlewares } from '../../../middlewares/ai-rate-limit';
import { commerceVerticalEntitlementMiddleware } from '../../../middlewares/commerce-entitlement';
import { entitlementMiddleware } from '../../../middlewares/entitlement';
import { createConfiguredAiService } from '../../../services/ai-service.factory';
import type { AppBindings } from '../../../types';
import { getActorFromContext } from '../../../utils/actor';
import { meterAiUsage } from '../../../utils/ai-usage-metering';
import { apiLogger } from '../../../utils/logger';
import {
    createProtectedStreamingRoute,
    type StreamTextChunk
} from '../../../utils/streaming-route-factory';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * The AI feature key used by the engine for prompt resolution, provider
 * routing, and per-feature quota metering. MUST match the stable
 * `AiFeature` enum value defined in `@repo/schemas`.
 */
const FEATURE: AiFeature = 'text_improve';

/**
 * Default locale applied when the request body omits `locale`. The
 * engine also defaults to `'es'`, but making the fallback explicit at
 * the route boundary keeps behaviour auditable in the route file and
 * prevents a future engine-default change from silently shifting the
 * generated language.
 */
const DEFAULT_LOCALE: LanguageEnum = 'es';

// ---------------------------------------------------------------------------
// Per-request entitlement routing (HOS-1075)
// ---------------------------------------------------------------------------

/**
 * Narrows a raw, unvalidated `entityType` request-body value to a
 * {@link CommerceVertical}, or `null` for `'accommodation'` / absent /
 * anything else.
 *
 * Deliberately loose (reads `unknown`, never throws): this runs BEFORE
 * `AiTextImproveRequestSchema` validates the body, purely to decide which
 * entitlement set to load. A malformed value falls through to `null` here
 * and is rejected properly by the schema a moment later — this function is
 * not the source of truth for what a valid `entityType` is.
 *
 * @param entityType - The raw `entityType` field from the parsed JSON body.
 * @returns The commerce vertical, or `null` when the text belongs to an
 *   accommodation (or the value could not be read as a commerce vertical).
 */
function commerceVerticalFromRawEntityType(entityType: unknown): CommerceVertical | null {
    switch (entityType) {
        case 'gastronomy':
        case 'experience':
            return entityType;
        default:
            return null;
    }
}

/**
 * Routes the request to the correct entitlement source, per-request
 * (HOS-1075).
 *
 * `text-improve` is ONE shared endpoint across every vertical — unlike the
 * gastronomy/experience PATCH routes, which are mounted once per vertical
 * and can hang `commerceVerticalEntitlementMiddleware(vertical)` statically
 * off their own route registration. Here the vertical is only knowable from
 * the REQUEST BODY (`entityType`), so the branch has to happen per request
 * rather than per mount.
 *
 * - `entityType` absent or `'accommodation'` → no-op. The context already
 *   carries the ACCOMMODATION entitlements loaded by the global
 *   `entitlementMiddleware()` mounted ahead of this one — exactly today's
 *   behaviour, unchanged.
 * - `entityType` is `'gastronomy'` / `'experience'` → delegates to
 *   {@link commerceVerticalEntitlementMiddleware}, which REPLACES
 *   `userEntitlements` / `userLimits` with that vertical's grants (read
 *   from the actor's commerce subscription for THAT vertical, never the
 *   accommodation one). This is what closes HOS-1075: a host who is ALSO a
 *   comercio owner can no longer spend their accommodation plan's
 *   `AI_TEXT_IMPROVE` entitlement on comercio text, because the entitlement
 *   set checked downstream is swapped out entirely before
 *   `createAiQuotaMiddleware` reads it.
 *
 * Reads the body via `c.req.json()` — safe to call more than once, Hono
 * caches the parsed result (the `streamHandler` below reads it again for
 * the same reason). A body that fails to parse as JSON is left for the
 * factory's own `requestSchema.safeParse` step to reject with the standard
 * 400 envelope; this middleware just falls through to the accommodation
 * default in that case.
 */
function aiTextImproveEntitlementRouter(): MiddlewareHandler<AppBindings> {
    return async (c, next) => {
        let rawEntityType: unknown;
        try {
            const body = (await c.req.json()) as { entityType?: unknown };
            rawEntityType = body?.entityType;
        } catch {
            rawEntityType = undefined;
        }

        const vertical = commerceVerticalFromRawEntityType(rawEntityType);
        if (vertical) {
            await commerceVerticalEntitlementMiddleware(vertical)(c, next);
            return;
        }

        await next();
    };
}

// ---------------------------------------------------------------------------
// Prompt builder
// ---------------------------------------------------------------------------

/**
 * Builds the user turn sent to the `text_improve` engine capability.
 *
 * The system prompt is owned by the engine (`DEFAULT_PROMPTS['text_improve']`
 * or a SUPER_ADMIN-overridable version in `ai_prompt_versions`) and is
 * resolved automatically by the engine before the provider call. This
 * function only composes the user-facing instruction + the field content.
 *
 * Exported separately so the route unit tests (T-005) can assert on the
 * built user turn for a given `fieldValue` + `fieldType` pair.
 *
 * The instruction is framed per `fieldType`: `description`/`summary` are
 * marketing-facing listing copy, whereas `faq_answer` is a factual guest
 * answer that must NOT be turned into sales copy. Both variants demand a
 * substantial rewrite (not a cosmetic edit) and strip any auto-generated
 * metadata prefix (BETA-180).
 *
 * @param input - The validated text-improvement request body.
 * @returns The user turn sent to the AI provider.
 */
export function buildTextImprovePrompt(input: AiTextImprove): string {
    const isFaq: boolean = input.fieldType === 'faq_answer';
    const fieldLabel: string = isFaq ? 'FAQ answer' : input.fieldType;
    const goal = isFaq
        ? 'Rewrite the following accommodation FAQ answer so it reads as a clear, complete, and genuinely helpful answer for a prospective guest. Do not turn a factual answer into marketing or sales copy.'
        : `Rewrite the following accommodation ${fieldLabel} so it reads as clear, engaging, and persuasive marketing copy for a tourism listing.`;
    return (
        `${goal} ` +
        `Substantially rework the wording, structure, and flow — do not just fix punctuation, expand abbreviations, or make other cosmetic edits. ` +
        `Remove any auto-generated metadata prefix that is not part of the ${fieldLabel} (for example a publication date, the listing type, or a category label such as "Entire home: country house"). ` +
        `Stay faithful to the facts: do not invent amenities, services, prices, distances, or claims that are not in the original. ` +
        `Reply with only the improved ${fieldLabel}, in the same language as the input, with no preamble, labels, or surrounding quotation marks.\n\n` +
        `${input.fieldValue}`
    );
}

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

/**
 * Protected SSE streaming route for AI text improvement.
 *
 * The factory injects `protectedAuthMiddleware` before our middleware
 * stack, so we only need to specify the AI-specific middleware here.
 * The `requiredPermissions` is omitted — the AI feature is gated by
 * the `ai_text_improve` billing entitlement (not a `PermissionEnum`),
 * which is enforced downstream by `createAiQuotaMiddleware`.
 */
export const protectedAiTextImproveRoute = createProtectedStreamingRoute({
    path: '/',
    summary: 'AI text improvement (streaming SSE)',
    description:
        'Improves an accommodation or comercio (gastronomy/experience) text field using the ' +
        '`text_improve` AI feature. Streams the suggestion token-by-token via Server-Sent Events. ' +
        'Gated by the `ai_text_improve` billing entitlement and per-plan monthly quota, resolved ' +
        'against the vertical named by `entityType` (HOS-1075).',
    tags: ['AI - Text Improve'],
    requestSchema: AiTextImproveRequestSchema,
    options: {
        middlewares: [
            // 1. Load ACCOMMODATION entitlements + limits + billingLoadFailed flag.
            //    MUST be first — the router below and createAiQuotaMiddleware both
            //    read c.get('userEntitlements').
            entitlementMiddleware(),
            // 2. HOS-1075: for a comercio request (entityType 'gastronomy' /
            //    'experience'), REPLACE the entitlements/limits set above with
            //    that vertical's own grants, so the feature is gated on the
            //    right subscription instead of always the accommodation one.
            //    No-ops for accommodation requests (the default).
            aiTextImproveEntitlementRouter(),
            // 3. Per-user burst rate limit + per-IP rate limit (defaults from SPEC-173).
            ...createAiRateLimitMiddlewares(FEATURE),
            // 4. Entitlement gate (403 ENTITLEMENT_REQUIRED) + monthly quota
            //    (403 LIMIT_REACHED) + billing-outage guard (503 SERVICE_UNAVAILABLE).
            //    Reads whichever entitlement set step 1 or step 2 last set.
            createAiQuotaMiddleware(FEATURE)
        ]
    },
    streamHandler: async ({ c }) => {
        const handlerStartMs = Date.now();
        const actor = getActorFromContext(c);

        // The factory validated the body above (AiTextImproveRequestSchema).
        // We re-read here because the factory does not pass the parsed body
        // into the handler — Hono caches c.req.json() so this is a free lookup.
        const body = (await c.req.json()) as AiTextImprove;
        const { locale } = body;
        // HOS-1075: absent means 'accommodation' — see AiTextImproveEntityTypeSchema
        // and aiTextImproveEntitlementRouter, which apply the same default when
        // deciding which entitlement set to load.
        const entityType = body.entityType ?? 'accommodation';

        const prompt = buildTextImprovePrompt(body);
        const aiService = await createConfiguredAiService();

        const { stream: rawStream, meta: rawMeta } = await aiService.streamText({
            feature: FEATURE,
            prompt,
            locale: locale ?? DEFAULT_LOCALE
        });

        // -------------------------------------------------------------------
        // Usage metering (HOS-328). See `utils/ai-usage-metering` for why the
        // row exists at all and why the billing unit is the request.
        //
        // This route makes exactly one provider call, so the row's tokens are
        // that call's tokens.
        //
        // Two details drive the shape below:
        //
        // 1. `streamDrainedCleanly` — the engine forwards the same `meta`
        //    promise through its output-moderation wrapper, which throws AFTER
        //    the last token. So `meta` also resolves on requests where the
        //    client received an SSE `error` frame and no reply. Recording those
        //    as 'success' would charge a quota unit for nothing, so the
        //    wrapping generator below reports whether the stream actually
        //    completed. It is a promise rather than a boolean on purpose:
        //    reading a flag would depend on microtask ordering between the
        //    generator and `meta`, which is not guaranteed. The factory always
        //    drains the stream before awaiting `meta`, so awaiting this cannot
        //    deadlock, and the `finally` settles it on throw and early-return
        //    alike.
        //
        // 2. The resolved metadata is returned UNCHANGED — the factory
        //    serialises it verbatim as the SSE `done` frame, so reshaping it
        //    here would be a breaking client-facing change. `meterAiUsage` is
        //    time-bounded precisely because it sits in front of that frame.
        //
        // NOTE: a `.then` fires eagerly the moment its source settles, whether
        // or not anyone awaits the derived promise. So on a post-drain
        // moderation throw — where the factory emits `error` and never awaits
        // `meta` — the row IS still written, with status 'error'. That is what
        // `streamDrainedCleanly` is for.
        //
        // `meta` can also REJECT rather than resolve: the adapter builds it as
        // `Promise.all([usage, finishReason])`, so a mid-stream provider failure
        // rejects it. That is the ordinary provider-5xx path, and tokens have
        // usually already been generated and billed by then, so it gets its own
        // side-channel below rather than being left unmetered.
        //
        // KNOWN LIMITATION: a client that disconnects mid-stream never settles
        // `meta` at all and stays unmetered. That matches the pre-existing
        // contract of the sibling `chat` route and is tracked separately.
        // -------------------------------------------------------------------
        let markStreamSettled: (drainedCleanly: boolean) => void = () => {};
        const streamDrainedCleanly = new Promise<boolean>((resolve) => {
            markStreamSettled = resolve;
        });

        const stream: AsyncIterable<StreamTextChunk> = (async function* () {
            let drainedCleanly = false;
            try {
                for await (const chunk of rawStream) {
                    yield chunk;
                }
                drainedCleanly = true;
            } finally {
                markStreamSettled(drainedCleanly);
            }
        })();

        // Side-channel for the rejection case. Deliberately a SEPARATE branch off
        // `rawMeta` rather than a rejection arm on the chain below: `meta` must
        // keep rejecting exactly as it did before, or the factory would emit a
        // `done` frame for a stream that failed.
        rawMeta.catch(() =>
            meterAiUsage({
                userId: actor.id,
                feature: FEATURE,
                provider: 'none',
                model: 'none',
                // The adapter rejects `meta` without ever reporting usage, so the
                // real token count of a failed stream is unknowable here. The row
                // still carries the error signal.
                promptTokens: 0,
                completionTokens: 0,
                latencyMs: Date.now() - handlerStartMs,
                status: 'error',
                logContext: { fieldType: body.fieldType, entityType, entityId: body.entityId }
            })
        );

        const meta = rawMeta.then(async (resolvedMeta) => {
            // Read the drain flag in its own statement: object-literal properties
            // evaluate in source order, so awaiting inline would compute
            // `latencyMs` at a different instant than the sibling routes do.
            const drainedCleanly = await streamDrainedCleanly;

            // Guarded here as well as inside `meterAiUsage`: the argument object
            // is built OUTSIDE the helper, so a malformed `usage` would reject
            // `meta` and turn an already-delivered reply into an SSE `error`.
            try {
                await meterAiUsage({
                    userId: actor.id,
                    feature: FEATURE,
                    provider: resolvedMeta.provider,
                    model: resolvedMeta.model,
                    promptTokens: resolvedMeta.usage?.promptTokens ?? 0,
                    completionTokens: resolvedMeta.usage?.completionTokens ?? 0,
                    latencyMs: Date.now() - handlerStartMs,
                    status: drainedCleanly ? 'success' : 'error',
                    logContext: { fieldType: body.fieldType, entityType, entityId: body.entityId }
                });
            } catch (meteringError) {
                apiLogger.warn(
                    {
                        fieldType: body.fieldType,
                        error:
                            meteringError instanceof Error
                                ? meteringError.message
                                : String(meteringError)
                    },
                    'text-improve: usage metering threw (non-fatal — the reply was already delivered)'
                );
            }

            return resolvedMeta;
        });

        return { stream, meta };
    }
});
