import { relations } from 'drizzle-orm';
import { index, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { SocialPlatformPgEnum, SocialSourcePgEnum } from '../enums.dbschema.ts';
import { socialAudiences } from './social_audiences.dbschema.ts';

/**
 * Social AI requests table.
 * Append-only log of every GPT ingestion call that led to (or attempted) a draft.
 *
 * NO soft-delete columns and NO audit FKs by design — this table is
 * a permanent audit record. Rows are never deleted by application code.
 */
export const socialAiRequests = pgTable(
    'social_ai_requests',
    {
        id: uuid('id').primaryKey().defaultRandom(),
        /**
         * Opaque ID assigned by the GPT to this request, distinct from draft_id.
         * UNIQUE — used to detect duplicate submissions at the ingestion layer.
         */
        requestId: text('request_id').notNull(),
        source: SocialSourcePgEnum('source').notNull(),
        /** Content topic / subject of the post idea */
        topic: text('topic'),
        /** Free-text idea or prompt from the operator */
        userIdea: text('user_idea'),
        /** Content pillar (e.g. "travel", "gastronomy") */
        pillar: text('pillar'),
        /** Optional audience hint from the GPT */
        audienceId: uuid('audience_id').references(() => socialAudiences.id, {
            onDelete: 'set null'
        }),
        /** JSON array of platform strings suggested by the GPT */
        suggestedPlatformsJson: jsonb('suggested_platforms_json').$type<string[]>(),
        /** Suggested publish format string from the GPT */
        suggestedFormat: text('suggested_format'),
        /** Caption base generated by GPT before admin editing */
        generatedCaptionBase: text('generated_caption_base'),
        /** Full raw request payload as received */
        rawRequestJson: jsonb('raw_request_json').$type<Record<string, unknown>>(),
        /** Full raw response payload returned by this handler */
        rawResponseJson: jsonb('raw_response_json').$type<Record<string, unknown>>(),
        /** Processing status: "success" | "failed" | "partial" */
        status: text('status').notNull(),
        errorMessage: text('error_message'),
        /** Suggested platform for the request */
        suggestedPlatform: SocialPlatformPgEnum('suggested_platform'),
        createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull()
    },
    (table) => ({
        socialAiRequests_requestId_idx: uniqueIndex('socialAiRequests_requestId_idx').on(
            table.requestId
        ),
        socialAiRequests_source_idx: index('socialAiRequests_source_idx').on(table.source),
        socialAiRequests_audienceId_idx: index('socialAiRequests_audienceId_idx').on(
            table.audienceId
        ),
        socialAiRequests_createdAt_idx: index('socialAiRequests_createdAt_idx').on(table.createdAt)
    })
);

export const socialAiRequestsRelations = relations(socialAiRequests, ({ one }) => ({
    audience: one(socialAudiences, {
        fields: [socialAiRequests.audienceId],
        references: [socialAudiences.id]
    })
}));

export type InsertSocialAiRequest = typeof socialAiRequests.$inferInsert;
export type SelectSocialAiRequest = typeof socialAiRequests.$inferSelect;
