import { z } from 'zod';
import { LanguageEnumSchema } from '../user/user.settings.schema.js';
import { AiFeatureSchema, AiModelParamsSchema, AiProviderIdSchema } from './ai-provider.schema.js';

/**
 * AI capability request/response schemas (SPEC-173).
 *
 * Models the I/O contract for every engine capability exposed in §5 of the
 * spec. Each capability has a typed request schema and a typed response schema.
 * The engine uses these at every boundary: HTTP route validation, service-layer
 * calls, and (where relevant) streaming chunk shapes.
 *
 * **Locale reuse**: `LanguageEnumSchema` from `@repo/schemas` (SSoT:
 * `src/entities/user/user.settings.schema.ts`) is the platform-wide locale
 * discriminator (`'es' | 'en' | 'pt'`). It is imported here rather than
 * re-declared to keep the single source of truth.
 *
 * **Capabilities covered**:
 * - `generateText`  — single-shot or multi-turn text generation.
 * - `streamText`    — streaming text generation (chunk + final-meta shapes).
 * - `generateObject`— structured-object generation (envelope only; the target
 *                      Zod schema is a TYPE PARAM at the engine layer).
 * - `moderate`      — provider-agnostic content moderation (Q4, §5).
 *
 * **Shared building blocks**:
 * - `AiUsageStatsSchema` — token-count triple, reused across all responses.
 * - `AiMessageSchema` — single AI SDK v6 CoreMessage (role + content string).
 * - `AiCapabilityRequestBaseSchema` — feature, locale, optional model override,
 *                                      optional inference params.
 *
 * **Strictness**: request schemas use `.strict()` so that unrecognised keys are
 * rejected at the boundary. Response schemas are intentionally NOT `.strict()` —
 * provider adapters may attach diagnostic fields that the caller can ignore.
 */

// ---------------------------------------------------------------------------
// Shared: usage stats
// ---------------------------------------------------------------------------

/**
 * Token-usage statistics returned by every generate/stream response.
 *
 * All counts are non-negative integers (0 is valid when a provider does not
 * report a sub-count, e.g. some streaming adapters only fill `totalTokens`).
 */
export const AiUsageStatsSchema = z.object({
    /** Number of tokens in the prompt / input. */
    promptTokens: z.number().int().min(0),
    /** Number of tokens generated by the model. */
    completionTokens: z.number().int().min(0),
    /** Total tokens consumed (`promptTokens + completionTokens` in most providers). */
    totalTokens: z.number().int().min(0)
});

/** TypeScript type for AI token-usage statistics. */
export type AiUsageStats = z.infer<typeof AiUsageStatsSchema>;

// ---------------------------------------------------------------------------
// Shared: request base
// ---------------------------------------------------------------------------

/**
 * Common fields shared by every capability request.
 *
 * - `feature`  — routes the call to the correct engine config entry.
 * - `locale`   — the user's locale; forwarded to the system-prompt resolver so
 *                the engine can select the right localized prompt (§5.4).
 * - `model`    — optional override of the admin-configured model string for
 *                this call. When absent, the engine uses the feature config.
 * - `params`   — optional inference-time parameter overrides. When absent, the
 *                engine uses the feature config params.
 */
export const AiCapabilityRequestBaseSchema = z
    .object({
        /** AI feature routing key. Determines which config entry the engine uses. */
        feature: AiFeatureSchema,
        /**
         * User locale for prompt localization.
         * One of `'es'`, `'en'`, or `'pt'` (platform SSoT: `LanguageEnumSchema`).
         */
        locale: LanguageEnumSchema,
        /**
         * Optional model identifier override for this call.
         * Overrides the model set in `ai_settings` for the feature.
         * Concrete string values (e.g. `"gpt-4o-mini"`) are NOT validated here —
         * the provider adapter enforces them at call time.
         */
        model: z.string().min(1).optional(),
        /**
         * Optional inference-parameter overrides for this call.
         * Any field omitted here falls back to the feature config value.
         */
        params: AiModelParamsSchema.optional()
    })
    .strict();

/** TypeScript type for the shared capability request base. */
export type AiCapabilityRequestBase = z.infer<typeof AiCapabilityRequestBaseSchema>;

// ---------------------------------------------------------------------------
// Multi-turn message (AI SDK v6 CoreMessage, string-content V1 subset)
// ---------------------------------------------------------------------------

/**
 * A single message in a multi-turn AI conversation.
 *
 * Aligned with the Vercel AI SDK v6 `CoreMessage` shape (role + content).
 * V1 restricts `content` to a plain string — the AI SDK also supports
 * `ContentPart[]` arrays for image/tool content, but that is out of scope
 * for the V1 surface and can be added additively by a child spec.
 *
 * Roles follow the AI SDK convention:
 * - `system`    — System prompt or instructions prepended before the conversation.
 * - `user`      — User turn (human input).
 * - `assistant` — Model turn (prior assistant response for multi-turn context).
 *
 * **Decision (owner-approved 2026-06-04)**: V1 restricts `content` to a plain
 * `string`. The AI SDK v6 additionally supports `ContentPart[]` arrays (for
 * images, tool calls, etc.). Those are omitted (YAGNI); a child spec may extend
 * this schema additively if richer content types are needed.
 */
export const AiMessageSchema = z.object({
    /**
     * The role of the message author.
     * Must be one of `'system'`, `'user'`, or `'assistant'`.
     */
    role: z.enum(['system', 'user', 'assistant']),
    /**
     * The text content of the message.
     * Must be a non-empty string in V1. Empty messages are rejected to prevent
     * accidental blank turns that confuse the model.
     */
    content: z.string().min(1)
});

/** TypeScript type for a single AI conversation message. */
export type AiMessage = z.infer<typeof AiMessageSchema>;

// ---------------------------------------------------------------------------
// generateText
// ---------------------------------------------------------------------------

/**
 * Request schema for the `generateText` capability.
 *
 * Accepts EITHER a `prompt: string` (single-shot) OR a `messages: AiMessage[]`
 * array (multi-turn). Exactly one of the two must be provided — both together
 * and neither are rejected by the `.superRefine()` guard.
 *
 * **Decision (owner-approved 2026-06-04)**: support BOTH `prompt` and `messages`
 * from V1. The Vercel AI SDK v6 `generateText()` already accepts either form;
 * keeping the schema aligned with the SDK means no engine-layer translation cost.
 * `prompt` is sufficient for single-shot call sites (text_improve, search); a
 * `messages` array is needed for multi-turn chat and system+user composition.
 * The two are mutually exclusive to avoid ambiguity: if both are provided the
 * engine would have to pick one, so the schema rejects the combination at the
 * boundary. `generateObject` keeps `prompt`-only (structured output is one-shot
 * in V1 — see its own decision note).
 */
export const GenerateTextRequestSchema = AiCapabilityRequestBaseSchema.extend({
    /**
     * Plain-string prompt for single-shot generation.
     * Mutually exclusive with `messages`. Provide exactly one.
     */
    prompt: z.string().min(1).optional(),
    /**
     * Ordered message array for multi-turn / system+user composition.
     * Mutually exclusive with `prompt`. Provide exactly one.
     * Must contain at least one message.
     */
    messages: z.array(AiMessageSchema).min(1).optional()
})
    .strict()
    .superRefine((val, ctx) => {
        const hasPrompt = val.prompt !== undefined;
        const hasMessages = val.messages !== undefined;
        if (!hasPrompt && !hasMessages) {
            ctx.addIssue({
                code: z.ZodIssueCode.custom,
                message: 'Exactly one of "prompt" or "messages" must be provided (neither was).',
                path: ['prompt']
            });
        }
        if (hasPrompt && hasMessages) {
            ctx.addIssue({
                code: z.ZodIssueCode.custom,
                message:
                    'Exactly one of "prompt" or "messages" must be provided (both were given).',
                path: ['prompt']
            });
        }
    });

/** TypeScript type for a `generateText` request. */
export type GenerateTextRequest = z.infer<typeof GenerateTextRequestSchema>;

/**
 * Response schema for the `generateText` capability.
 *
 * Reflects the fields returned by the Vercel AI SDK v6 `generateText()` result
 * object: `text`, usage statistics, the resolved provider and model, and the
 * finish reason.
 */
export const GenerateTextResponseSchema = z.object({
    /** The generated text output from the model. */
    text: z.string(),
    /** Token usage for this call. */
    usage: AiUsageStatsSchema,
    /** The provider that ultimately served this response (after fallback resolution). */
    provider: AiProviderIdSchema,
    /**
     * The model identifier that was used, as reported by or passed to the adapter.
     * May differ from the requested model if the adapter normalised it.
     */
    model: z.string().min(1),
    /**
     * The finish reason reported by the model.
     * Common values: `'stop'` (natural end), `'length'` (max-tokens hit),
     * `'content-filter'` (moderation stop). The set is open — providers may
     * return additional values; callers should handle unknown strings gracefully.
     */
    finishReason: z.string().min(1)
});

/** TypeScript type for a `generateText` response. */
export type GenerateTextResponse = z.infer<typeof GenerateTextResponseSchema>;

// ---------------------------------------------------------------------------
// streamText
// ---------------------------------------------------------------------------

/**
 * Request schema for the `streamText` capability.
 *
 * Identical prompt-or-messages contract to `GenerateTextRequestSchema` — the
 * capability is differentiated at the engine layer (streaming vs buffered
 * output), not at the request schema level.
 *
 * **Decision (owner-approved 2026-06-04)**: same as `generateText` — both
 * `prompt` and `messages` are supported from V1, mutually exclusive. See the
 * `GenerateTextRequestSchema` decision note for full rationale.
 */
export const StreamTextRequestSchema = AiCapabilityRequestBaseSchema.extend({
    /**
     * Plain-string prompt for single-shot streaming.
     * Mutually exclusive with `messages`. Provide exactly one.
     */
    prompt: z.string().min(1).optional(),
    /**
     * Ordered message array for multi-turn streaming.
     * Mutually exclusive with `prompt`. Provide exactly one.
     * Must contain at least one message.
     */
    messages: z.array(AiMessageSchema).min(1).optional()
})
    .strict()
    .superRefine((val, ctx) => {
        const hasPrompt = val.prompt !== undefined;
        const hasMessages = val.messages !== undefined;
        if (!hasPrompt && !hasMessages) {
            ctx.addIssue({
                code: z.ZodIssueCode.custom,
                message: 'Exactly one of "prompt" or "messages" must be provided (neither was).',
                path: ['prompt']
            });
        }
        if (hasPrompt && hasMessages) {
            ctx.addIssue({
                code: z.ZodIssueCode.custom,
                message:
                    'Exactly one of "prompt" or "messages" must be provided (both were given).',
                path: ['prompt']
            });
        }
    });

/** TypeScript type for a `streamText` request. */
export type StreamTextRequest = z.infer<typeof StreamTextRequestSchema>;

/**
 * Schema for a single delta chunk emitted during a `streamText` response.
 *
 * The SSE framing (event type, `data:` prefix, flush strategy) is handled by
 * the HTTP route layer (T-024), not here. This schema models only the payload
 * of a single streamed token delta.
 */
export const StreamTextChunkSchema = z.object({
    /**
     * Incremental text delta for this chunk.
     * May be an empty string for keep-alive / heartbeat frames (provider
     * dependent). Callers should concatenate non-empty deltas.
     */
    delta: z.string()
});

/** TypeScript type for a `streamText` delta chunk. */
export type StreamTextChunk = z.infer<typeof StreamTextChunkSchema>;

/**
 * Schema for the final metadata frame emitted at the end of a `streamText`
 * response, after all delta chunks.
 *
 * The engine emits this as the last SSE event so callers can record usage.
 * `delta` is absent — callers distinguish this from chunk frames by the
 * presence of `usage` / `finishReason`.
 */
export const StreamTextFinalMetaSchema = z.object({
    /** Aggregate token usage for the full stream. */
    usage: AiUsageStatsSchema,
    /** The provider that served the stream (after fallback resolution). */
    provider: AiProviderIdSchema,
    /** The model identifier that was used for the stream. */
    model: z.string().min(1),
    /** The finish reason for the stream (same semantics as `generateText`). */
    finishReason: z.string().min(1)
});

/** TypeScript type for the `streamText` final metadata frame. */
export type StreamTextFinalMeta = z.infer<typeof StreamTextFinalMetaSchema>;

// ---------------------------------------------------------------------------
// generateObject
// ---------------------------------------------------------------------------

/**
 * Request schema for the `generateObject` capability.
 *
 * **Important design note**: the target structured-output schema (what the
 * model should produce) is a TYPE PARAMETER at the engine layer, not a fixed
 * Zod schema here. The caller passes the Zod schema at call-time to the
 * engine's `generateObject<T>()` method; this request schema only covers the
 * _envelope_ (base fields + prompt).
 *
 * This schema intentionally does NOT include a `schema` field for the target
 * object shape — embedding an arbitrary Zod schema as a serialised value would
 * require runtime schema-from-JSON reconstruction, which is out of scope for V1
 * and fragile in general.
 *
 * **Decision (owner-approved 2026-06-04)**: the `generateObject` response shape
 * is intentionally opaque at the `@repo/schemas` layer — only the meta fields
 * (`usage`, `provider`, `model`, `finishReason`) are defined in
 * `GenerateObjectResponseMetaSchema`. The typed `object: T` field is a generic
 * type parameter known only at the engine call-site; callers compose the full
 * response type by merging their target schema with the meta schema:
 * `z.object({ object: MyOutputSchema }).merge(GenerateObjectResponseMetaSchema)`.
 * This avoids runtime schema-from-JSON reconstruction and keeps the schemas
 * layer free of domain-specific output shapes. `messages` support for
 * `generateObject` is omitted in V1 (structured output is one-shot); a child
 * spec may add it via `.extend()` if multi-turn structured output is needed.
 */
export const GenerateObjectRequestSchema = AiCapabilityRequestBaseSchema.extend({
    /**
     * The prompt instructing the model what object to produce.
     * The engine combines this with the active system prompt and the caller's
     * Zod schema to drive structured output.
     */
    prompt: z.string().min(1)
}).strict();

/** TypeScript type for a `generateObject` request. */
export type GenerateObjectRequest = z.infer<typeof GenerateObjectRequestSchema>;

/**
 * Response metadata for the `generateObject` capability.
 *
 * Contains only the invariant meta fields (usage, provider, model,
 * finishReason). The `object` field — which holds the typed structured output
 * — is NOT defined here because its shape is a generic type parameter `T`
 * known only at the engine call-site.
 *
 * Callers compose the full response type by merging their target schema with
 * this meta schema:
 * ```ts
 * const FullSchema = z.object({ object: MyOutputSchema }).merge(GenerateObjectResponseMetaSchema);
 * ```
 */
export const GenerateObjectResponseMetaSchema = z.object({
    /** Token usage for this call. */
    usage: AiUsageStatsSchema,
    /** The provider that served the response (after fallback resolution). */
    provider: AiProviderIdSchema,
    /** The model identifier that was used. */
    model: z.string().min(1),
    /** The finish reason reported by the model. */
    finishReason: z.string().min(1)
});

/** TypeScript type for `generateObject` response metadata (without the typed object). */
export type GenerateObjectResponseMeta = z.infer<typeof GenerateObjectResponseMetaSchema>;

// ---------------------------------------------------------------------------
// moderate
// ---------------------------------------------------------------------------

/**
 * Request schema for the `moderate` capability (Q4, §5).
 *
 * Intentionally does NOT extend `AiCapabilityRequestBaseSchema` — moderation
 * is a lower-level utility that operates on raw text and does not require
 * feature routing via `AiFeatureSchema`. The engine hardwires the moderation
 * provider (typically the same as the primary text provider).
 *
 * `locale` is optional: content moderators may use it to apply locale-aware
 * policies, but the majority of providers treat moderation language-agnostically.
 */
export const ModerateRequestSchema = z
    .object({
        /** The text input to evaluate for policy violations. */
        input: z.string().min(1),
        /**
         * Optional locale hint for the input.
         * Providers that support locale-aware policies may use this to adjust
         * thresholds or categories.
         */
        locale: LanguageEnumSchema.optional()
    })
    .strict();

/** TypeScript type for a `moderate` request. */
export type ModerateRequest = z.infer<typeof ModerateRequestSchema>;

/**
 * Response schema for the `moderate` capability.
 *
 * Provider-agnostic shape. The engine normalises each provider's output into
 * this envelope so callers are insulated from provider differences.
 *
 * - `flagged`     — top-level flag: `true` if ANY category was violated.
 * - `categories`  — per-category boolean violation flags (open record).
 * - `scores`      — optional per-category confidence scores [0, 1] (open record).
 *                   Not all providers return scores; absent scores mean unknown.
 *
 * **Strictness**: NOT `.strict()` — providers may include additional diagnostic
 * fields that callers can safely ignore.
 */
export const ModerateResponseSchema = z.object({
    /**
     * `true` if the moderation result flagged any policy violation.
     * The caller should treat this as the primary decision signal.
     */
    flagged: z.boolean(),
    /**
     * Per-category violation flags.
     * Keys are provider-defined category names (e.g. `'hate'`, `'violence'`).
     * `true` means the category was flagged.
     */
    categories: z.record(z.string(), z.boolean()),
    /**
     * Optional per-category confidence scores in [0, 1].
     * Higher values indicate stronger confidence in the flag.
     * Absent when the provider does not return numeric scores.
     */
    scores: z.record(z.string(), z.number().min(0).max(1)).optional()
});

/** TypeScript type for a `moderate` response. */
export type ModerateResponse = z.infer<typeof ModerateResponseSchema>;
