import {
    DestinationModel,
    type DrizzleClient,
    UserModel,
    and,
    billingPlans,
    billingPrices,
    eq,
    getDb
} from '@repo/db';
import type { Destination, RoleEnum, User } from '@repo/schemas';

/**
 * E2E test data seeding helpers
 * Provides utilities to create test data for E2E scenarios
 */

// ---------------------------------------------------------------------------
// Billing constants
// ---------------------------------------------------------------------------

/**
 * ARS is the only currency Hospeda bills in. Matches packages/seed/src/required/billingPlans.seed.ts.
 * Centralized here so test data does not silently disagree with the production stack.
 */
const TEST_BILLING_CURRENCY = 'ARS';

/**
 * Stable names for the two baseline test plans seeded by {@link seedBillingTestPlans}.
 *
 * These are intentionally distinct from production plan names (Free / Starter / Pro / ...)
 * so test runs against a dev DB never collide with real seeded plans.
 */
const TEST_PLAN_NAMES = {
    cheap: 'Test Cheap Plan',
    expensive: 'Test Expensive Plan'
} as const;

/**
 * Create a test user with optional overrides
 * @param overrides - Partial user data to override defaults
 * @returns Created user
 */
export async function createTestUser(overrides?: Partial<User>): Promise<User> {
    const userModel = new UserModel();

    const timestamp = Date.now();
    const defaultData = {
        authProviderId:
            (overrides as Record<string, unknown>)?.authProviderId || `test_auth_${timestamp}`,
        email:
            (overrides as Record<string, unknown>)?.email || `test-user-${timestamp}@example.com`,
        slug: overrides?.slug || `test-user-${timestamp}`,
        firstName: overrides?.firstName || 'Test',
        lastName: overrides?.lastName || 'User',
        role: overrides?.role || ('USER' as RoleEnum),
        permissions: overrides?.permissions || [],
        settings: overrides?.settings || {
            notifications: {
                enabled: true,
                allowEmails: true,
                allowSms: false,
                allowPush: false
            }
        },
        ...overrides
    };

    const result = await userModel.create(defaultData as any);
    return result as User;
}

/**
 * Create a test destination with optional overrides
 * @param overrides - Partial destination data to override defaults
 * @returns Created destination
 */
export async function createTestDestination(
    overrides?: Partial<Destination>
): Promise<Destination> {
    const destinationModel = new DestinationModel();

    const timestamp = Date.now();
    const defaultData = {
        name: overrides?.name || `Test Destination ${timestamp}`,
        slug: overrides?.slug || `test-destination-${timestamp}`,
        summary: overrides?.summary || {
            en: 'A beautiful test destination for E2E testing',
            es: 'Un hermoso destino de prueba para testing E2E'
        },
        description: overrides?.description || {
            en: 'This is a test destination created for E2E testing purposes. It has all the necessary data to validate our API endpoints.',
            es: 'Este es un destino de prueba creado para propósitos de testing E2E. Tiene todos los datos necesarios para validar nuestros endpoints de API.'
        },
        ...overrides
    };

    const result = await destinationModel.create(defaultData as any);
    return result as Destination;
}

// ---------------------------------------------------------------------------
// Billing plan + price factories (SPEC-143 T-143-04)
// ---------------------------------------------------------------------------

/**
 * Input shape for {@link createTestPlan}. All fields are optional and override the
 * sensible defaults produced for an isolated test row.
 */
export interface CreateTestPlanInput {
    readonly name?: string;
    readonly description?: string;
    readonly active?: boolean;
    readonly entitlements?: readonly string[];
    readonly limits?: Readonly<Record<string, number>>;
    /** False by default — tests always run in non-livemode. */
    readonly livemode?: boolean;
    /** Free-form JSONB metadata. Defaults include slug/category/isDefault/sortOrder/trialDays/hasTrial. */
    readonly metadata?: Readonly<Record<string, unknown>>;
}

/**
 * Result of {@link createTestPlan}. The returned UUID is generated by the database
 * (`billing_plans.id` defaults to `gen_random_uuid()`).
 */
export interface CreateTestPlanResult {
    readonly planId: string;
    readonly name: string;
}

/**
 * Insert a `billing_plans` row with test-friendly defaults.
 *
 * Mirrors the insert shape used by packages/seed/src/required/billingPlans.seed.ts
 * but without the idempotency check — tests start from a clean DB or a rollback
 * transaction, so name uniqueness is the caller's responsibility (defaults to a
 * timestamped name).
 *
 * Uses Drizzle directly because there is no BaseModel class for billing_plans;
 * the table is provided by @qazuor/qzpay-drizzle and managed by qzpay-hono.
 *
 * @param overrides - Optional fields to override defaults
 * @param db - Drizzle client; defaults to {@link getDb}. Injected by callers that
 *             want to write inside a specific transaction.
 * @returns The created planId and name
 * @throws If the insert returns no row (should never happen with a healthy connection)
 */
export async function createTestPlan(
    overrides: CreateTestPlanInput = {},
    db: DrizzleClient = getDb()
): Promise<CreateTestPlanResult> {
    const timestamp = Date.now();
    const name = overrides.name ?? `Test Plan ${timestamp}`;

    const inserted = await db
        .insert(billingPlans)
        .values({
            name,
            description:
                overrides.description ??
                `E2E test plan created at ${new Date(timestamp).toISOString()}`,
            active: overrides.active ?? true,
            entitlements: [...(overrides.entitlements ?? ['public:read'])],
            limits: { ...(overrides.limits ?? { ads_per_month: 5 }) },
            livemode: overrides.livemode ?? false,
            metadata: {
                slug: `test-plan-${timestamp}`,
                category: 'test',
                isDefault: false,
                sortOrder: 0,
                trialDays: 0,
                hasTrial: false,
                ...(overrides.metadata ?? {})
            }
        })
        .returning({ id: billingPlans.id });

    const row = inserted[0];
    if (!row) {
        throw new Error(`Insert of test plan "${name}" returned no row`);
    }

    return { planId: row.id, name };
}

/**
 * Supported billing intervals matching `billing_prices.billing_interval`. Uses the
 * qzpay-core enum values (`month` / `year`), NOT the user-facing aliases
 * (`monthly` / `annual`).
 */
export type TestBillingInterval = 'month' | 'year';

/**
 * Input shape for {@link createTestPrice}. `planId` and `unitAmount` are required;
 * everything else has a test-friendly default.
 */
export interface CreateTestPriceInput {
    readonly planId: string;
    /** Stored in centavos. 1000 ARS = 100000. */
    readonly unitAmount: number;
    readonly billingInterval: TestBillingInterval;
    readonly intervalCount?: number;
    /** Defaults to ARS — Hospeda's only billing currency. */
    readonly currency?: string;
    readonly active?: boolean;
    readonly livemode?: boolean;
    /** Only attached when > 0; matches seed behaviour (monthly trials only). */
    readonly trialDays?: number;
}

/**
 * Result of {@link createTestPrice}.
 */
export interface CreateTestPriceResult {
    readonly priceId: string;
}

/**
 * Insert a `billing_prices` row for an existing plan.
 *
 * Mirrors `packages/seed/src/required/billingPlans.seed.ts`'s `ensurePrice`
 * shape, including the `trialDays` attachment rule (only forwarded when
 * positive).
 *
 * @param input - Required plan + price details
 * @param db - Drizzle client; defaults to {@link getDb}
 * @returns The created priceId
 * @throws If the insert returns no row
 */
export async function createTestPrice(
    input: CreateTestPriceInput,
    db: DrizzleClient = getDb()
): Promise<CreateTestPriceResult> {
    const shouldAttachTrial = input.trialDays !== undefined && input.trialDays > 0;

    const inserted = await db
        .insert(billingPrices)
        .values({
            planId: input.planId,
            currency: input.currency ?? TEST_BILLING_CURRENCY,
            unitAmount: input.unitAmount,
            billingInterval: input.billingInterval,
            intervalCount: input.intervalCount ?? 1,
            active: input.active ?? true,
            livemode: input.livemode ?? false,
            ...(shouldAttachTrial ? { trialDays: input.trialDays } : {})
        })
        .returning({ id: billingPrices.id });

    const row = inserted[0];
    if (!row) {
        throw new Error(`Insert of test price for plan ${input.planId} returned no row`);
    }

    return { priceId: row.id };
}

/**
 * Result of {@link seedBillingTestPlans}.
 *
 * Provides the two baseline plans every billing e2e test depends on:
 * - `cheap` — entry-level paid tier (no trial)
 * - `expensive` — premium tier with a 14-day trial
 *
 * Each plan carries a monthly price and an annual price (annual = 10x monthly).
 */
export interface TestBillingPlansSeed {
    readonly cheap: {
        readonly planId: string;
        readonly name: string;
        readonly monthlyPriceId: string;
        readonly annualPriceId: string;
    };
    readonly expensive: {
        readonly planId: string;
        readonly name: string;
        readonly monthlyPriceId: string;
        readonly annualPriceId: string;
    };
}

/**
 * Idempotent: ensure the two baseline test plans exist, then return their IDs.
 *
 * Match strategy: lookup by exact `name` (the seed's stable handle, same convention
 * as the production seed). If a plan exists, its existing price rows are reused —
 * the function does NOT recreate or update them. If a plan exists but is missing
 * one of its price rows (cheap or annual), this throws — that's a corrupted seed
 * state and should be cleaned up before re-running tests.
 *
 * Designed to be called from a top-level `beforeAll` in a test file or globally
 * once per test run via a vitest `globalSetup`.
 *
 * @param db - Drizzle client; defaults to {@link getDb}
 * @returns The two baseline plans with their monthly + annual price IDs
 */
export async function seedBillingTestPlans(
    db: DrizzleClient = getDb()
): Promise<TestBillingPlansSeed> {
    const cheap = await ensureBaselinePlan({
        kind: 'cheap',
        monthlyAmount: 100_000, // 1,000 ARS in centavos
        annualAmount: 1_000_000, // 10,000 ARS in centavos (10x monthly)
        trialDays: 0,
        db
    });

    const expensive = await ensureBaselinePlan({
        kind: 'expensive',
        monthlyAmount: 500_000, // 5,000 ARS
        annualAmount: 5_000_000, // 50,000 ARS
        trialDays: 14,
        db
    });

    return { cheap, expensive };
}

/**
 * Internal helper for {@link seedBillingTestPlans}.
 */
interface EnsureBaselinePlanInput {
    readonly kind: keyof typeof TEST_PLAN_NAMES;
    readonly monthlyAmount: number;
    readonly annualAmount: number;
    readonly trialDays: number;
    readonly db: DrizzleClient;
}

/**
 * Internal helper for {@link seedBillingTestPlans}.
 */
async function ensureBaselinePlan(
    input: EnsureBaselinePlanInput
): Promise<TestBillingPlansSeed['cheap']> {
    const name = TEST_PLAN_NAMES[input.kind];
    const existingPlanRows = await input.db
        .select({ id: billingPlans.id })
        .from(billingPlans)
        .where(eq(billingPlans.name, name))
        .limit(1);

    let planId: string;
    if (existingPlanRows[0]) {
        planId = existingPlanRows[0].id;
    } else {
        const created = await createTestPlan(
            {
                name,
                description: `Baseline e2e ${input.kind} plan`,
                entitlements:
                    input.kind === 'cheap' ? ['public:read'] : ['public:read', 'expensive:feature'],
                limits: input.kind === 'cheap' ? { ads_per_month: 5 } : { ads_per_month: 100 },
                metadata: {
                    slug: `test-${input.kind}-plan`,
                    category: 'test-baseline',
                    isDefault: false,
                    sortOrder: input.kind === 'cheap' ? 1 : 2,
                    trialDays: input.trialDays,
                    hasTrial: input.trialDays > 0,
                    monthlyPriceArs: input.monthlyAmount,
                    annualPriceArs: input.annualAmount
                }
            },
            input.db
        );
        planId = created.planId;
    }

    const [monthlyPriceId, annualPriceId] = await Promise.all([
        ensurePlanPrice({
            planId,
            unitAmount: input.monthlyAmount,
            billingInterval: 'month',
            trialDays: input.trialDays,
            db: input.db
        }),
        ensurePlanPrice({
            planId,
            unitAmount: input.annualAmount,
            billingInterval: 'year',
            trialDays: 0, // annual never has trial in Hospeda's model
            db: input.db
        })
    ]);

    return { planId, name, monthlyPriceId, annualPriceId };
}

/**
 * Internal helper for {@link ensureBaselinePlan}: ensure a price row matching
 * (planId, currency=ARS, billingInterval, intervalCount=1) exists. Reuses
 * the existing row when present.
 */
interface EnsurePlanPriceInput {
    readonly planId: string;
    readonly unitAmount: number;
    readonly billingInterval: TestBillingInterval;
    readonly trialDays: number;
    readonly db: DrizzleClient;
}

async function ensurePlanPrice(input: EnsurePlanPriceInput): Promise<string> {
    const existing = await input.db
        .select({ id: billingPrices.id })
        .from(billingPrices)
        .where(
            and(
                eq(billingPrices.planId, input.planId),
                eq(billingPrices.billingInterval, input.billingInterval),
                eq(billingPrices.currency, TEST_BILLING_CURRENCY),
                eq(billingPrices.intervalCount, 1)
            )
        )
        .limit(1);

    if (existing[0]) {
        return existing[0].id;
    }

    const created = await createTestPrice(
        {
            planId: input.planId,
            unitAmount: input.unitAmount,
            billingInterval: input.billingInterval,
            trialDays: input.trialDays > 0 ? input.trialDays : undefined
        },
        input.db
    );
    return created.priceId;
}
