/**
 * Resolves the hospeda repo-root checkout path that several `hops` commands
 * operate on directly (git pull, reading committed fixtures/config from the
 * host filesystem), plus the path to the committed env-var registry JSON
 * bridge that lives inside that checkout.
 *
 * Extracted (HOS-79 T-014) from `src/commands/db-seed.ts`, where an
 * identical 4-line `resolveRepoRoot()` had been independently copy-pasted
 * into `db-migrate.ts` and `db-migrate-test.ts` as well — three verbatim
 * duplicates of the same function. This module is now the single source of
 * truth; all three commands (plus `db-seed-test-users.ts`, which re-exported
 * it from `db-seed.ts`) import it from here instead.
 */

import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { get } from './env.ts';

/**
 * Resolve the hospeda repo checkout root on the VPS host.
 *
 * Order:
 *   1. `HOPS_REPO_ROOT` env var (operator override, e.g. a non-standard
 *      install path) — read via `get()`, so an empty string is treated as
 *      unset, same as everywhere else in the toolkit.
 *   2. `~/hospeda` (the standard install path documented in the README).
 *
 * @returns Absolute path to the repo root. Not guaranteed to exist —
 *   callers that need the checkout to be present should verify with
 *   `existsSync` themselves (see `db-seed.ts` / `db-migrate.ts` for the
 *   established error-message convention).
 */
export function resolveRepoRoot(): string {
    const explicit = get('HOPS_REPO_ROOT');
    if (explicit) return explicit;
    return join(homedir(), 'hospeda');
}

/**
 * Path to the committed env-var registry JSON bridge
 * (`packages/config/generated/env-registry.json`) inside a repo checkout.
 *
 * This file is generated by `pnpm gen:env-registry-json` and committed to
 * git specifically so that `hops` (a bun-standalone package with zero
 * dependency on the pnpm workspace or `@repo/config`) can read the env-var
 * registry, cross-check rules, and value constraints as plain JSON data —
 * no TypeScript parsing, no `node_modules` from the monorepo required.
 *
 * @param repoRoot - Repo root to resolve the path under. Defaults to
 *   {@link resolveRepoRoot}'s result (injectable for tests).
 * @returns Absolute path to `env-registry.json`, whether or not it exists.
 */
export function registryJsonPath(repoRoot: string = resolveRepoRoot()): string {
    return join(repoRoot, 'packages/config/generated/env-registry.json');
}

/**
 * Value type of an environment variable, as recorded in the registry.
 * Mirrors `EnvVarType` in `packages/config/src/env-registry-types.ts`.
 */
export type RegistryEnvVarType = 'string' | 'url' | 'number' | 'boolean' | 'enum';

/**
 * Identifier for apps/services that consume an environment variable.
 * Mirrors `AppId` in `packages/config/src/env-registry-types.ts`.
 */
export type RegistryAppId = 'api' | 'web' | 'admin' | 'mobile' | 'docker' | 'seed';

/**
 * One env var definition as it appears in the committed registry JSON.
 * Deliberately a STRUCTURAL subset of `EnvVarDefinition`
 * (`packages/config/src/env-registry-types.ts`) — only the fields `hops`
 * commands actually read. `hops` cannot import that module (it lives in
 * the pnpm workspace, outside this bun-standalone package's dependency
 * graph), so this type is kept in manual sync with it; the committed JSON
 * is the real interop contract between the two, not this type declaration.
 */
export interface RegistryEnvVarDefinition {
    readonly name: string;
    readonly description: string;
    readonly type: RegistryEnvVarType;
    readonly required: boolean;
    readonly requiredScope?: 'always' | 'production' | 'conditional';
    readonly requiredWhen?: string;
    readonly secret: boolean;
    readonly apps: readonly RegistryAppId[];
    readonly category: string;
    /**
     * True when the value is injected by the platform/CI and must NOT be
     * set by hand (e.g. `NODE_ENV`, `CI`). Mirrors `EnvVarDefinition.platformInjected`
     * in `packages/config/src/env-registry-types.ts`. Used by `env-set --wizard
     * --review-all` (HOS-79 T-019) to skip prompting for these entries.
     */
    readonly platformInjected?: boolean;
    /**
     * Free-form instructions for obtaining a valid value, shown before a
     * secret's password prompt. Mirrors `EnvVarDefinition.howToObtain`.
     */
    readonly howToObtain?: string;
    /**
     * URL to the provider's docs/dashboard for obtaining a value. Mirrors
     * `EnvVarDefinition.helpUrl`.
     */
    readonly helpUrl?: string;
}

/** One side of a cross-check comparison — mirrors `CrossCheckCompareTarget`. */
export interface RegistryCrossCheckCompareTarget {
    readonly app: RegistryAppId;
    readonly key: string;
}

/** A single cross-app consistency rule — mirrors `CrossCheckRule`. */
export interface RegistryCrossCheckRule {
    readonly id: string;
    readonly description: string;
    readonly appliesTo: readonly ('local' | 'coolify')[];
    readonly comparator: 'equals';
    readonly compare: readonly RegistryCrossCheckCompareTarget[];
}

/** One introspected value constraint — mirrors `EnvVarConstraint`. */
export interface RegistryEnvVarConstraint {
    readonly enumValues?: readonly string[];
    readonly boolean?: true;
    readonly numeric?: { readonly min?: number; readonly max?: number };
}

/** Full shape of the committed `env-registry.json` artifact. */
export interface EnvRegistryJson {
    readonly registry: readonly RegistryEnvVarDefinition[];
    readonly crossChecks: readonly RegistryCrossCheckRule[];
    readonly constraints: Readonly<Record<string, RegistryEnvVarConstraint>>;
}

/**
 * Read and parse the committed env-var registry JSON bridge.
 *
 * @param repoRoot - Repo root to read from. Defaults to {@link resolveRepoRoot}.
 * @throws when the file is missing (the checkout predates HOS-79, or the
 *   operator hasn't `git pull`ed yet) or is not valid JSON. Both throw a
 *   plain `Error` with an actionable message rather than calling `die()` —
 *   this function does I/O but no process control, so callers (command
 *   entry points) decide whether to `die()` or propagate.
 */
export function loadRegistryJson(repoRoot: string = resolveRepoRoot()): EnvRegistryJson {
    const path = registryJsonPath(repoRoot);
    if (!existsSync(path)) {
        throw new Error(
            `Env-var registry JSON not found at '${path}'. Run \`pnpm gen:env-registry-json\` in the checkout and commit the result, or \`git pull\` if it was already generated upstream.`
        );
    }
    const raw = readFileSync(path, 'utf-8');
    try {
        return JSON.parse(raw) as EnvRegistryJson;
    } catch (err) {
        throw new Error(
            `Failed to parse env-var registry JSON at '${path}': ${err instanceof Error ? err.message : String(err)}`
        );
    }
}
