/**
 * Minimal .env file parser and writer.
 *
 * Reads and writes `.env.local` files without external dependencies,
 * preserving comments and blank lines on write where possible.
 *
 * @module scripts/env/utils/dotenv
 */

import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';

/**
 * A parsed environment variable map.
 */
export type EnvMap = Map<string, string>;

/**
 * Parameters for reading a .env file.
 */
interface ReadEnvFileParams {
    /** Absolute path to the .env file. */
    readonly filePath: string;
}

/**
 * Parameters for writing a .env file.
 */
interface WriteEnvFileParams {
    /** Absolute path to the .env file. */
    readonly filePath: string;
    /** Map of key → value entries to write. */
    readonly vars: EnvMap;
}

/**
 * Parameters for setting a single key in an existing .env file.
 */
interface SetEnvVarParams {
    /** Absolute path to the .env file. */
    readonly filePath: string;
    /** Variable name. */
    readonly key: string;
    /** Variable value (will be quoted if it contains spaces or special chars). */
    readonly value: string;
}

/**
 * Parses a .env file and returns a Map of key → value pairs.
 *
 * Handles:
 * - Lines starting with `#` (skipped as comments)
 * - Blank lines (skipped)
 * - Quoted values (`"..."` and `'...'` — quotes stripped)
 * - `export KEY=VALUE` syntax
 *
 * If the file does not exist, returns an empty Map rather than throwing.
 *
 * @param params - File path to read.
 * @returns Map of variable names to their string values.
 *
 * @example
 * ```ts
 * const vars = await readEnvFile({ filePath: '/project/apps/api/.env.local' });
 * console.log(vars.get('HOSPEDA_API_URL'));
 * ```
 */
export async function readEnvFile(params: ReadEnvFileParams): Promise<EnvMap> {
    const { filePath } = params;

    if (!existsSync(filePath)) {
        return new Map();
    }

    const content = await readFile(filePath, 'utf-8');
    const result: EnvMap = new Map();

    for (const rawLine of content.split('\n')) {
        const line = rawLine.trim();

        // Skip comments and blank lines
        if (!line || line.startsWith('#')) continue;

        // Strip optional `export ` prefix
        const stripped = line.startsWith('export ') ? line.slice(7).trim() : line;

        const eqIdx = stripped.indexOf('=');
        if (eqIdx === -1) continue;

        const key = stripped.slice(0, eqIdx).trim();
        let value = stripped.slice(eqIdx + 1).trim();

        // Strip surrounding quotes
        if (
            (value.startsWith('"') && value.endsWith('"')) ||
            (value.startsWith("'") && value.endsWith("'"))
        ) {
            value = value.slice(1, -1);
        }

        if (key) {
            result.set(key, value);
        }
    }

    return result;
}

/**
 * Writes a complete env variable map to a .env file.
 *
 * Overwrites the file entirely. Values containing spaces or special
 * characters are automatically double-quoted.
 *
 * @param params - File path and variable map to write.
 *
 * @example
 * ```ts
 * await writeEnvFile({
 *   filePath: '/project/apps/api/.env.local',
 *   vars: new Map([['HOSPEDA_API_URL', 'http://localhost:3001']]),
 * });
 * ```
 */
export async function writeEnvFile(params: WriteEnvFileParams): Promise<void> {
    const { filePath, vars } = params;

    const lines: string[] = ['# Generated by hospeda env tools', ''];

    for (const [key, value] of vars.entries()) {
        const needsQuoting = /[\s"'\\#]/.test(value) || value.length === 0;
        const serialized = needsQuoting ? `"${value.replace(/"/g, '\\"')}"` : value;
        lines.push(`${key}=${serialized}`);
    }

    lines.push('');
    await writeFile(filePath, lines.join('\n'), 'utf-8');
}

/**
 * Sets or updates a single variable in an existing .env file,
 * preserving all other lines, comments, and blank lines.
 *
 * If the key already exists, its line is replaced in-place.
 * If the key is new, it is appended at the end of the file.
 * Creates the file if it does not exist.
 *
 * @param params - File path, variable key, and new value.
 *
 * @example
 * ```ts
 * await setEnvVar({
 *   filePath: '/project/apps/api/.env.local',
 *   key: 'HOSPEDA_API_URL',
 *   value: 'https://api.example.com',
 * });
 * ```
 */
export async function setEnvVar(params: SetEnvVarParams): Promise<void> {
    const { filePath, key, value } = params;

    const needsQuoting = /[\s"'\\#]/.test(value) || value.length === 0;
    const serialized = needsQuoting ? `"${value.replace(/"/g, '\\"')}"` : value;
    const newLine = `${key}=${serialized}`;

    if (!existsSync(filePath)) {
        await writeFile(filePath, `${newLine}\n`, 'utf-8');
        return;
    }

    const content = await readFile(filePath, 'utf-8');
    const lines = content.split('\n');

    let found = false;
    const updated = lines.map((line) => {
        const stripped = line.startsWith('export ') ? line.slice(7).trim() : line.trim();
        const eqIdx = stripped.indexOf('=');
        if (eqIdx !== -1 && stripped.slice(0, eqIdx).trim() === key) {
            found = true;
            return newLine;
        }
        return line;
    });

    if (!found) {
        // Append before trailing blank lines
        const lastNonEmpty = updated.reduceRight(
            (acc, line, i) => (acc === -1 && line.trim() ? i : acc),
            -1
        );
        updated.splice(lastNonEmpty + 1, 0, newLine);
    }

    await writeFile(filePath, updated.join('\n'), 'utf-8');
}
