export enum AccommodationTypeEnum {
    APARTMENT = 'APARTMENT',
    HOUSE = 'HOUSE',
    COUNTRY_HOUSE = 'COUNTRY_HOUSE',
    CABIN = 'CABIN',
    HOTEL = 'HOTEL',
    HOSTEL = 'HOSTEL',
    CAMPING = 'CAMPING',
    ROOM = 'ROOM',
    MOTEL = 'MOTEL',
    RESORT = 'RESORT',
    APART_HOTEL = 'APART_HOTEL',
    ESTANCIA = 'ESTANCIA',
    BED_AND_BREAKFAST = 'BED_AND_BREAKFAST'
}
