export enum AmenitiesTypeEnum {
    CLIMATE_CONTROL = 'CLIMATE_CONTROL',
    CONNECTIVITY = 'CONNECTIVITY',
    ENTERTAINMENT = 'ENTERTAINMENT',
    KITCHEN = 'KITCHEN',
    BED_AND_BATH = 'BED_AND_BATH',
    OUTDOORS = 'OUTDOORS',
    ACCESSIBILITY = 'ACCESSIBILITY',
    SERVICES = 'SERVICES',
    SAFETY = 'SAFETY',
    FAMILY_FRIENDLY = 'FAMILY_FRIENDLY',
    WORK_FRIENDLY = 'WORK_FRIENDLY',
    GENERAL_APPLIANCES = 'GENERAL_APPLIANCES'
}
