export enum ProfessionalServiceCategoryEnum {
    PHOTO = 'PHOTO',
    PHOTOGRAPHY = 'PHOTOGRAPHY',
    COPYWRITING = 'COPYWRITING',
    CONSULTING = 'CONSULTING',
    SEO = 'SEO',
    DESIGN = 'DESIGN',
    MAINTENANCE = 'MAINTENANCE',
    TOUR = 'TOUR',
    BIKE_RENTAL = 'BIKE_RENTAL',
    OTHER = 'OTHER'
}
