/**
 * @file check-catalog-sql.ts
 * @description GUARD:G18 (HOS-1352 program, built by V1 / HOS-1431, AC:V1:4,
 * TEST:V1:5): the reference rows the migrations write are the rows the code
 * catalog generates.
 *
 * A migration cannot call code, so the key table travels as SQL generated by
 * `scripts/generate-catalog-sql.ts` and committed inside a migration. This guard
 * regenerates every load from the code and compares it with what the migration
 * history writes.
 *
 * ## The predicate
 *
 * For each load (`catalog_key`, `vertical`, and the four plan catalog tables):
 * the CUMULATIVE set of rows inserted into that table by every versioned
 * migration (`packages/db/src/migrations/NNNN_*.sql`, in file order, keyed by
 * the primary key, the first column) equals, row by row and column by column,
 * the set the generator produces from the code. Red names the load and every key
 * that differs: in the code but inserted by no migration, inserted but no longer
 * in the code, or inserted with different attribute values.
 *
 * Cumulative, not a diff of one file: a later migration that inserts a new key
 * is how the catalog grows, so the guard reads the whole history. Comments are
 * not compared (the hand-written note in `0129_gorgeous_storm.sql` stays outside
 * the compared region), nor is the column order of an `INSERT` (columns are
 * matched by name).
 *
 * ## What it does NOT do, so a green run is not read as more
 *
 * - It reads `INSERT INTO "<table>" (...) VALUES (...), ...;` with string,
 *   safe-integer, boolean and `NULL` literals. Any OTHER statement that writes one of the
 *   tables (`UPDATE`, `DELETE`, `TRUNCATE`, `INSERT ... SELECT`,
 *   `INSERT ... ON CONFLICT`) cannot be folded into the row set, so the guard
 *   FAILS on it instead of guessing; teach it the new shape first.
 * - It does not read the database. That the migration actually applies, and
 *   that the FK rejects an unknown key, is TEST:V1:6
 *   (`packages/db/test/integration/catalog-key-fk-from-empty.test.ts`).
 * - V2.4b's production catalog loads are included in the default migration scan.
 * - The extras carril (`migrations/extras/`) is not read: reference rows never
 *   go there.
 *
 * ## Positive control
 *
 * `run({ migrationsDir, loads })` takes any directory and any expected loads:
 * `scripts/__tests__/check-catalog-sql.test.ts` adds a key to the code catalog
 * without regenerating and sees it red, naming the load and the key.
 *
 * Exit codes: 0 = migrations match the code; 1 = a difference, or SQL the guard
 * cannot interpret.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildLoads, type CatalogLoad, LOAD_NAMES, type SqlValue } from './generate-catalog-sql.js';

/** The versioned migrations directory, repo-relative. */
export const MIGRATIONS_DIR = 'packages/db/src/migrations';

/** A versioned migration file name: four digits, underscore, name, `.sql`. */
const MIGRATION_FILE = /^\d{4}_[\w-]+\.sql$/;

/** One problem found by the guard. */
export interface CatalogSqlViolation {
    /** The load's human label. */
    readonly load: string;
    /** The differing key (primary key value), when the problem is about one row. */
    readonly key?: string;
    /** What is wrong. */
    readonly detail: string;
}

/** Rows a migration history inserted into one table, keyed by primary key. */
interface InsertedRows {
    readonly rows: Map<
        string,
        { readonly values: Record<string, SqlValue>; readonly file: string }
    >;
    readonly violations: CatalogSqlViolation[];
}

/**
 * Splits SQL text into statements on `;`, dropping `--` comments and keeping
 * string literals intact.
 *
 * @param input - Split input.
 * @param input.sql - The SQL text.
 * @returns The statements, trimmed, without the trailing `;`.
 */
export function splitStatements({ sql }: { readonly sql: string }): readonly string[] {
    const statements: string[] = [];
    let current = '';
    let i = 0;
    while (i < sql.length) {
        const ch = sql[i] as string;
        if (ch === '-' && sql[i + 1] === '-') {
            const end = sql.indexOf('\n', i);
            i = end === -1 ? sql.length : end;
            continue;
        }
        if (ch === "'") {
            let j = i + 1;
            while (j < sql.length) {
                if (sql[j] === "'" && sql[j + 1] === "'") j += 2;
                else if (sql[j] === "'") break;
                else j += 1;
            }
            current += sql.slice(i, j + 1);
            i = j + 1;
            continue;
        }
        if (ch === ';') {
            if (current.trim()) statements.push(current.trim());
            current = '';
        } else {
            current += ch;
        }
        i += 1;
    }
    if (current.trim()) statements.push(current.trim());
    return statements;
}

/**
 * Parses the `VALUES` list of an `INSERT`: parenthesised tuples of string,
 * safe-integer, boolean and `NULL` literals.
 *
 * @param input - Parse input.
 * @param input.text - Everything after the `VALUES` keyword.
 * @returns The tuples, or an error naming the first token it could not read.
 */
export function parseValues({ text }: { readonly text: string }): {
    readonly tuples: readonly (readonly SqlValue[])[];
    readonly error?: string;
} {
    const tuples: SqlValue[][] = [];
    let i = 0;
    const skipSpace = () => {
        while (i < text.length && /\s/.test(text[i] as string)) i += 1;
    };
    while (true) {
        skipSpace();
        if (text[i] !== '(') return { tuples, error: `expected "(" at "${text.slice(i, i + 20)}"` };
        i += 1;
        const tuple: SqlValue[] = [];
        while (true) {
            skipSpace();
            if (text[i] === "'") {
                let value = '';
                i += 1;
                while (i < text.length) {
                    if (text[i] === "'" && text[i + 1] === "'") {
                        value += "'";
                        i += 2;
                    } else if (text[i] === "'") break;
                    else {
                        value += text[i];
                        i += 1;
                    }
                }
                i += 1;
                tuple.push(value);
            } else if (/^NULL\b/i.test(text.slice(i))) {
                tuple.push(null);
                i += 4;
            } else if (/^(TRUE|FALSE)\b/i.test(text.slice(i))) {
                const match = /^(TRUE|FALSE)\b/i.exec(text.slice(i)) as RegExpExecArray;
                tuple.push(match[1]?.toUpperCase() === 'TRUE');
                i += match[0].length;
            } else if (/^-?(?:0|[1-9]\d*)\b/.test(text.slice(i))) {
                const match = /^-?(?:0|[1-9]\d*)\b/.exec(text.slice(i)) as RegExpExecArray;
                const value = Number(match[0]);
                if (!Number.isSafeInteger(value)) {
                    return { tuples, error: `unsafe integer at "${text.slice(i, i + 20)}"` };
                }
                tuple.push(value);
                i += match[0].length;
            } else {
                return { tuples, error: `unsupported value at "${text.slice(i, i + 20)}"` };
            }
            skipSpace();
            if (text[i] === ',') {
                i += 1;
                continue;
            }
            if (text[i] === ')') {
                i += 1;
                break;
            }
            return { tuples, error: `expected "," or ")" at "${text.slice(i, i + 20)}"` };
        }
        tuples.push(tuple);
        skipSpace();
        if (i >= text.length) return { tuples };
        if (text[i] !== ',')
            return { tuples, error: `unexpected "${text.slice(i, i + 20)}" after a row` };
        i += 1;
    }
}

function escapeRegExp({ text }: { readonly text: string }): string {
    return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Folds every statement of the migration history that writes `load.table` into
 * one row set keyed by primary key.
 *
 * @param input - Fold input.
 * @param input.files - Migration files in apply order: name and SQL text.
 * @param input.load - The load whose table to read; its first column is the key.
 * @returns The inserted rows and any statement the guard cannot interpret.
 */
export function collectInsertedRows({
    files,
    load
}: {
    readonly files: readonly { readonly name: string; readonly sql: string }[];
    readonly load: CatalogLoad;
}): InsertedRows {
    const table = escapeRegExp({ text: load.table });
    const touches = new RegExp(
        `\\b(?:INSERT\\s+INTO|UPDATE|DELETE\\s+FROM|TRUNCATE(?:\\s+TABLE)?)\\s+(?:ONLY\\s+)?(?:"?public"?\\.)?"?${table}"?(?=[\\s(;,]|$)`,
        'i'
    );
    const plainInsert = new RegExp(
        `^INSERT\\s+INTO\\s+(?:"?public"?\\.)?"?${table}"?\\s*\\(([^)]*)\\)\\s*VALUES\\s*([\\s\\S]*)$`,
        'i'
    );
    const rows: InsertedRows['rows'] = new Map();
    const violations: CatalogSqlViolation[] = [];
    const keyColumn = load.columns[0] as string;

    for (const file of files) {
        for (const statement of splitStatements({ sql: file.sql })) {
            if (!touches.test(statement)) continue;
            const match = plainInsert.exec(statement);
            const parsed = match ? parseValues({ text: match[2] as string }) : undefined;
            if (!match || !parsed || parsed.error || /\bON\s+CONFLICT\b/i.test(statement)) {
                violations.push({
                    load: load.label,
                    detail:
                        `${file.name}: a statement writes "${load.table}" in a shape G18 cannot fold into the ` +
                        `row set (${parsed?.error ?? 'not a plain INSERT ... VALUES'}). Teach the guard the shape ` +
                        `before using it: "${statement.slice(0, 80).replace(/\s+/g, ' ')}..."`
                });
                continue;
            }
            const columns = (match[1] as string)
                .split(',')
                .map((c) => c.trim().replace(/^"|"$/g, ''));
            for (const tuple of parsed.tuples) {
                if (tuple.length !== columns.length) {
                    violations.push({
                        load: load.label,
                        detail: `${file.name}: a row has ${tuple.length} values for ${columns.length} columns.`
                    });
                    continue;
                }
                const values = Object.fromEntries(columns.map((c, idx) => [c, tuple[idx] ?? null]));
                const key = values[keyColumn];
                if (typeof key !== 'string') {
                    violations.push({
                        load: load.label,
                        detail: `${file.name}: a row has no "${keyColumn}" value.`
                    });
                    continue;
                }
                const previous = rows.get(key);
                if (previous) {
                    violations.push({
                        load: load.label,
                        key,
                        detail: `inserted twice (${previous.file} and ${file.name}); the second insert would violate the primary key.`
                    });
                    continue;
                }
                rows.set(key, { values, file: file.name });
            }
        }
    }
    return { rows, violations };
}

/**
 * Compares one load the code generates with the rows the migrations insert.
 *
 * @param input - Compare input.
 * @param input.files - Migration files in apply order.
 * @param input.load - The load regenerated from the code.
 * @returns Every difference, each naming the load and, when it is about a row, the key.
 */
export function compareLoad({
    files,
    load
}: {
    readonly files: readonly { readonly name: string; readonly sql: string }[];
    readonly load: CatalogLoad;
}): readonly CatalogSqlViolation[] {
    const inserted = collectInsertedRows({ files, load });
    const violations = [...inserted.violations];
    const expectedKeys = new Set<string>();

    for (const row of load.rows) {
        const key = row[0] as string;
        expectedKeys.add(key);
        const found = inserted.rows.get(key);
        if (!found) {
            violations.push({
                load: load.label,
                key,
                detail: 'is in the code catalog but no migration inserts it (regenerate the SQL into a new migration).'
            });
            continue;
        }
        const differing = load.columns
            .map((column, idx) => ({
                column,
                code: row[idx] ?? null,
                sql: found.values[column] ?? null
            }))
            .filter((cell) => cell.code !== cell.sql);
        if (differing.length > 0) {
            violations.push({
                load: load.label,
                key,
                detail: `differs from ${found.file}: ${differing
                    .map(
                        (c) =>
                            `${c.column} is ${JSON.stringify(c.code)} in code, ${JSON.stringify(c.sql)} in SQL`
                    )
                    .join('; ')}.`
            });
        }
    }
    for (const [key, found] of inserted.rows) {
        if (!expectedKeys.has(key)) {
            violations.push({
                load: load.label,
                key,
                detail: `is inserted by ${found.file} but is no longer in the code catalog.`
            });
        }
    }
    return violations;
}

/**
 * Reads the versioned migrations of a directory, in apply (file name) order.
 *
 * @param input - Read input.
 * @param input.migrationsDir - Absolute path to the migrations directory.
 * @returns Each file's name and SQL text.
 */
export function readMigrations({ migrationsDir }: { readonly migrationsDir: string }): readonly {
    readonly name: string;
    readonly sql: string;
}[] {
    return readdirSync(migrationsDir)
        .filter((name) => MIGRATION_FILE.test(name))
        .sort()
        .map((name) => ({ name, sql: readFileSync(join(migrationsDir, name), 'utf8') }));
}

/**
 * Runs GUARD:G18.
 *
 * @param args - Run input.
 * @param args.migrationsDir - Migrations directory; defaults to the repo's.
 * @param args.loads - The loads to verify; defaults to the generator's, regenerated from code.
 * @returns The exit code and the report.
 */
export function run(
    args: { readonly migrationsDir?: string; readonly loads?: readonly CatalogLoad[] } = {}
): { readonly exitCode: number; readonly output: string } {
    const repoRoot = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
    const migrationsDir = args.migrationsDir ?? join(repoRoot, MIGRATIONS_DIR);
    const loads = args.loads ?? LOAD_NAMES.map((name) => buildLoads()[name]);
    const lines = ['=== GUARD:G18 - migration reference rows match the code catalog ==='];

    let files: ReturnType<typeof readMigrations>;
    try {
        files = readMigrations({ migrationsDir });
    } catch (error) {
        lines.push(`ERROR: cannot read ${migrationsDir}: ${(error as Error).message}`);
        return { exitCode: 1, output: lines.join('\n') };
    }
    if (files.length === 0) {
        lines.push(
            `ERROR: no versioned migration found in ${migrationsDir}; the scan is broken, not clean.`
        );
        return { exitCode: 1, output: lines.join('\n') };
    }

    const violations = loads.flatMap((load) => compareLoad({ files, load }));
    if (violations.length > 0) {
        for (const load of loads) {
            const mine = violations.filter((v) => v.load === load.label);
            if (mine.length === 0) continue;
            lines.push(
                '',
                `FAIL load ${load.label}: the SQL the migrations write is not the SQL the code generates.`
            );
            for (const v of mine) lines.push(`  ${v.key ? `key '${v.key}' ` : ''}${v.detail}`);
        }
        lines.push(
            '',
            'Fix: run `pnpm gen:catalog-sql --load=<table>` and commit its rows in a NEW migration',
            '(never edit an applied one).'
        );
        return { exitCode: 1, output: lines.join('\n') };
    }

    lines.push(
        `OK: ${files.length} migration file(s) read; ${loads
            .map((l) => `${l.table} ${l.rows.length} row(s)`)
            .join(', ')} match the code catalog.`
    );
    return { exitCode: 0, output: lines.join('\n') };
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
    const { exitCode, output } = run();
    (exitCode === 0 ? console.log : console.error)(output);
    process.exit(exitCode);
}
