import { createServer } from 'node:http'
import { mkdirSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { randomUUID } from 'node:crypto'
import { DatabaseSync } from 'node:sqlite'

const port = Number(process.env.ARTIFACT_PORT || 4317)
const sessionCookieValue = randomUUID()
const dataDir = process.env.ARTIFACT_DATA_DIR || join(homedir(), '.local', 'share', 'opencode-artifacts')
mkdirSync(dataDir, { recursive: true })
const db = new DatabaseSync(join(dataDir, 'artifacts.sqlite'))
db.exec(`PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS artifacts (id TEXT PRIMARY KEY, project TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, latest_version INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS versions (artifact_id TEXT NOT NULL, version INTEGER NOT NULL, bundle_json TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (artifact_id, version));
CREATE TABLE IF NOT EXISTS events (event_id TEXT PRIMARY KEY, artifact_id TEXT NOT NULL, version INTEGER NOT NULL, type TEXT NOT NULL, payload_json TEXT NOT NULL, idempotency_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL);`)
const now = () => new Date().toISOString()
const json = (res, status, value) => { const body = JSON.stringify(value); res.writeHead(status, {'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex, nofollow, noarchive'}); res.end(body) }
const html = (res, body) => { res.writeHead(200, {'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-robots-tag':'noindex, nofollow, noarchive','set-cookie':`artifact_session=${sessionCookieValue}; HttpOnly; SameSite=Strict; Path=/`}); res.end(body) }
const authorized = req => { const cookie = req.headers.cookie || ''; const origin = req.headers.origin; return cookie.split(';').some(v => v.trim() === `artifact_session=${sessionCookieValue}`) && (!origin || origin === `http://127.0.0.1:${port}` || origin === `http://localhost:${port}`) }
const readBody = async req => { let s=''; for await (const c of req) { s += c; if (s.length > 1_000_000) throw new Error('body too large') }; return JSON.parse(s || '{}') }
const findArtifact = id => db.prepare('SELECT * FROM artifacts WHERE id = ? OR slug = ?').get(id, id)
const getBundle = (id, version) => { const row = db.prepare('SELECT bundle_json FROM versions WHERE artifact_id=? AND version=?').get(id, version); return row ? JSON.parse(row.bundle_json) : null }
function currentState(id, version) { const state = {}; const bundle=getBundle(id,version); for (const section of bundle?.data?.sections||[]) { if (section.type==='checklist') for (const item of section.data?.items||[]) if (item.done===true) state[item.id]=true; } const rows = db.prepare('SELECT type,payload_json FROM events WHERE artifact_id=? AND version>=? ORDER BY created_at').all(id, version); for (const row of rows) { if (row.type === 'reviewChecklist.itemToggled') { const p=JSON.parse(row.payload_json); state[p.itemId] = p.checked } else if (row.type === 'widget.valueChanged') { const p=JSON.parse(row.payload_json); state[p.fieldId] = p.value } }; return state }
function shell(title, content, script='') {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex,nofollow,noarchive"><title>${escapeHtml(title)}</title><style>
:root{color-scheme:dark;--bg:#101419;--fg:#e5e7eb;--muted:#94a3b8;--surface:#18212b;--surface-2:#202b38;--border:#334155;--control:#1b222c;--accent:#67e8f9;--button:#253242}
body{font:16px system-ui;margin:0;background:var(--bg);color:var(--fg);transition:background .2s,color .2s}body.light{color-scheme:light;--bg:#f6f7f9;--fg:#17202a;--muted:#64748b;--surface:#fff;--surface-2:#f8fafc;--border:#dfe3e8;--control:#fff;--accent:#2457c5;--button:#fff}
main{max-width:960px;margin:32px auto;padding:0 18px}.topbar{display:flex;justify-content:flex-end;align-items:center;gap:8px;font-size:.85rem}.topbar select{background:var(--control);color:var(--fg);border:1px solid var(--border);border-radius:6px;padding:5px}a{color:var(--accent)}article,li{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:16px;margin:12px 0}button{padding:8px 12px;border:1px solid var(--border);border-radius:8px;background:var(--button);color:var(--fg);cursor:pointer}.hero{background:#17202a;color:#f8fafc;padding:28px}.hero h2{font-size:clamp(2rem,5vw,4rem);margin:8px 0}.eyebrow{letter-spacing:.14em;text-transform:uppercase;color:var(--accent);font-size:.75rem}.callout{border-left:4px solid #22d3ee}.callout.warning{border-color:#f59e0b}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:1px;background:var(--border)}.metrics div{background:var(--surface-2);padding:18px}.metrics strong{display:block;font-size:2rem}.metrics span,.muted{color:var(--muted)}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--border)}.timeline{border-left:2px solid var(--accent);padding-left:24px}.timeline li{list-style:none;border:0;border-radius:0;padding:8px 0;margin:0;background:transparent}.timeline span{display:block;color:var(--muted)}button:disabled{opacity:.5}.check{display:flex;gap:10px;align-items:flex-start}.check>span{display:grid;gap:3px}.item-meta{color:var(--accent);font-size:.75rem;text-transform:uppercase;letter-spacing:.08em}.item-description,.item-notes{display:block;color:var(--muted);font-size:.9rem}.item-notes{font-style:italic}.field{display:grid;gap:6px;margin:12px 0}.field input,.field select{background:var(--control);color:var(--fg);border:1px solid var(--border);border-radius:6px;padding:8px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}
</style></head><body><main><div class="topbar"><label>Tema <select id="theme"><option value="dark">Oscuro</option><option value="light">Claro</option><option value="system">Sistema</option></select></label></div>${content}</main><script>const theme=document.querySelector('#theme');const saved=localStorage.getItem('artifact-theme')||'dark';const applyTheme=t=>{document.body.classList.toggle('light',t==='light'||(t==='system'&&matchMedia('(prefers-color-scheme:light)').matches));theme.value=t};applyTheme(saved);theme.addEventListener('change',()=>{localStorage.setItem('artifact-theme',theme.value);applyTheme(theme.value)});${script}</script></body></html>`
}
const escapeHtml = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
function gallery() { const rows=db.prepare('SELECT * FROM artifacts ORDER BY updated_at DESC').all(); const items=rows.map(a=>`<article><h2><a href="/artifacts/${encodeURIComponent(a.slug)}">${escapeHtml(a.title)}</a></h2><p class="muted">${escapeHtml(a.project)} · ${a.latest_version} versión(es) · ${escapeHtml(a.updated_at)}</p></article>`).join('') || '<p>No hay artifacts. Ejecutá <code>pnpm publish:sample</code>.</p>'; return shell('Artifacts', `<h1>Artifacts locales</h1><p class="muted">Solo accesible en esta PC · noindex · nofollow · actualización automática</p>${items}`, `setInterval(()=>location.reload(),5000)`) }
function renderSection(section, state) {
  const d=section.data||{}; const title=section.title?`<h2>${escapeHtml(section.title)}</h2>`:''
  if(section.type==='hero') return `<article class="hero"><p class="eyebrow">${escapeHtml(d.eyebrow||'')}</p><h2>${escapeHtml(d.title||section.title||'')}</h2><p>${escapeHtml(d.description||d.text||'')}</p></article>`
  if(section.type==='prose') return `<article>${title}<p>${escapeHtml(d.text||'')}</p></article>`
  if(section.type==='callout') return `<article class="callout ${escapeHtml(d.tone||'info')}">${title}<p>${escapeHtml(d.text||'')}</p></article>`
  if(section.type==='metricGrid') return `<article>${title}<div class="metrics">${(d.metrics||[]).map(m=>`<div><strong>${escapeHtml(m.value)}</strong><span>${escapeHtml(m.label)}</span></div>`).join('')}</div></article>`
  if(section.type==='table') return `<article>${title}<div class="scroll"><table><thead><tr>${(d.columns||[]).map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr></thead><tbody>${(d.rows||[]).map(row=>`<tr>${row.map(c=>`<td>${escapeHtml(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></article>`
  if(section.type==='timeline') return `<article>${title}<ol class="timeline">${(d.items||[]).map(i=>`<li><strong>${escapeHtml(i.label||'')}</strong><span>${escapeHtml(i.detail||'')}</span></li>`).join('')}</ol></article>`
  if(section.type==='checklist') return `<article>${title}<ul>${(d.items||[]).map(i=>`<li class="check"><input type="checkbox" data-item="${escapeHtml(i.id)}" ${state[i.id]??i.done?'checked':''}><span><strong>${escapeHtml(i.title||i.label||'')}</strong><small class="item-meta">${escapeHtml(i.category||'')}</small><span class="item-description">${escapeHtml(i.description||'')}</span>${i.notes?`<span class="item-notes">${escapeHtml(i.notes)}</span>`:''}</span></li>`).join('')}</ul></article>`
  if(section.type==='form') return `<article>${title}<div>${(d.fields||[]).map(f=>{const value=state[f.id]??''; const label=`<label class="field"><span>${escapeHtml(f.label||f.id)}</span>`; if(f.type==='select'||f.type==='multiselect'){const multiple=f.type==='multiselect'?' multiple':''; const values=Array.isArray(value)?value:[value]; return `${label}<select data-field="${escapeHtml(f.id)}"${multiple}>${(f.options||[]).map(o=>`<option value="${escapeHtml(o.value??o)}" ${values.includes(o.value??o)?'selected':''}>${escapeHtml(o.label??o)}</option>`).join('')}</select></label>`} return `${label}<input type="text" data-field="${escapeHtml(f.id)}" value="${escapeHtml(value)}" placeholder="${escapeHtml(f.placeholder||'')}"></label>`}).join('')}</div></article>`
  return ''
}
function renderSections(data, state) { return (Array.isArray(data?.sections)?data.sections:[]).map(s=>renderSection(s,state)).join('') }

function artifactPage(a, requestedVersion) { const version = requestedVersion && Number.isInteger(requestedVersion) && requestedVersion > 0 ? requestedVersion : a.latest_version; const b=getBundle(a.id,version); if (!b) return shell('404','<h1>Versión no encontrada</h1>'); const items=b?.data?.widgets?.reviewChecklist?.items || []; const state=currentState(a.id,version); const sections=renderSections(b.data,state); const checks=items.map(i=>`<li class="check"><input type="checkbox" data-item="${escapeHtml(i.id)}" ${state[i.id]?'checked':''}><span>${escapeHtml(i.label)}</span></li>`).join(''); const versions=db.prepare('SELECT version,created_at FROM versions WHERE artifact_id=? ORDER BY version DESC').all(a.id).map(v=>`<option value="${v.version}" ${v.version===version?'selected':''}>v${v.version} · ${v.created_at}</option>`).join(''); const script=`document.querySelectorAll('[data-item]').forEach(el=>el.addEventListener('change',async()=>{const id=el.dataset.item;await fetch('/api/artifacts/${a.id}/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'reviewChecklist.itemToggled',payload:{itemId:id,checked:el.checked},idempotencyKey:crypto.randomUUID()})})}));document.querySelectorAll('[data-field]').forEach(el=>{const save=async()=>{const value=el.multiple?[...el.selectedOptions].map(o=>o.value):el.value;await fetch('/api/artifacts/${a.id}/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'widget.valueChanged',payload:{fieldId:el.dataset.field,value},idempotencyKey:crypto.randomUUID()})})};el.addEventListener(el.tagName==='INPUT'?'change':'change',save)});document.querySelector('#version-selector').onchange=e=>location.href='/artifacts/${a.slug}?v='+e.target.value;const viewedVersion=${version};setInterval(async()=>{try{const r=await fetch('/api/artifacts/${a.slug}/meta',{cache:'no-store'});const m=await r.json();if(m.latestVersion>viewedVersion)location.href='/artifacts/${a.slug}'}catch{}},3000)`; return shell(b?.artifact?.title || a.title, `<p><a href="/artifacts">← todos</a></p><h1>${escapeHtml(b?.artifact?.title || a.title)}</h1><p>${escapeHtml(b?.artifact?.description || '')}</p><div class="toolbar"><label>Versión <select id="version-selector">${versions}</select></label><span class="muted">Versión ${version} · publicada ${escapeHtml(b.version.createdAt)}</span></div>${sections || `<article><h2>Checklist</h2><ul>${checks || '<li>No hay contenido en esta versión.</li>'}</ul></article>`}`,script) }
async function handle(req,res) { try { const u=new URL(req.url,`http://${req.headers.host}`); if(req.method==='GET' && u.pathname==='/') return res.writeHead(302,{location:'/artifacts'}).end(); if(req.method==='GET'&&u.pathname==='/artifacts') return html(res,gallery()); if(req.method==='GET'&&u.pathname.startsWith('/artifacts/')) { const a=findArtifact(decodeURIComponent(u.pathname.split('/')[2])); if(!a) return html(res,shell('404','<h1>No encontrado</h1>')); return html(res,artifactPage(a,u.searchParams.has('v')?Number(u.searchParams.get('v')):undefined)) }
if(req.method==='GET'&&u.pathname==='/api/artifacts') return json(res,200,db.prepare('SELECT id,project,slug,title,updated_at,latest_version FROM artifacts ORDER BY updated_at DESC').all());
if(req.method==='GET'&&u.pathname.startsWith('/api/artifacts/')) { const parts=u.pathname.split('/').filter(Boolean); const a=findArtifact(parts[2]); if(!a) return json(res,404,{error:'not_found'}); if(parts[3]==='versions') return json(res,200,db.prepare('SELECT version,created_at FROM versions WHERE artifact_id=? ORDER BY version DESC').all(a.id)); if(parts[3]==='state') return json(res,200,currentState(a.id,1)); if(parts[3]==='meta') return json(res,200,{slug:a.slug,latestVersion:a.latest_version,updatedAt:a.updated_at}); }
if(req.method==='POST'&&!authorized(req)) return json(res,401,{error:'local_session_required'}); if(req.method==='POST'&&u.pathname.startsWith('/api/artifacts/')&&u.pathname.endsWith('/versions')) { const parts=u.pathname.split('/').filter(Boolean); const a=findArtifact(parts[2]); if(!a) return json(res,404,{error:'not_found'}); const body=await readBody(req); if(body?.schemaVersion!=='artifact/v1'||!body.data||!body.view) return json(res,400,{error:'invalid_bundle'}); const version=a.latest_version+1; const timestamp=now(); const normalized={...body,artifact:{...body.artifact,id:a.id,slug:a.slug,title:body.artifact?.title||a.title},version:{...body.version,id:'ver_'+randomUUID(),number:version,createdAt:timestamp,basedOnVersion:a.latest_version||null}}; db.prepare('INSERT INTO versions VALUES (?,?,?,?)').run(a.id,version,JSON.stringify(normalized),timestamp); db.prepare('UPDATE artifacts SET title=?,updated_at=?,latest_version=? WHERE id=?').run(normalized.artifact.title,timestamp,version,a.id); return json(res,201,{artifactId:a.id,version}); }
if(req.method==='POST'&&!authorized(req)) return json(res,401,{error:'local_session_required'}); if(req.method==='POST'&&u.pathname.startsWith('/api/artifacts/')&&u.pathname.endsWith('/restore')) { const parts=u.pathname.split('/').filter(Boolean); const a=findArtifact(parts[2]); if(!a) return json(res,404,{error:'not_found'}); const body=await readBody(req); const source=Number(body.version); const original=getBundle(a.id,source); if(!original) return json(res,404,{error:'version_not_found'}); const version=a.latest_version+1; const timestamp=now(); const restored={...original,version:{...original.version,id:'ver_'+randomUUID(),number:version,createdAt:timestamp,reason:'restore',basedOnVersion:source}}; db.prepare('INSERT INTO versions VALUES (?,?,?,?)').run(a.id,version,JSON.stringify(restored),timestamp); db.prepare('UPDATE artifacts SET updated_at=?,latest_version=? WHERE id=?').run(timestamp,version,a.id); return json(res,201,{artifactId:a.id,version,basedOnVersion:source}); }
if(req.method==='POST'&&!authorized(req)) return json(res,401,{error:'local_session_required'}); if(req.method==='POST'&&u.pathname.startsWith('/api/artifacts/')&&u.pathname.endsWith('/events')) { const parts=u.pathname.split('/').filter(Boolean); const a=findArtifact(parts[2]); if(!a) return json(res,404,{error:'not_found'}); const body=await readBody(req); if(typeof body.idempotencyKey!=='string') return json(res,400,{error:'invalid_event'}); const bundle=getBundle(a.id,a.latest_version); const checklistItems=[...(bundle?.data?.widgets?.reviewChecklist?.items||[]),...(bundle?.data?.sections||[]).filter(s=>s.type==='checklist').flatMap(s=>s.data?.items||[])]; const checklist=checklistItems.some(i=>i.id===body.payload?.itemId); const fields=(bundle?.data?.sections||[]).filter(s=>s.type==='form').flatMap(s=>s.data?.fields||[]); const field=fields.find(f=>f.id===body.payload?.fieldId); const validChecklist=body.type==='reviewChecklist.itemToggled'&&typeof body.payload?.itemId==='string'&&typeof body.payload?.checked==='boolean'&&checklist; const validField=body.type==='widget.valueChanged'&&field&&((field.type==='multiselect'&&Array.isArray(body.payload?.value))||((field.type==='text'||field.type==='select'||!field.type)&&typeof body.payload?.value==='string')); if(!validChecklist&&!validField) return json(res,400,{error:'invalid_event'}); const prior=db.prepare('SELECT event_id FROM events WHERE idempotency_key=?').get(body.idempotencyKey); if(prior) return json(res,200,{eventId:prior.event_id,replayed:true}); const eventId='evt_'+randomUUID(); db.prepare('INSERT INTO events VALUES (?,?,?,?,?,?,?)').run(eventId,a.id,a.latest_version,body.type,JSON.stringify(body.payload),body.idempotencyKey,now()); return json(res,201,{eventId,replayed:false}); }
return json(res,404,{error:'not_found'}); } catch(e) { return json(res,400,{error:e.message}) } }
createServer(handle).listen(port,'127.0.0.1',()=>console.log(`artifact-app listening on http://127.0.0.1:${port}/artifacts`))
