/**
 * Events list page - using generic entity list system
 */
import { EventsPageComponent, EventsRoute } from '@/features/events/config/events.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [46fc0f72-7f41-4c89-8a72-bef4631ead5e]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = EventsRoute;
export default EventsPageComponent;
