import {
    EventLocationsPageComponent,
    EventLocationsRoute
} from '@/features/event-locations/config/event-locations.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [85c4ac5c-dd30-4561-bb44-132c033e13fa]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = EventLocationsRoute;
export default EventLocationsPageComponent;
