import {
    EventOrganizersPageComponent,
    EventOrganizersRoute
} from '@/features/event-organizers/config/event-organizers.config';
import { adminLogger } from '@/utils/logger';
import { createFileRoute } from '@tanstack/react-router';

// HACK [c60f5409-1887-4050-ba06-303dca1c1b85]: We need to add this log so that the type checker doesn’t complain about the unused import, which is auto-generated by TanStack when the project starts.
adminLogger.log(createFileRoute, 'This hack is to make typecheck happy');

export const Route = EventOrganizersRoute;
export default EventOrganizersPageComponent;
