/**
 * Accommodation Import — Raw-to-Draft Mapper (SPEC-222)
 *
 * Converts a {@link RawExtraction} (the loose, pre-validation bag produced by
 * an adapter) into a fully type-safe {@link AccommodationImportDraft} by
 * coercing each candidate field's value and validating it against the
 * corresponding Zod schema shape.
 *
 * **Key contracts:**
 * - Fields that fail coercion or Zod validation are silently dropped — never
 *   thrown. The caller always receives a valid (possibly empty) draft.
 * - Reviews and ratings are never mapped. `RawExtraction` already excludes
 *   them; this file adds no rating-field handling (SPEC-222 hard rule).
 * - Confidence is assigned purely from source: use `CONFIDENCE_BY_SOURCE[source]`.
 *
 * @module services/accommodation-import/mapping
 */

import {
    type AccommodationImportDraft,
    AccommodationImportDraftSchema,
    type FieldSource
} from '@repo/schemas';

import type { RawCandidateField, RawExtraction } from './adapter.types.js';

// ---------------------------------------------------------------------------
// CONFIDENCE_BY_SOURCE
// ---------------------------------------------------------------------------

/**
 * Default confidence score (0–100) for a field value given its extraction
 * source.
 *
 * Bands are chosen to reflect data reliability:
 * - `official_api` (95) — Data came directly from an official platform API.
 *   Highest confidence: machine-readable, structured, authoritative.
 * - `jsonld` (90)       — Parsed from a structured JSON-LD block. Very
 *   reliable: schema.org vocabulary with typed fields.
 * - `opengraph` (70)    — Parsed from Open Graph meta tags. Good reliability;
 *   intended for sharing but may be truncated or marketing-optimised.
 * - `meta` (65)         — Other HTML `<meta>` tags (description, keywords).
 *   Slightly less reliable than OG tags; prone to keyword stuffing.
 * - `text` (50)         — Extracted by heuristic DOM / text parsing.
 *   Medium confidence: pattern-matching may mis-identify values.
 * - `ai` (30)           — Inferred or generated by an AI model.
 *   Lowest confidence: plausible but unverified; requires host review.
 *
 * Being a `Record<FieldSource, number>` this object is exhaustiveness-checked:
 * adding a new `FieldSource` value in the schema will cause a TypeScript error
 * here until the band is defined.
 */
export const CONFIDENCE_BY_SOURCE: Readonly<Record<FieldSource, number>> = {
    official_api: 95,
    jsonld: 90,
    opengraph: 70,
    meta: 65,
    text: 50,
    ai: 30
} as const;

// ---------------------------------------------------------------------------
// Internal coercion helpers
// ---------------------------------------------------------------------------

/**
 * Coerces an unknown value to a trimmed string, or returns `undefined` when
 * the value cannot be meaningfully converted to a non-empty string.
 *
 * Accepts strings (trimmed) and numbers/booleans (via String conversion).
 * Rejects `null`, `undefined`, objects, and arrays.
 *
 * @param v - The raw candidate value.
 * @returns A trimmed string, or `undefined` if coercion is not possible.
 */
function toTrimmedString(v: unknown): string | undefined {
    if (typeof v === 'string') {
        return v.trim();
    }
    if (typeof v === 'number' || typeof v === 'boolean') {
        return String(v);
    }
    return undefined;
}

/**
 * Coerces an unknown value to a non-negative integer, or returns `undefined`.
 *
 * Accepts:
 * - Numbers — truncated with `Math.trunc` if fractional, rejected if negative.
 * - Numeric strings — parsed with `Number()`; rejected if NaN or negative.
 *
 * @param v - The raw candidate value.
 * @returns A non-negative integer, or `undefined` if coercion fails.
 */
function toNonNegativeInt(v: unknown): number | undefined {
    let n: number;
    if (typeof v === 'number') {
        n = Math.trunc(v);
    } else if (typeof v === 'string') {
        const parsed = Number(v.trim());
        if (Number.isNaN(parsed)) {
            return undefined;
        }
        n = Math.trunc(parsed);
    } else {
        return undefined;
    }
    return n >= 0 ? n : undefined;
}

/**
 * Coerces an unknown value to a non-negative number (float allowed), or
 * returns `undefined`.
 *
 * Accepts numbers and numeric strings. Rejects negative values.
 *
 * @param v - The raw candidate value.
 * @returns A non-negative number, or `undefined` if coercion fails.
 */
function toNonNegativeNumber(v: unknown): number | undefined {
    let n: number;
    if (typeof v === 'number') {
        n = v;
    } else if (typeof v === 'string') {
        const parsed = Number(v.trim());
        if (Number.isNaN(parsed)) {
            return undefined;
        }
        n = parsed;
    } else {
        return undefined;
    }
    return n >= 0 ? n : undefined;
}

/**
 * Coerces an unknown value to a WGS-84 coordinate pair `{ lat, long }` where
 * both members are strings (matching `CoordinatesSchema`).
 *
 * Accepts:
 * - An object with numeric or string `lat` / `long` (or `lng` / `longitude`) properties.
 * - An array of two numbers `[lat, long]`.
 *
 * @param v - The raw candidate value.
 * @returns `{ lat: string; long: string }` or `undefined` if coercion fails.
 */
function toCoordinates(v: unknown): { lat: string; long: string } | undefined {
    if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
        const obj = v as Record<string, unknown>;
        const rawLat = obj.lat ?? obj.latitude;
        const rawLong = obj.long ?? obj.lng ?? obj.longitude;

        if (rawLat === undefined || rawLong === undefined) {
            return undefined;
        }

        const lat = typeof rawLat === 'number' ? String(rawLat) : toTrimmedString(rawLat);
        const long = typeof rawLong === 'number' ? String(rawLong) : toTrimmedString(rawLong);

        if (lat === undefined || long === undefined) {
            return undefined;
        }
        return { lat, long };
    }

    if (Array.isArray(v) && v.length >= 2) {
        const [rawLat, rawLong] = v;
        if (typeof rawLat === 'number' && typeof rawLong === 'number') {
            return { lat: String(rawLat), long: String(rawLong) };
        }
    }

    return undefined;
}

// ---------------------------------------------------------------------------
// Typed partial-draft accumulators (avoid bracket-notation lint warnings)
// ---------------------------------------------------------------------------

/** Mutable partial of the extraInfo nested object while assembling. */
interface ExtraInfoAccum {
    capacity?: AccommodationImportDraft['extraInfo'] extends infer E | undefined
        ? E extends { capacity?: infer C }
            ? C
            : never
        : never;
    bedrooms?: AccommodationImportDraft['extraInfo'] extends infer E | undefined
        ? E extends { bedrooms?: infer B }
            ? B
            : never
        : never;
    beds?: AccommodationImportDraft['extraInfo'] extends infer E | undefined
        ? E extends { beds?: infer D }
            ? D
            : never
        : never;
    bathrooms?: AccommodationImportDraft['extraInfo'] extends infer E | undefined
        ? E extends { bathrooms?: infer R }
            ? R
            : never
        : never;
}

/** Mutable partial of the location nested object while assembling. */
interface LocationAccum {
    coordinates?: NonNullable<AccommodationImportDraft['location']>['coordinates'];
    street?: NonNullable<AccommodationImportDraft['location']>['street'];
    number?: NonNullable<AccommodationImportDraft['location']>['number'];
}

/** Mutable partial of the price nested object while assembling. */
interface PriceAccum {
    price?: NonNullable<AccommodationImportDraft['price']>['price'];
    currency?: NonNullable<AccommodationImportDraft['price']>['currency'];
}

/** Mutable partial of the contactInfo nested object while assembling. */
interface ContactInfoAccum {
    mobilePhone?: NonNullable<AccommodationImportDraft['contactInfo']>['mobilePhone'];
    website?: NonNullable<AccommodationImportDraft['contactInfo']>['website'];
}

/** Mutable partial of the seo nested object while assembling. */
interface SeoAccum {
    title?: NonNullable<AccommodationImportDraft['seo']>['title'];
    description?: NonNullable<AccommodationImportDraft['seo']>['description'];
}

// ---------------------------------------------------------------------------
// Internal per-field mapping helper
// ---------------------------------------------------------------------------

/**
 * Attempts to map a single string-valued candidate field into an
 * `{ value, confidence, source }` envelope using the given Zod schema.
 *
 * The schema receives the coerced value. If either coercion or validation
 * fails, returns `undefined` (field is dropped).
 *
 * @param candidate   - Raw candidate with unknown value and source tag.
 * @param coercedValue - Pre-coerced value to validate (already type-narrowed by caller).
 * @param schema      - Zod schema for the wrapped `importedField` object.
 * @param sources     - Set to register the source in on success.
 * @returns The validated envelope or `undefined` on failure.
 */
function tryMapField<T>(
    candidate: RawCandidateField,
    coercedValue: T,
    schema: { safeParse: (v: unknown) => { success: true; data: unknown } | { success: false } },
    sources: Set<FieldSource>
): { value: T; confidence: number; source: FieldSource } | undefined {
    const envelope = {
        value: coercedValue,
        confidence: CONFIDENCE_BY_SOURCE[candidate.source],
        source: candidate.source
    };
    const result = schema.safeParse(envelope);
    if (!result.success) {
        return undefined;
    }
    sources.add(candidate.source);
    return envelope;
}

// ---------------------------------------------------------------------------
// mapRawToDraft
// ---------------------------------------------------------------------------

/**
 * Converts a {@link RawExtraction} into a type-safe {@link AccommodationImportDraft}.
 *
 * For each candidate field in `raw`:
 * 1. Coerces the loose `unknown` value to the target type.
 * 2. Validates the coerced value against the corresponding Zod field schema
 *    (reached via `AccommodationImportDraftSchema.shape`).
 * 3. On validation success, wraps the value as `{ value, confidence, source }`.
 * 4. On coercion or validation failure, silently drops the field.
 *
 * After assembling all passing fields, a final `AccommodationImportDraftSchema.safeParse`
 * guard is run. Any field that still fails at this stage (which should not
 * happen in practice) is stripped by Zod's default `.strip()` behaviour, so
 * the returned draft is always a valid `AccommodationImportDraft`.
 *
 * **Reviews and ratings are never mapped** — they are excluded from
 * `RawExtraction` by design (SPEC-222).
 *
 * @param input - Object containing the `RawExtraction` to map.
 * @returns An object with:
 *   - `draft`       — The valid, partially-populated import draft.
 *   - `methodsUsed` — Distinct list of {@link FieldSource} values that
 *                     contributed at least one field to the draft.
 *
 * @example
 * ```ts
 * const { draft, methodsUsed } = mapRawToDraft({
 *   raw: {
 *     sourcePlatform: 'airbnb',
 *     name: { value: 'Cabaña del Río', source: 'jsonld' },
 *     extraInfo: {
 *       capacity: { value: '6', source: 'text' },
 *     },
 *   },
 * });
 * // draft.name = { value: 'Cabaña del Río', confidence: 90, source: 'jsonld' }
 * // draft.extraInfo.capacity = { value: 6, confidence: 50, source: 'text' }
 * // methodsUsed = ['jsonld', 'text']
 * ```
 */
export const mapRawToDraft = (input: { readonly raw: RawExtraction }): {
    draft: AccommodationImportDraft;
    methodsUsed: FieldSource[];
} => {
    const { raw } = input;

    // Shortcut to the inner value-schema for each top-level importedField.
    const shape = AccommodationImportDraftSchema.shape;

    // Track which FieldSource values contributed at least one field.
    const usedSources = new Set<FieldSource>();

    // Accumulate the assembled draft as a typed partial before the final guard.
    const assembled: Partial<AccommodationImportDraft> = {};

    // -----------------------------------------------------------------------
    // name
    // -----------------------------------------------------------------------
    if (raw.name !== undefined) {
        const coerced = toTrimmedString(raw.name.value);
        if (coerced !== undefined) {
            const mapped = tryMapField(raw.name, coerced, shape.name.unwrap(), usedSources);
            if (mapped !== undefined) {
                assembled.name = mapped;
            }
        }
    }

    // -----------------------------------------------------------------------
    // summary
    // -----------------------------------------------------------------------
    if (raw.summary !== undefined) {
        const coerced = toTrimmedString(raw.summary.value);
        if (coerced !== undefined) {
            const mapped = tryMapField(raw.summary, coerced, shape.summary.unwrap(), usedSources);
            if (mapped !== undefined) {
                assembled.summary = mapped;
            }
        }
    }

    // -----------------------------------------------------------------------
    // description
    // -----------------------------------------------------------------------
    if (raw.description !== undefined) {
        const coerced = toTrimmedString(raw.description.value);
        if (coerced !== undefined) {
            const mapped = tryMapField(
                raw.description,
                coerced,
                shape.description.unwrap(),
                usedSources
            );
            if (mapped !== undefined) {
                assembled.description = mapped;
            }
        }
    }

    // -----------------------------------------------------------------------
    // type
    // -----------------------------------------------------------------------
    if (raw.type !== undefined) {
        const coerced = toTrimmedString(raw.type.value);
        if (coerced !== undefined) {
            const mapped = tryMapField(raw.type, coerced, shape.type.unwrap(), usedSources);
            if (mapped !== undefined) {
                // The value is validated by AccommodationTypeEnumSchema inside the
                // importedField; casting is safe because safeParse confirmed it.
                assembled.type = mapped as AccommodationImportDraft['type'];
            }
        }
    }

    // -----------------------------------------------------------------------
    // extraInfo
    // -----------------------------------------------------------------------
    if (raw.extraInfo !== undefined) {
        const extraInfoShape = shape.extraInfo.unwrap().shape;
        const extraInfoAccum: ExtraInfoAccum = {};

        if (raw.extraInfo.capacity !== undefined) {
            const coerced = toNonNegativeInt(raw.extraInfo.capacity.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.extraInfo.capacity,
                    coerced,
                    extraInfoShape.capacity.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    extraInfoAccum.capacity = mapped;
                }
            }
        }

        if (raw.extraInfo.bedrooms !== undefined) {
            const coerced = toNonNegativeInt(raw.extraInfo.bedrooms.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.extraInfo.bedrooms,
                    coerced,
                    extraInfoShape.bedrooms.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    extraInfoAccum.bedrooms = mapped;
                }
            }
        }

        if (raw.extraInfo.beds !== undefined) {
            const coerced = toNonNegativeInt(raw.extraInfo.beds.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.extraInfo.beds,
                    coerced,
                    extraInfoShape.beds.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    extraInfoAccum.beds = mapped;
                }
            }
        }

        if (raw.extraInfo.bathrooms !== undefined) {
            const coerced = toNonNegativeInt(raw.extraInfo.bathrooms.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.extraInfo.bathrooms,
                    coerced,
                    extraInfoShape.bathrooms.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    extraInfoAccum.bathrooms = mapped;
                }
            }
        }

        if (Object.keys(extraInfoAccum).length > 0) {
            assembled.extraInfo = extraInfoAccum;
        }
    }

    // -----------------------------------------------------------------------
    // location
    // -----------------------------------------------------------------------
    if (raw.location !== undefined) {
        const locationShape = shape.location.unwrap().shape;
        const locationAccum: LocationAccum = {};

        if (raw.location.coordinates !== undefined) {
            const coerced = toCoordinates(raw.location.coordinates.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.location.coordinates,
                    coerced,
                    locationShape.coordinates.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    locationAccum.coordinates = mapped;
                }
            }
        }

        if (raw.location.street !== undefined) {
            const coerced = toTrimmedString(raw.location.street.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.location.street,
                    coerced,
                    locationShape.street.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    locationAccum.street = mapped;
                }
            }
        }

        if (raw.location.number !== undefined) {
            const coerced = toTrimmedString(raw.location.number.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.location.number,
                    coerced,
                    locationShape.number.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    locationAccum.number = mapped;
                }
            }
        }

        if (Object.keys(locationAccum).length > 0) {
            assembled.location = locationAccum;
        }
    }

    // -----------------------------------------------------------------------
    // price
    // -----------------------------------------------------------------------
    if (raw.price !== undefined) {
        const priceShape = shape.price.unwrap().shape;
        const priceAccum: PriceAccum = {};

        if (raw.price.price !== undefined) {
            const coerced = toNonNegativeNumber(raw.price.price.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.price.price,
                    coerced,
                    priceShape.price.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    priceAccum.price = mapped;
                }
            }
        }

        if (raw.price.currency !== undefined) {
            const coerced = toTrimmedString(raw.price.currency.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.price.currency,
                    coerced,
                    priceShape.currency.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    priceAccum.currency = mapped;
                }
            }
        }

        if (Object.keys(priceAccum).length > 0) {
            assembled.price = priceAccum;
        }
    }

    // -----------------------------------------------------------------------
    // contactInfo
    // -----------------------------------------------------------------------
    if (raw.contactInfo !== undefined) {
        const contactShape = shape.contactInfo.unwrap().shape;
        const contactAccum: ContactInfoAccum = {};

        if (raw.contactInfo.mobilePhone !== undefined) {
            const coerced = toTrimmedString(raw.contactInfo.mobilePhone.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.contactInfo.mobilePhone,
                    coerced,
                    contactShape.mobilePhone.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    contactAccum.mobilePhone = mapped;
                }
            }
        }

        if (raw.contactInfo.website !== undefined) {
            const coerced = toTrimmedString(raw.contactInfo.website.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.contactInfo.website,
                    coerced,
                    contactShape.website.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    contactAccum.website = mapped;
                }
            }
        }

        if (Object.keys(contactAccum).length > 0) {
            assembled.contactInfo = contactAccum;
        }
    }

    // -----------------------------------------------------------------------
    // seo
    // -----------------------------------------------------------------------
    if (raw.seo !== undefined) {
        const seoShape = shape.seo.unwrap().shape;
        const seoAccum: SeoAccum = {};

        if (raw.seo.title !== undefined) {
            const coerced = toTrimmedString(raw.seo.title.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.seo.title,
                    coerced,
                    seoShape.title.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    seoAccum.title = mapped;
                }
            }
        }

        if (raw.seo.description !== undefined) {
            const coerced = toTrimmedString(raw.seo.description.value);
            if (coerced !== undefined) {
                const mapped = tryMapField(
                    raw.seo.description,
                    coerced,
                    seoShape.description.unwrap(),
                    usedSources
                );
                if (mapped !== undefined) {
                    seoAccum.description = mapped;
                }
            }
        }

        if (Object.keys(seoAccum).length > 0) {
            assembled.seo = seoAccum;
        }
    }

    // -----------------------------------------------------------------------
    // Final safeParse guard
    // -----------------------------------------------------------------------
    // Run the whole assembled object through the top-level schema. Any field
    // that still fails at this stage (e.g., an upstream schema change) is
    // stripped by Zod's default `.strip()` behaviour, so we always return a
    // valid draft.
    const finalResult = AccommodationImportDraftSchema.safeParse(assembled);

    // In the unlikely event that the entire object fails (e.g., a malformed
    // nested structure), fall back to an empty draft rather than throwing.
    const draft: AccommodationImportDraft = finalResult.success ? finalResult.data : {};

    const methodsUsed = Array.from(usedSources);

    return { draft, methodsUsed };
};
