import { z } from 'zod';
import { SocialPlatformEnumSchema } from '../../enums/social-platform.schema.js';
import { SocialSourceEnumSchema } from '../../enums/social-source.schema.js';

/**
 * SocialAiRequest entity schema.
 * Append-only log of every GPT ingestion call that led to (or attempted) a draft.
 *
 * NO soft-delete columns and NO audit FKs by design — this table is
 * a permanent audit record. Rows are never deleted by application code.
 */
export const SocialAiRequestSchema = z.object({
    id: z.string().uuid({ message: 'zodError.socialAiRequest.id.uuid' }),
    /**
     * Opaque ID assigned by the GPT to this request.
     * UNIQUE — used to detect duplicate submissions at the ingestion layer.
     */
    requestId: z.string().min(1, { message: 'zodError.socialAiRequest.requestId.required' }),
    source: SocialSourceEnumSchema,
    /** Content topic / subject of the post idea */
    topic: z.string().optional(),
    /** Free-text idea or prompt from the operator */
    userIdea: z.string().optional(),
    /** Content pillar (e.g. "travel", "gastronomy") */
    pillar: z.string().optional(),
    /** Optional audience hint from the GPT */
    audienceId: z.string().uuid({ message: 'zodError.socialAiRequest.audienceId.uuid' }).optional(),
    /** JSON array of platform strings suggested by the GPT */
    suggestedPlatformsJson: z.array(z.string()).optional(),
    /** Suggested publish format string from the GPT */
    suggestedFormat: z.string().optional(),
    /** Caption base generated by GPT before admin editing */
    generatedCaptionBase: z.string().optional(),
    /** Full raw request payload as received */
    rawRequestJson: z.record(z.string(), z.unknown()).optional(),
    /** Full raw response payload returned by this handler */
    rawResponseJson: z.record(z.string(), z.unknown()).optional(),
    /** Processing status: "success" | "failed" | "partial" */
    status: z.string().min(1, { message: 'zodError.socialAiRequest.status.required' }),
    errorMessage: z.string().optional(),
    /** Suggested platform for the request */
    suggestedPlatform: SocialPlatformEnumSchema.optional(),
    createdAt: z.coerce.date({ message: 'zodError.common.createdAt.required' })
});

/** TypeScript type inferred from {@link SocialAiRequestSchema}. */
export type SocialAiRequest = z.infer<typeof SocialAiRequestSchema>;
