/**
 * @fileoverview
 * Data migration: 0030-clear-placeholder-blog-media
 *
 * Clears the fake `placehold.co` imagery that `0025-seed-real-blog-posts`
 * wrote for the real editorial blog posts and their branded author.
 *
 * ## Background
 *
 * `0025` deliberately stamped every real post with a resolvable-but-obviously-
 * fake cover (`https://placehold.co/1200x630/1b6b4c/ffffff?text=Hospeda`) and
 * gave the "Equipo Hospeda" author the 400x400 variant as an avatar, on the
 * assumption that an operator would swap them for real assets from the admin
 * panel once the photography landed. That never happened, and the placeholders
 * are actively harmful:
 *
 * - The public post detail page has no way to tell them from a real upload —
 *   the host is `placehold.co`, which does not contain the substring the web
 *   uses to recognise its own local placeholders — so every post renders a
 *   flat green rectangle where the cover should be.
 * - The admin editor shows a populated "featured image" slot, so an editor
 *   believes an image was uploaded when none ever was.
 *
 * Removing the reference makes the data honest: the post genuinely has no
 * cover, the web renders nothing (no placeholder, no reserved space), and the
 * admin shows an empty slot inviting a real upload. The author card falls back
 * to its initial-letter avatar, which is already implemented.
 *
 * ## Scope guards
 *
 * Both updates match the placeholder URL **exactly**. A post whose cover was
 * already replaced with a real asset, or an author who already has a real
 * avatar, is untouched — so this can never destroy work an operator did
 * between `0025` and this migration.
 *
 * Only the `featuredImage` key is removed from `posts.media`; any `gallery` or
 * `videos` a post may have acquired since survives. `media` collapses to NULL
 * only when `featuredImage` was its last remaining key. The same applies to the
 * author's `profile`: only `avatar` is dropped, the `bio` stays.
 *
 * The authored `featuredImageCaption` / `featuredImageAlt` in the article
 * fixtures are intentionally kept in the repo — they describe the photo that
 * should eventually be shot, and `0025` will use them again once real URLs
 * exist.
 *
 * ## Idempotency
 *
 * Re-running is a no-op: after the first pass no row matches the placeholder
 * URL any more.
 *
 * ## `destructive` flag decision
 *
 * `false` — mirrors `0020-backfill-accommodation-seo-titles`. This is a
 * targeted, exact-match-guarded, idempotent edit of a single JSONB key on a
 * well-identified set of rows. It deletes no human-authored content (both URLs
 * are constants generated by `0025`, reproduced below), and it is trivially
 * reversible by writing the same constants back.
 */
import { posts, sql, users } from '@repo/db';
import type { SeedMigrationCtx, SeedMigrationModule, SeedMigrationResult } from './types.js';

export const meta = {
    name: '0030-clear-placeholder-blog-media',
    group: 'required',
    destructive: false
} as const satisfies SeedMigrationModule['meta'];

/**
 * The exact fake cover URL written by `0025-seed-real-blog-posts`. Kept as a
 * literal (rather than imported from `0025`) so this migration stays a frozen
 * historical record even if `0025` is later edited.
 */
const PLACEHOLDER_FEATURED_IMAGE_URL = 'https://placehold.co/1200x630/1b6b4c/ffffff?text=Hospeda';

/** The exact fake avatar URL written by `0025-seed-real-blog-posts`. */
const PLACEHOLDER_AVATAR_URL = 'https://placehold.co/400x400/1b6b4c/ffffff?text=Hospeda';

/** Unique identity of the editorial author created by `0025`. */
const EDITORIAL_EMAIL = 'editorial@hospeda.com.ar';

export async function up(ctx: SeedMigrationCtx): Promise<SeedMigrationResult> {
    // Drop only the `featuredImage` key; collapse `media` to NULL when that
    // key was all it held.
    const clearedPosts = await ctx.db
        .update(posts)
        .set({
            media: sql`NULLIF(${posts.media} - 'featuredImage', '{}'::jsonb)`,
            updatedAt: new Date()
        })
        .where(sql`${posts.media}->'featuredImage'->>'url' = ${PLACEHOLDER_FEATURED_IMAGE_URL}`)
        .returning({ slug: posts.slug });

    // Drop only the `avatar` key so the author's `bio` survives.
    const clearedAuthors = await ctx.db
        .update(users)
        .set({
            profile: sql`NULLIF(${users.profile} - 'avatar', '{}'::jsonb)`,
            updatedAt: new Date()
        })
        .where(
            sql`${users.email} = ${EDITORIAL_EMAIL} AND ${users.profile}->>'avatar' = ${PLACEHOLDER_AVATAR_URL}`
        )
        .returning({ email: users.email });

    return {
        summary: `Cleared placeholder imagery from ${clearedPosts.length} blog post(s) and ${clearedAuthors.length} editorial author profile(s).`,
        counts: {
            postsCleared: clearedPosts.length,
            authorsCleared: clearedAuthors.length
        }
    };
}
