import { z } from 'zod';
import {
    AccommodationExternalListingIdSchema,
    AccommodationExternalReputationIdSchema,
    AccommodationIdSchema
} from '../../common/id.schema.js';
import { ExternalPlatformEnumSchema } from '../../enums/external-platform.schema.js';
import { ExternalReviewSnippetSchema } from './accommodation-external-listing.schema.js';

// ============================================================================
// RUN STATUS
// ============================================================================

/**
 * Async run status for Apify-backed external reputation fetches.
 *
 * - idle: No run in progress (default). Row holds either cached data or an error.
 * - pending: A run has been enqueued with Apify but has not started yet.
 * - running: Apify has confirmed the run is in progress.
 *
 * This status is INTERNAL ONLY — never exposed via public block schemas.
 */
export const ExternalReputationRunStatusSchema = z.enum(['idle', 'pending', 'running'], {
    error: () => ({ message: 'zodError.accommodationExternalReputation.runStatus.invalid' })
});
export type ExternalReputationRunStatus = z.infer<typeof ExternalReputationRunStatusSchema>;

// ============================================================================
// FETCH STATUS
// ============================================================================

/**
 * Result of the last attempt to fetch reputation data from the external
 * platform.
 *
 * - ok: Data was fetched successfully.
 * - blocked: The platform actively blocked the request (e.g. 403 / CAPTCHA).
 * - not_found: The listing ID no longer resolves on the platform.
 * - error: Any other non-recoverable or transient error.
 */
export const ExternalFetchStatusSchema = z.enum(['ok', 'blocked', 'not_found', 'error'], {
    error: () => ({ message: 'zodError.accommodationExternalReputation.fetchStatus.invalid' })
});
export type ExternalFetchStatus = z.infer<typeof ExternalFetchStatusSchema>;

// ============================================================================
// ACCOMMODATION EXTERNAL REPUTATION SCHEMA
// ============================================================================

/**
 * Schema for the cached reputation data fetched from an external platform.
 *
 * One row per (accommodation, platform) — updated by the background fetcher
 * job. All aggregate fields (rating, reviewsCount) are nullable because a
 * fresh listing may not have reviews yet, and a blocked fetch leaves the
 * previously-cached values intact.
 *
 * This record does NOT extend the standard audit/lifecycle fields because it is
 * purely cache-managed (no owner/admin writes, no soft-delete workflow). Only
 * `createdAt` and `updatedAt` are tracked for cache-age purposes.
 */
export const AccommodationExternalReputationSchema = z.object({
    /** Primary key — UUID generated by the database. */
    id: AccommodationExternalReputationIdSchema,
    /** FK to the accommodation. */
    accommodationId: AccommodationIdSchema,
    /** Platform from which this reputation data was fetched. */
    platform: ExternalPlatformEnumSchema,
    /**
     * FK to the {@link AccommodationExternalListing} row that provides the
     * externalId / URL used for the fetch.
     */
    listingId: AccommodationExternalListingIdSchema,
    /**
     * Overall numeric rating as returned by the platform (e.g. 4.7 on a
     * 1–5 scale). Stored as a string in Postgres NUMERIC columns; the
     * transform coerces to a JS number at parse time.
     */
    rating: z
        .union([z.string(), z.number()])
        .transform((v) => (typeof v === 'string' ? Number.parseFloat(v) : v))
        .pipe(z.number().min(0).max(10))
        .nullish(),
    /** Total number of reviews as returned by the platform. */
    reviewsCount: z.number().int().min(0).nullish(),
    /**
     * Deep link to the listing reviews section (e.g. the Google Maps URL
     * that opens directly to the reviews tab). Used when showLink is true.
     */
    deepLink: z.string().url().nullish(),
    /**
     * Up to N most recent / most relevant review snippets fetched from the
     * platform, stored as JSONB. Null when the platform does not support
     * snippet fetching or the last fetch status is not 'ok'.
     */
    snippets: z.array(ExternalReviewSnippetSchema).nullish(),
    /**
     * Timestamp of the last successful snippet fetch. Used by the public
     * schema TTL logic to decide whether to surface snippets.
     */
    snippetsFetchedAt: z.coerce.date().nullish(),
    /**
     * Timestamp of the last successful aggregate (rating + reviewsCount)
     * fetch, regardless of whether snippets were updated.
     */
    aggregateFetchedAt: z.coerce.date().nullish(),
    /** Outcome of the most recent fetch attempt. */
    fetchStatus: ExternalFetchStatusSchema,
    /**
     * Human-readable diagnostic message from the last fetch attempt.
     * Populated on non-ok statuses to aid debugging.
     */
    fetchMessage: z.string().nullish(),
    /**
     * Async run status for Apify-backed platforms.
     * Internal coordination field — never exposed via public block schemas.
     * Defaults to 'idle' (no run in progress).
     */
    runStatus: ExternalReputationRunStatusSchema.default('idle'),
    /**
     * Apify run ID returned by POST /v2/acts/{actor}/runs.
     * Set when runStatus = 'pending'; null when idle or not applicable.
     */
    apifyRunId: z.string().nullish(),
    /**
     * Default dataset ID for the Apify run.
     * Set by the polling cron after the run succeeds; null when idle.
     */
    apifyDatasetId: z.string().nullish(),
    /**
     * Wall-clock time when startRun() was called.
     * Used by the timeout sweep in the polling cron.
     */
    runStartedAt: z.coerce.date().nullish(),
    /** Row creation timestamp (set by the DB on first upsert). */
    createdAt: z.coerce.date({
        message: 'zodError.common.createdAt.required'
    }),
    /** Timestamp of the last upsert (updated by every fetch run). */
    updatedAt: z.coerce.date({
        message: 'zodError.common.updatedAt.required'
    })
});
export type AccommodationExternalReputation = z.infer<typeof AccommodationExternalReputationSchema>;
