import { z } from 'zod';
import { BaseAuditFields } from '../../common/audit.schema.js';
import {
    AccommodationExternalListingIdSchema,
    AccommodationIdSchema
} from '../../common/id.schema.js';
import { BaseLifecycleFields } from '../../common/lifecycle.schema.js';
import { ExternalPlatformEnumSchema } from '../../enums/external-platform.schema.js';

// ============================================================================
// SNIPPET SCHEMA
// ============================================================================

/**
 * A single review snippet fetched from an external platform.
 * Stored as JSONB in the reputation table; also referenced here for
 * documentation purposes.
 */
export const ExternalReviewSnippetSchema = z.object({
    /** Display name of the reviewer as returned by the platform. */
    author: z.string().min(1),
    /** Excerpt of the review text. */
    text: z.string().min(1),
    /** Numeric star rating given by the reviewer (platform-specific scale). */
    rating: z.number().nullish(),
    /** ISO 8601 timestamp string as returned by the platform. */
    timeIso: z.string().nullish(),
    /** URL to the reviewer's profile on the platform. */
    authorUrl: z.string().url().nullish(),
    /** URL to the reviewer's profile photo. */
    profilePhoto: z.string().url().nullish(),
    /** Human-readable relative time string (e.g. "hace 2 semanas"). */
    relativeTime: z.string().nullish()
});
export type ExternalReviewSnippet = z.infer<typeof ExternalReviewSnippetSchema>;

// ============================================================================
// ACCOMMODATION EXTERNAL LISTING SCHEMA
// ============================================================================

/**
 * Schema for an external listing link registered by the accommodation owner.
 * One row per (accommodation, platform) pair; the owner provides the URL and
 * optional externalId so the fetcher can resolve the correct place/listing.
 *
 * Audit + lifecycle fields follow the standard conventions used across all
 * entities in this codebase.
 */
export const AccommodationExternalListingSchema = z.object({
    /** Primary key — UUID generated by the database. */
    id: AccommodationExternalListingIdSchema,
    /** FK to the accommodation this listing belongs to. */
    accommodationId: AccommodationIdSchema,
    /** Platform where the listing lives (e.g. GOOGLE, BOOKING, AIRBNB). */
    platform: ExternalPlatformEnumSchema,
    /**
     * Full public URL to the listing on the external platform.
     * Shown to users when showLink is true.
     */
    url: z.string().url({ message: 'zodError.accommodationExternalListing.url.invalidUrl' }),
    /**
     * Platform-specific identifier for the listing (e.g. Google place_id,
     * Booking property ID). Used by the reputation fetcher; not surfaced
     * publicly.
     */
    externalId: z.string().min(1).nullish(),
    /**
     * When true, the public detail page shows a link to this listing so that
     * visitors can navigate to the external profile.
     */
    showLink: z.boolean().default(false),
    /**
     * When true, review snippets fetched from this platform are shown on the
     * public detail page (subject to TTL and platform support).
     */
    showReviews: z.boolean().default(false),
    /**
     * Set to true by an admin after the listing URL has been verified as
     * genuine. Unverified listings are stored but not yet surfaced publicly.
     */
    verified: z.boolean().default(false),
    // Standard audit + lifecycle
    ...BaseAuditFields,
    ...BaseLifecycleFields
});
export type AccommodationExternalListing = z.infer<typeof AccommodationExternalListingSchema>;

// ============================================================================
// CREATE SCHEMA
// ============================================================================

/**
 * Input schema for creating a new external listing.
 * Omits server-managed fields (id, audit timestamps, verification).
 * The service sets `verified = false` on creation; it is not user-settable.
 */
export const CreateAccommodationExternalListingSchema = AccommodationExternalListingSchema.omit({
    id: true,
    createdAt: true,
    updatedAt: true,
    createdById: true,
    updatedById: true,
    deletedAt: true,
    deletedById: true,
    verified: true,
    lifecycleState: true
});
export type CreateAccommodationExternalListingInput = z.infer<
    typeof CreateAccommodationExternalListingSchema
>;

// ============================================================================
// UPDATE SCHEMA
// ============================================================================

/**
 * Input schema for updating an external listing (full or partial PATCH).
 * The `platform` is immutable after creation (change it by deleting and
 * re-creating the listing). `verified` is admin-only and managed through a
 * dedicated endpoint.
 */
export const UpdateAccommodationExternalListingSchema = AccommodationExternalListingSchema.omit({
    id: true,
    accommodationId: true,
    platform: true,
    createdAt: true,
    updatedAt: true,
    createdById: true,
    updatedById: true,
    deletedAt: true,
    deletedById: true,
    verified: true,
    lifecycleState: true
}).partial();
export type UpdateAccommodationExternalListingInput = z.infer<
    typeof UpdateAccommodationExternalListingSchema
>;
