import { z } from 'zod';
import { BaseAuditFields } from '../../common/audit.schema.js';
import {
    AccommodationExternalListingIdSchema,
    AccommodationIdSchema
} from '../../common/id.schema.js';
import { BaseLifecycleFields } from '../../common/lifecycle.schema.js';
import { ExternalPlatformEnumSchema } from '../../enums/external-platform.schema.js';
import { stripShapeDefaults } from '../../utils/utils.js';

// ============================================================================
// SNIPPET SCHEMA
// ============================================================================

/**
 * A single review snippet fetched from an external platform.
 * Stored as JSONB in the reputation table; also referenced here for
 * documentation purposes.
 */
export const ExternalReviewSnippetSchema = z.object({
    /** Display name of the reviewer as returned by the platform. */
    author: z.string().min(1),
    /** Excerpt of the review text. */
    text: z.string().min(1),
    /** Numeric star rating given by the reviewer (platform-specific scale). */
    rating: z.number().nullish(),
    /** ISO 8601 timestamp string as returned by the platform. */
    timeIso: z.string().nullish(),
    /** URL to the reviewer's profile on the platform. */
    authorUrl: z.string().url().nullish(),
    /** URL to the reviewer's profile photo. */
    profilePhoto: z.string().url().nullish(),
    /** Human-readable relative time string (e.g. "hace 2 semanas"). */
    relativeTime: z.string().nullish()
});
export type ExternalReviewSnippet = z.infer<typeof ExternalReviewSnippetSchema>;

// ============================================================================
// ACCOMMODATION EXTERNAL LISTING SCHEMA
// ============================================================================

/**
 * Schema for an external listing link registered by the accommodation owner.
 * One row per (accommodation, platform) pair; the owner provides the URL and
 * optional externalId so the fetcher can resolve the correct place/listing.
 *
 * Audit + lifecycle fields follow the standard conventions used across all
 * entities in this codebase.
 */
export const AccommodationExternalListingSchema = z.object({
    /** Primary key — UUID generated by the database. */
    id: AccommodationExternalListingIdSchema,
    /** FK to the accommodation this listing belongs to. */
    accommodationId: AccommodationIdSchema,
    /** Platform where the listing lives (e.g. GOOGLE, BOOKING, AIRBNB). */
    platform: ExternalPlatformEnumSchema,
    /**
     * Full public URL to the listing on the external platform.
     * Shown to users when showLink is true.
     */
    url: z.string().url({ message: 'zodError.accommodationExternalListing.url.invalidUrl' }),
    /**
     * Platform-specific identifier for the listing (e.g. Google place_id,
     * Booking property ID). Used by the reputation fetcher; not surfaced
     * publicly.
     */
    externalId: z.string().min(1).nullish(),
    /**
     * When true, the public detail page shows a link to this listing so that
     * visitors can navigate to the external profile.
     */
    showLink: z.boolean().default(false),
    /**
     * When true, review snippets fetched from this platform are shown on the
     * public detail page (subject to TTL and platform support).
     */
    showReviews: z.boolean().default(false),
    /**
     * Set to true by an admin after the listing URL has been verified as
     * genuine. Unverified listings are stored but not yet surfaced publicly.
     */
    verified: z.boolean().default(false),
    // Standard audit + lifecycle
    ...BaseAuditFields,
    ...BaseLifecycleFields
});
export type AccommodationExternalListing = z.infer<typeof AccommodationExternalListingSchema>;

// ============================================================================
// CREATE SCHEMA
// ============================================================================

/**
 * Input schema for creating a new external listing.
 * Omits server-managed fields (id, audit timestamps, verification).
 * The service sets `verified = false` on creation; it is not user-settable.
 */
export const CreateAccommodationExternalListingSchema = AccommodationExternalListingSchema.omit({
    id: true,
    createdAt: true,
    updatedAt: true,
    createdById: true,
    updatedById: true,
    deletedAt: true,
    deletedById: true,
    verified: true,
    lifecycleState: true
});
export type CreateAccommodationExternalListingInput = z.infer<
    typeof CreateAccommodationExternalListingSchema
>;

// ============================================================================
// UPDATE SCHEMA
// ============================================================================

/**
 * Input schema for updating an external listing (full or partial PATCH).
 * The `platform` is immutable after creation (change it by deleting and
 * re-creating the listing). `verified` is admin-only and managed through a
 * dedicated endpoint.
 *
 * **`stripShapeDefaults` is load-bearing here (H-129).** `showLink` and
 * `showReviews` carry `.default(false)`, and in Zod 4 `.partial()` does NOT
 * suppress a default: parsing `{ showLink: true }` against a plain
 * `.partial()` yields `{ showLink: true, showReviews: false }`. That parsed
 * object is spread straight into a literal SQL `SET`, so toggling one switch
 * turned the other one off — the owner's UI sends exactly one field per
 * toggle. Stripping the defaults first makes an absent key stay absent.
 */
export const UpdateAccommodationExternalListingSchema = z
    .object(
        stripShapeDefaults(
            AccommodationExternalListingSchema.omit({
                id: true,
                accommodationId: true,
                platform: true,
                createdAt: true,
                updatedAt: true,
                createdById: true,
                updatedById: true,
                deletedAt: true,
                deletedById: true,
                verified: true,
                lifecycleState: true
            }).shape
        )
    )
    .partial();
export type UpdateAccommodationExternalListingInput = z.infer<
    typeof UpdateAccommodationExternalListingSchema
>;

// ============================================================================
// LIST RESPONSE SCHEMA (HOS-290)
// ============================================================================

/**
 * Reputation metadata that accompanies the owner's listing list.
 *
 * Both values are things the editor needs to render the section but that do
 * NOT live on a listing row: the master toggle is a column on `accommodations`,
 * and the "last updated" timestamp is the most recent successful aggregate
 * fetch across every platform row in `accommodation_external_reputation`.
 */
export const AccommodationExternalReputationMetaSchema = z.object({
    /** `accommodations.show_external_reputation` — the owner's master switch. */
    showExternalReputation: z.boolean(),
    /**
     * Most recent `aggregate_fetched_at` across all platforms for this
     * accommodation, or `null` when nothing has ever been fetched.
     */
    aggregateFetchedAt: z.coerce.date().nullable()
});
export type AccommodationExternalReputationMeta = z.infer<
    typeof AccommodationExternalReputationMetaSchema
>;

/**
 * Response contract for `GET /api/v1/protected/accommodations/:id/external-listings`.
 *
 * HOS-290: the route used to return a BARE ARRAY while
 * `ExternalReputationSection.client.tsx` read `body.data.reputation
 * .showExternalReputation` off it — a `TypeError` on every mount, caught by the
 * component's own try/catch, so the entire "Reputación externa" section showed
 * nothing but a red error banner in production. Nothing caught it because the
 * client declared its own hand-written response interface and the component
 * test mocked THAT invented shape rather than the real one.
 *
 * Declaring the contract here is the actual fix: the route validates against it
 * (fail-closed, via `stripWithSchema`), the client consumes the inferred type
 * instead of re-describing it, and the test builds its fixture through it. One
 * definition, verifiable by the type system, instead of two that can drift.
 */
export const AccommodationExternalListingsResponseSchema = z.object({
    /** Every non-deleted listing config registered for the accommodation. */
    listings: z.array(AccommodationExternalListingSchema),
    /** Accommodation-level reputation metadata (not per-listing). */
    reputation: AccommodationExternalReputationMetaSchema
});
export type AccommodationExternalListingsResponse = z.infer<
    typeof AccommodationExternalListingsResponseSchema
>;
