/**
 * Accommodations list page — using the generic entity list system.
 *
 * SPEC-169 T-022 (D5): adds a `beforeLoad` owner-scope guard that redirects
 * any actor holding ACCOMMODATION_VIEW_OWN (but NOT ACCOMMODATION_VIEW_ALL)
 * to /me/accommodations before any global data fetch. This is belt-and-suspenders
 * defence on top of the server-side forced owner-scoping in §5.2.
 *
 * The component and validate-search config come from the AccommodationsRoute
 * generated by the createEntityListPage factory. We re-create the route here
 * (same path) adding the beforeLoad hook; TanStack Router merges the route
 * definition with the file-based routing tree.
 */

import {
    AccommodationsPageComponent,
    AccommodationsRoute
} from '@/features/accommodations/config/accommodations.config';
import type { AuthState } from '@/lib/auth-session';
import { decideOwnerScopedRedirect } from '@/lib/owner-scoped-guard';
import { createFileRoute, redirect } from '@tanstack/react-router';

// TanStack Router requirement: bare reference prevents unused-import removal by bundler.
createFileRoute;

/**
 * Accommodations list route with owner-scope guard.
 *
 * Re-uses the validateSearch from the factory-generated route and wires in
 * the beforeLoad D5 guard.
 */
export const Route = createFileRoute('/_authed/accommodations/')({
    // Mirror the validateSearch from the factory route so URL search params still work.
    validateSearch: AccommodationsRoute.options.validateSearch,
    beforeLoad: ({ context }) => {
        // TYPE-WORKAROUND: TanStack Router context type can't infer dynamically-loaded
        // auth fields populated in the parent _authed beforeLoad; cast restores the
        // AuthState shape set there.
        const authState = context as unknown as AuthState;

        const redirectTarget = decideOwnerScopedRedirect({
            permissions: authState.permissions ?? []
        });

        if (redirectTarget) {
            throw redirect({ to: redirectTarget as '/me/accommodations' });
        }
    },
    component: AccommodationsPageComponent
});
