name: Refresh Search Index

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v4 # O la versión más reciente

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm' # Habilita el caching para pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # O simplemente pnpm install si prefieres

      - name: Refresh materialized view
        run: node packages/db/scripts/refresh-search-view.js # Asegúrate que este script se ejecute con pnpm si es necesario, p.ej. pnpm run tu-script-de-refresh
